/*
    CAU ARPSE Monitoring - Updated Management Response rich text support

    This patch converts the existing DAC/PAC UPDATED_STATUS columns from
    VARCHAR2(200) to CLOB so Step 7 can store rich text management responses.

    Run this in the owning Oracle schema before using the Step 7 rich text
    fields in production. Recompile PKG_COMMERCIAL_AUDIT afterward with
    P_SAVE_ARPSE_DAC.P_UPDATED_STATUS and P_SAVE_ARPSE_PAC.P_UPDATED_STATUS
    declared as CLOB and without TRIM(P_UPDATED_STATUS).
*/

ALTER TABLE T_COM_AUDIT_ARPSE_DAC ADD (UPDATED_STATUS_CLOB CLOB);
UPDATE T_COM_AUDIT_ARPSE_DAC SET UPDATED_STATUS_CLOB = TO_CLOB(UPDATED_STATUS);
ALTER TABLE T_COM_AUDIT_ARPSE_DAC DROP COLUMN UPDATED_STATUS;
ALTER TABLE T_COM_AUDIT_ARPSE_DAC RENAME COLUMN UPDATED_STATUS_CLOB TO UPDATED_STATUS;

ALTER TABLE T_COM_AUDIT_ARPSE_DAC_HIST ADD (UPDATED_STATUS_CLOB CLOB);
UPDATE T_COM_AUDIT_ARPSE_DAC_HIST SET UPDATED_STATUS_CLOB = TO_CLOB(UPDATED_STATUS);
ALTER TABLE T_COM_AUDIT_ARPSE_DAC_HIST DROP COLUMN UPDATED_STATUS;
ALTER TABLE T_COM_AUDIT_ARPSE_DAC_HIST RENAME COLUMN UPDATED_STATUS_CLOB TO UPDATED_STATUS;

ALTER TABLE T_COM_AUDIT_ARPSE_PAC ADD (UPDATED_STATUS_CLOB CLOB);
UPDATE T_COM_AUDIT_ARPSE_PAC SET UPDATED_STATUS_CLOB = TO_CLOB(UPDATED_STATUS);
ALTER TABLE T_COM_AUDIT_ARPSE_PAC DROP COLUMN UPDATED_STATUS;
ALTER TABLE T_COM_AUDIT_ARPSE_PAC RENAME COLUMN UPDATED_STATUS_CLOB TO UPDATED_STATUS;

ALTER TABLE T_COM_AUDIT_ARPSE_PAC_HIST ADD (UPDATED_STATUS_CLOB CLOB);
UPDATE T_COM_AUDIT_ARPSE_PAC_HIST SET UPDATED_STATUS_CLOB = TO_CLOB(UPDATED_STATUS);
ALTER TABLE T_COM_AUDIT_ARPSE_PAC_HIST DROP COLUMN UPDATED_STATUS;
ALTER TABLE T_COM_AUDIT_ARPSE_PAC_HIST RENAME COLUMN UPDATED_STATUS_CLOB TO UPDATED_STATUS;

COMMIT;
