-- Phase 1 email-trigger attempt log. Run once in each application schema before deployment.
CREATE TABLE T_AU_EMAIL_TRIGGER_LOG
(
    ID              NUMBER(19)       NOT NULL,
    TRIGGER_DATE    TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
    MODULE          VARCHAR2(100)    NOT NULL,
    TRIGGER_POINT   VARCHAR2(200)    NOT NULL,
    REFERENCE_ID    VARCHAR2(200),
    TO_ADDRESS      VARCHAR2(2000),
    CC_ADDRESS      VARCHAR2(2000),
    EMAIL_SUBJECT   VARCHAR2(1000),
    STATUS          VARCHAR2(30)     NOT NULL,
    ERROR_MESSAGE   VARCHAR2(4000),
    SENT_ON         TIMESTAMP(6),
    CONSTRAINT PK_T_AU_EMAIL_TRIGGER_LOG PRIMARY KEY (ID),
    CONSTRAINT CK_T_AU_EMAIL_TRIGGER_STATUS CHECK
        (STATUS IN ('TRIGGERED','CONFIGURATION_MISSING','RECIPIENT_MISSING','SENT','SMTP_FAILED','FAILED'))
);

CREATE SEQUENCE SEQ_T_AU_EMAIL_TRIGGER_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IX_T_AU_EMAIL_TRIGGER_LOG_01
    ON T_AU_EMAIL_TRIGGER_LOG (TRIGGER_DATE, MODULE, TRIGGER_POINT, STATUS);

COMMENT ON TABLE T_AU_EMAIL_TRIGGER_LOG IS 'Phase 1 audit log for every application email-send attempt.';
