-- IAS generic email queue refactor
-- Deploy before PKG_IAS_NOTIFICATION.sql/ias_notification_centralization.sql and PKG_AE.sql.
SET DEFINE OFF
SET SERVEROUTPUT ON
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME='T_EMAIL_QUEUE';
  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE T_EMAIL_QUEUE (
      EMAIL_ID NUMBER NOT NULL, EVENT_CODE VARCHAR2(100 CHAR) NOT NULL,
      REF_ID1 NUMBER, REF_ID2 NUMBER, MAIL_TO VARCHAR2(2000 CHAR) NOT NULL,
      MAIL_CC VARCHAR2(2000 CHAR), SUBJECT VARCHAR2(1000 CHAR) NOT NULL,
      BODY CLOB NOT NULL, STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
      CREATED_ON DATE DEFAULT SYSDATE NOT NULL, SENT_ON DATE,
      ERROR_TEXT VARCHAR2(2000 CHAR), RETRY_COUNT NUMBER DEFAULT 0 NOT NULL,
      CREATED_BY NUMBER, CONSTRAINT PK_EMAIL_QUEUE PRIMARY KEY (EMAIL_ID),
      CONSTRAINT CK_EMAIL_QUEUE_STATUS CHECK (STATUS IN ('PENDING','FAILED','SENT'))
    )~';
  END IF;

  SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_EMAIL_QUEUE_ID';
  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_EMAIL_QUEUE_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME='UQ_EMAIL_SCHED_NOTIFY';
  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UQ_EMAIL_SCHED_NOTIFY ON T_EMAIL_QUEUE
      (CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH')
       THEN EVENT_CODE END,
       CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH')
       THEN REF_ID1 END,
       CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH')
       THEN REF_ID2 END)~';
  END IF;
END;
/

-- Generic queue API. This package replaces the former PKG_INQ queue members.
@@pkg_email.sql
/
SHOW ERRORS PACKAGE PKG_EMAIL
SHOW ERRORS PACKAGE BODY PKG_EMAIL

DECLARE
  N NUMBER;
BEGIN
  SELECT COUNT(*) INTO N FROM USER_OBJECTS
   WHERE OBJECT_NAME='PKG_EMAIL' AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY') AND STATUS='VALID';
  IF N<>2 THEN RAISE_APPLICATION_ERROR(-20801,'PKG_EMAIL compilation failed; inspect USER_ERRORS.'); END IF;
END;
/

UPDATE IAS_NOTIFICATION_MASTER
   SET DELIVERY_MECHANISM='PKG_EMAIL.P_ENQUEUE_EMAIL'
 WHERE NOTIFICATION_CODE IN
       ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH');

UPDATE IAS_NOTIFICATION_MASTER
   SET RELATED_PROCEDURE='EmailNotification.NotifyManagementAuditParaStatus',
       DELIVERY_MECHANISM='EmailConfiguration SMTP'
 WHERE NOTIFICATION_CODE='MGMT_AUDIT_PARA_STATUS';
COMMIT;

PROMPT Deploy the complete updated PKG_INQ.sql, ias_notification_centralization.sql, and PKG_AE.sql next.
SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('T_EMAIL_QUEUE','SEQ_EMAIL_QUEUE_ID','PKG_EMAIL')
 ORDER BY OBJECT_NAME,OBJECT_TYPE;
