/*
IAS generic email queue foundation (Oracle 18c compatible).

This is database deployment phase 1. Run the remaining files in the exact
order documented by management_audit_notification_deployment.md.
*/
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
    FROM USER_TABLES
   WHERE TABLE_NAME='T_EMAIL_QUEUE';

  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE T_EMAIL_QUEUE (
      EMAIL_ID NUMBER NOT NULL,
      EVENT_CODE VARCHAR2(100 CHAR) NOT NULL,
      REF_ID1 NUMBER,
      REF_ID2 NUMBER,
      MAIL_TO VARCHAR2(2000 CHAR) NOT NULL,
      MAIL_CC VARCHAR2(2000 CHAR),
      SUBJECT VARCHAR2(1000 CHAR) NOT NULL,
      BODY CLOB NOT NULL,
      STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
      CREATED_ON DATE DEFAULT SYSDATE NOT NULL,
      SENT_ON DATE,
      ERROR_TEXT VARCHAR2(2000 CHAR),
      RETRY_COUNT NUMBER DEFAULT 0 NOT NULL,
      CREATED_BY NUMBER,
      CONSTRAINT PK_EMAIL_QUEUE PRIMARY KEY (EMAIL_ID),
      CONSTRAINT CK_EMAIL_QUEUE_STATUS CHECK (STATUS IN ('PENDING','FAILED','SENT'))
    )~';
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME='SEQ_EMAIL_QUEUE_ID';

  IF V_COUNT=0 THEN
    EXECUTE IMMEDIATE
      'CREATE SEQUENCE SEQ_EMAIL_QUEUE_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM USER_INDEXES
   WHERE INDEX_NAME='UQ_EMAIL_SCHED_NOTIFY';

  IF V_COUNT>0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX UQ_EMAIL_SCHED_NOTIFY';
  END IF;

  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UQ_EMAIL_SCHED_NOTIFY ON T_EMAIL_QUEUE
    (CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH')
          THEN EVENT_CODE END,
     CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH')
          THEN REF_ID1 END,
     CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH')
          THEN NVL(REF_ID2,-1) END)~';
END;
/

DECLARE
  V_OBJECTS NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_OBJECTS
    FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('T_EMAIL_QUEUE','SEQ_EMAIL_QUEUE_ID','UQ_EMAIL_SCHED_NOTIFY')
     AND STATUS='VALID';

  IF V_OBJECTS<>3 THEN
    RAISE_APPLICATION_ERROR(-20801,
      'Generic email queue foundation validation failed.');
  END IF;
END;
/

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('T_EMAIL_QUEUE','SEQ_EMAIL_QUEUE_ID','UQ_EMAIL_SCHED_NOTIFY')
 ORDER BY OBJECT_NAME,OBJECT_TYPE;
