-- Rollback for standalone AIS Email Management Module only.
-- Existing AIS email objects are not touched.

DROP PACKAGE PKG_EMAIL;
DROP TABLE EM_EMAIL_LOG CASCADE CONSTRAINTS PURGE;
ALTER TABLE EM_EMAIL_EVENT DROP CONSTRAINT FK_EM_EVENT_ACTIVE_TEMPLATE;
DROP TABLE EM_EMAIL_ATTACHMENT_DEF CASCADE CONSTRAINTS PURGE;
DROP TABLE EM_EMAIL_PLACEHOLDER CASCADE CONSTRAINTS PURGE;
DROP TABLE EM_EMAIL_RECIPIENT_RULE CASCADE CONSTRAINTS PURGE;
DROP TABLE EM_EMAIL_TEMPLATE CASCADE CONSTRAINTS PURGE;
DROP TABLE EM_EMAIL_EVENT CASCADE CONSTRAINTS PURGE;

-- Restore the pre-module PKG_EMAIL implementation shipped with AIS.
@@pkg_email.sql
