-- IAS database-backed SMTP configuration. Run as the IAS application schema owner.

CREATE TABLE T_AU_EMAIL_CONFIGURATION
(
    CONFIG_ID           NUMBER(19)       NOT NULL,
    SMTP_HOST           VARCHAR2(255)    NOT NULL,
    SMTP_PORT           NUMBER(5)        NOT NULL,
    FROM_EMAIL          VARCHAR2(320)    NOT NULL,
    SMTP_USERNAME       VARCHAR2(320),
    ENCRYPTED_PASSWORD  RAW(2000),
    ENABLE_SSL          CHAR(1)          DEFAULT 'Y' NOT NULL,
    IS_ACTIVE           CHAR(1)          DEFAULT 'N' NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_ON          TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_AU_EMAIL_CONFIGURATION PRIMARY KEY (CONFIG_ID),
    CONSTRAINT CK_T_AU_EMAIL_CONFIG_PORT CHECK (SMTP_PORT BETWEEN 1 AND 65535),
    CONSTRAINT CK_T_AU_EMAIL_CONFIG_SSL CHECK (ENABLE_SSL IN ('Y','N')),
    CONSTRAINT CK_T_AU_EMAIL_CONFIG_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE SEQUENCE SEQ_T_AU_EMAIL_CONFIGURATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Oracle permits multiple NULLs but only one indexed value of 1, enforcing one active row.
CREATE UNIQUE INDEX UX_T_AU_EMAIL_CONFIG_ACTIVE
    ON T_AU_EMAIL_CONFIGURATION (CASE WHEN IS_ACTIVE = 'Y' THEN 1 ELSE NULL END);

CREATE TABLE T_AU_EMAIL_CONFIGURATION_HIST
(
    HISTORY_ID              NUMBER(19)      NOT NULL,
    CONFIG_ID               NUMBER(19)      NOT NULL,
    CHANGED_FIELDS          VARCHAR2(2000)  NOT NULL,
    CHANGED_BY              VARCHAR2(100),
    CHANGED_ON              TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CLIENT_IP               VARCHAR2(64),
    PREVIOUS_ACTIVE_STATUS  CHAR(1),
    NEW_ACTIVE_STATUS       CHAR(1),
    CONSTRAINT PK_T_AU_EMAIL_CONFIG_HIST PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_T_AU_EMAIL_CONFIG_HIST FOREIGN KEY (CONFIG_ID)
        REFERENCES T_AU_EMAIL_CONFIGURATION (CONFIG_ID),
    CONSTRAINT CK_T_AU_EMAIL_HIST_PREV CHECK (PREVIOUS_ACTIVE_STATUS IN ('Y','N') OR PREVIOUS_ACTIVE_STATUS IS NULL),
    CONSTRAINT CK_T_AU_EMAIL_HIST_NEW CHECK (NEW_ACTIVE_STATUS IN ('Y','N') OR NEW_ACTIVE_STATUS IS NULL)
);

CREATE SEQUENCE SEQ_T_AU_EMAIL_CONFIG_HIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IX_T_AU_EMAIL_CONFIG_HIST_01
    ON T_AU_EMAIL_CONFIGURATION_HIST (CONFIG_ID, CHANGED_ON);

CREATE OR REPLACE PACKAGE PKG_EMAIL_CONFIGURATION AS
    TYPE T_CURSOR IS REF CURSOR;

    PROCEDURE GET_ACTIVE_CONFIGURATION(P_CURSOR OUT T_CURSOR);
    PROCEDURE GET_CONFIGURATION(P_CONFIG_ID IN NUMBER, P_CURSOR OUT T_CURSOR);

    PROCEDURE UPSERT_CONFIGURATION(
        P_CONFIG_ID          IN OUT NUMBER,
        P_SMTP_HOST          IN VARCHAR2,
        P_SMTP_PORT          IN NUMBER,
        P_FROM_EMAIL         IN VARCHAR2,
        P_SMTP_USERNAME      IN VARCHAR2,
        P_ENCRYPTED_PASSWORD IN RAW,
        P_ENABLE_SSL         IN CHAR,
        P_IS_ACTIVE          IN CHAR,
        P_UPDATED_BY         IN VARCHAR2,
        P_CLIENT_IP          IN VARCHAR2);

    PROCEDURE ACTIVATE_CONFIGURATION(
        P_CONFIG_ID IN NUMBER, P_CHANGED_BY IN VARCHAR2, P_CLIENT_IP IN VARCHAR2);

    PROCEDURE DEACTIVATE_CONFIGURATION(
        P_CONFIG_ID IN NUMBER, P_CHANGED_BY IN VARCHAR2, P_CLIENT_IP IN VARCHAR2);

    PROCEDURE RECORD_CONFIGURATION_CHANGE(
        P_CONFIG_ID IN NUMBER,
        P_CHANGED_FIELDS IN VARCHAR2,
        P_CHANGED_BY IN VARCHAR2,
        P_CLIENT_IP IN VARCHAR2,
        P_PREVIOUS_ACTIVE_STATUS IN CHAR,
        P_NEW_ACTIVE_STATUS IN CHAR);
END PKG_EMAIL_CONFIGURATION;
/

CREATE OR REPLACE PACKAGE BODY PKG_EMAIL_CONFIGURATION AS
    PROCEDURE RECORD_CONFIGURATION_CHANGE(
        P_CONFIG_ID IN NUMBER,
        P_CHANGED_FIELDS IN VARCHAR2,
        P_CHANGED_BY IN VARCHAR2,
        P_CLIENT_IP IN VARCHAR2,
        P_PREVIOUS_ACTIVE_STATUS IN CHAR,
        P_NEW_ACTIVE_STATUS IN CHAR) IS
    BEGIN
        INSERT INTO T_AU_EMAIL_CONFIGURATION_HIST
            (HISTORY_ID, CONFIG_ID, CHANGED_FIELDS, CHANGED_BY, CHANGED_ON,
             CLIENT_IP, PREVIOUS_ACTIVE_STATUS, NEW_ACTIVE_STATUS)
        VALUES
            (SEQ_T_AU_EMAIL_CONFIG_HIST.NEXTVAL, P_CONFIG_ID,
             SUBSTR(P_CHANGED_FIELDS, 1, 2000), P_CHANGED_BY, SYSTIMESTAMP,
             SUBSTR(P_CLIENT_IP, 1, 64), P_PREVIOUS_ACTIVE_STATUS, P_NEW_ACTIVE_STATUS);
    END;

    PROCEDURE GET_ACTIVE_CONFIGURATION(P_CURSOR OUT T_CURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT CONFIG_ID, SMTP_HOST, SMTP_PORT, FROM_EMAIL, SMTP_USERNAME,
                   ENCRYPTED_PASSWORD, ENABLE_SSL, IS_ACTIVE, UPDATED_BY, UPDATED_ON
              FROM T_AU_EMAIL_CONFIGURATION
             WHERE IS_ACTIVE = 'Y';
    END;

    PROCEDURE GET_CONFIGURATION(P_CONFIG_ID IN NUMBER, P_CURSOR OUT T_CURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT CONFIG_ID, SMTP_HOST, SMTP_PORT, FROM_EMAIL, SMTP_USERNAME,
                   ENCRYPTED_PASSWORD, ENABLE_SSL, IS_ACTIVE, UPDATED_BY, UPDATED_ON
              FROM T_AU_EMAIL_CONFIGURATION
             WHERE CONFIG_ID = P_CONFIG_ID;
    END;

    PROCEDURE ACTIVATE_CONFIGURATION(
        P_CONFIG_ID IN NUMBER, P_CHANGED_BY IN VARCHAR2, P_CLIENT_IP IN VARCHAR2) IS
        L_PREVIOUS CHAR(1);
    BEGIN
        SELECT IS_ACTIVE INTO L_PREVIOUS
          FROM T_AU_EMAIL_CONFIGURATION
         WHERE CONFIG_ID = P_CONFIG_ID
         FOR UPDATE;

        FOR R IN (SELECT CONFIG_ID FROM T_AU_EMAIL_CONFIGURATION
                   WHERE IS_ACTIVE = 'Y' AND CONFIG_ID <> P_CONFIG_ID FOR UPDATE) LOOP
            UPDATE T_AU_EMAIL_CONFIGURATION
               SET IS_ACTIVE = 'N', UPDATED_BY = P_CHANGED_BY, UPDATED_ON = SYSTIMESTAMP
             WHERE CONFIG_ID = R.CONFIG_ID;
            RECORD_CONFIGURATION_CHANGE(R.CONFIG_ID, 'IS_ACTIVE', P_CHANGED_BY,
                P_CLIENT_IP, 'Y', 'N');
        END LOOP;

        UPDATE T_AU_EMAIL_CONFIGURATION
           SET IS_ACTIVE = 'Y', UPDATED_BY = P_CHANGED_BY, UPDATED_ON = SYSTIMESTAMP
         WHERE CONFIG_ID = P_CONFIG_ID;
        IF L_PREVIOUS <> 'Y' THEN
            RECORD_CONFIGURATION_CHANGE(P_CONFIG_ID, 'IS_ACTIVE', P_CHANGED_BY,
                P_CLIENT_IP, L_PREVIOUS, 'Y');
        END IF;
        COMMIT;
    END;

    PROCEDURE DEACTIVATE_CONFIGURATION(
        P_CONFIG_ID IN NUMBER, P_CHANGED_BY IN VARCHAR2, P_CLIENT_IP IN VARCHAR2) IS
        L_PREVIOUS CHAR(1);
    BEGIN
        SELECT IS_ACTIVE INTO L_PREVIOUS
          FROM T_AU_EMAIL_CONFIGURATION
         WHERE CONFIG_ID = P_CONFIG_ID
         FOR UPDATE;
        UPDATE T_AU_EMAIL_CONFIGURATION
           SET IS_ACTIVE = 'N', UPDATED_BY = P_CHANGED_BY, UPDATED_ON = SYSTIMESTAMP
         WHERE CONFIG_ID = P_CONFIG_ID;
        IF L_PREVIOUS <> 'N' THEN
            RECORD_CONFIGURATION_CHANGE(P_CONFIG_ID, 'IS_ACTIVE', P_CHANGED_BY,
                P_CLIENT_IP, L_PREVIOUS, 'N');
        END IF;
        COMMIT;
    END;

    PROCEDURE UPSERT_CONFIGURATION(
        P_CONFIG_ID          IN OUT NUMBER,
        P_SMTP_HOST          IN VARCHAR2,
        P_SMTP_PORT          IN NUMBER,
        P_FROM_EMAIL         IN VARCHAR2,
        P_SMTP_USERNAME      IN VARCHAR2,
        P_ENCRYPTED_PASSWORD IN RAW,
        P_ENABLE_SSL         IN CHAR,
        P_IS_ACTIVE          IN CHAR,
        P_UPDATED_BY         IN VARCHAR2,
        P_CLIENT_IP          IN VARCHAR2) IS
        L_OLD T_AU_EMAIL_CONFIGURATION%ROWTYPE;
        L_FIELDS VARCHAR2(2000);
        L_IS_NEW BOOLEAN := FALSE;
    BEGIN
        IF P_CONFIG_ID IS NULL OR P_CONFIG_ID = 0 THEN
            P_CONFIG_ID := SEQ_T_AU_EMAIL_CONFIGURATION.NEXTVAL;
            L_IS_NEW := TRUE;
            INSERT INTO T_AU_EMAIL_CONFIGURATION
                (CONFIG_ID, SMTP_HOST, SMTP_PORT, FROM_EMAIL, SMTP_USERNAME,
                 ENCRYPTED_PASSWORD, ENABLE_SSL, IS_ACTIVE, UPDATED_BY, UPDATED_ON)
            VALUES
                (P_CONFIG_ID, TRIM(P_SMTP_HOST), P_SMTP_PORT, TRIM(P_FROM_EMAIL),
                 TRIM(P_SMTP_USERNAME), P_ENCRYPTED_PASSWORD,
                 NVL(P_ENABLE_SSL, 'Y'), 'N', P_UPDATED_BY, SYSTIMESTAMP);
            L_FIELDS := 'CONFIGURATION_CREATED';
            RECORD_CONFIGURATION_CHANGE(P_CONFIG_ID, L_FIELDS, P_UPDATED_BY,
                P_CLIENT_IP, NULL, 'N');
        ELSE
            SELECT * INTO L_OLD FROM T_AU_EMAIL_CONFIGURATION
             WHERE CONFIG_ID = P_CONFIG_ID FOR UPDATE;

            IF NVL(L_OLD.SMTP_HOST, ' ') <> NVL(TRIM(P_SMTP_HOST), ' ') THEN L_FIELDS := L_FIELDS || ',SMTP_HOST'; END IF;
            IF L_OLD.SMTP_PORT <> P_SMTP_PORT THEN L_FIELDS := L_FIELDS || ',SMTP_PORT'; END IF;
            IF NVL(L_OLD.FROM_EMAIL, ' ') <> NVL(TRIM(P_FROM_EMAIL), ' ') THEN L_FIELDS := L_FIELDS || ',FROM_EMAIL'; END IF;
            IF NVL(L_OLD.SMTP_USERNAME, ' ') <> NVL(TRIM(P_SMTP_USERNAME), ' ') THEN L_FIELDS := L_FIELDS || ',SMTP_USERNAME'; END IF;
            IF P_ENCRYPTED_PASSWORD IS NOT NULL THEN L_FIELDS := L_FIELDS || ',ENCRYPTED_PASSWORD'; END IF;
            IF L_OLD.ENABLE_SSL <> NVL(P_ENABLE_SSL, 'Y') THEN L_FIELDS := L_FIELDS || ',ENABLE_SSL'; END IF;

            UPDATE T_AU_EMAIL_CONFIGURATION
               SET SMTP_HOST = TRIM(P_SMTP_HOST), SMTP_PORT = P_SMTP_PORT,
                   FROM_EMAIL = TRIM(P_FROM_EMAIL), SMTP_USERNAME = TRIM(P_SMTP_USERNAME),
                   ENCRYPTED_PASSWORD = NVL(P_ENCRYPTED_PASSWORD, ENCRYPTED_PASSWORD),
                   ENABLE_SSL = NVL(P_ENABLE_SSL, 'Y'), UPDATED_BY = P_UPDATED_BY,
                   UPDATED_ON = SYSTIMESTAMP
             WHERE CONFIG_ID = P_CONFIG_ID;

            IF L_FIELDS IS NOT NULL THEN
                RECORD_CONFIGURATION_CHANGE(P_CONFIG_ID, LTRIM(L_FIELDS, ','),
                    P_UPDATED_BY, P_CLIENT_IP, L_OLD.IS_ACTIVE, L_OLD.IS_ACTIVE);
            END IF;
        END IF;

        IF NVL(P_IS_ACTIVE, 'N') = 'Y' THEN
            ACTIVATE_CONFIGURATION(P_CONFIG_ID, P_UPDATED_BY, P_CLIENT_IP);
        ELSIF NOT L_IS_NEW THEN
            SELECT * INTO L_OLD FROM T_AU_EMAIL_CONFIGURATION WHERE CONFIG_ID = P_CONFIG_ID;
            IF L_OLD.IS_ACTIVE = 'Y' THEN
                DEACTIVATE_CONFIGURATION(P_CONFIG_ID, P_UPDATED_BY, P_CLIENT_IP);
            ELSE
                COMMIT;
            END IF;
        ELSE
            COMMIT;
        END IF;
    END;
END PKG_EMAIL_CONFIGURATION;
/

COMMENT ON COLUMN T_AU_EMAIL_CONFIGURATION.ENCRYPTED_PASSWORD IS
    'AES-256-GCM ciphertext payload. Encryption key is held outside Oracle and source control.';
