/*
  IAS CENTRAL NOTIFICATION MANAGEMENT
  ===================================
  Target: Oracle 19c+ / current IAS schema

  Reviewed notification inventory and current caller/source
  ---------------------------------------------------------
  1  AUDIT_TEAM_ASSIGNED        ApiCallsController.AddEngagementPlan / PKG_PG.P_ADDAUDITENGPLAN
  2  AUDIT_TEAM_JOINED          DBConnection.AddJoiningReport / PKG_AR.P_ADDJOININGREPORT
  3  OBS_SUBMITTED_AUDITEE      ApiCallsController.submit_observation_to_auditee / PKG_AR observation workflow
  4  PARA_STATUS_UPDATED        DBConnection.SubmitPostAuditComplianceReview / PKG_AE.P_SUBMITPOSTAUDITCOMPLIANCE_REVIEW
  5  FINAL_REPORT_ISSUED        FieldAuditReportController.Finalize / PKG_FRPT final-report process
  6  INQUIRY_ASSIGNED_UNIT      ApiCallsController.AddHeadReview / PKG_INQ.ADD_HEAD_REVIEW
  7  PASSWORD_RESET_SUCCESS     DBConnection.ResetUserPassword / PKG_AD.RESET_USER_PASSWORD
  8  AUDIT_SAMPLE_ISSUE         DBConnection.CreateSampleDataAfterEngagementApproval / PKG_SM.P_ADD_SAMPLE_DATA
  9  AUDIT_EXCEPTION_ISSUE      DBConnection.CreateExceptionDataAfterEngagementApproval / PKG_SM.P_ADD_EXCEPTION_DATA
 10  AUDIT_CRITERIA_SUBMITTED   DBConnection.SubmitAuditCriteriaForApproval / PKG_PG.P_SUBMITAUDITCRITERIAFORAPPROVAL (currently dormant)
 11  AJAX_APPLICATION_ERROR     AjaxErrorNotificationMiddleware (application diagnostic)

  Design decisions
  ----------------
  * IAS_NOTIFICATION_MASTER is the runtime master requested here.  It records the
    business caller, related procedure, authoritative data source, templates,
    delivery mechanism and status.  It does not replace workflow tables.
  * Recipient values already returned by an existing business procedure/view are
    passed into the matching notification procedure.  Notification procedures do
    not repeat the business procedure's joins.
  * PARA_STATUS_UPDATED reads V_GET_AIS_POST_COMPLIANCE once.  The workflow should
    call it with vr1.COMID after its existing update; it must remove the duplicate
    ET/AD/MT email joins from P_SUBMITPOSTAUDITCOMPLIANCE_REVIEW.
  * All procedures use one HTML renderer and the existing PKG_INQ.P_ENQUEUE_EMAIL
    queue.  The current IAS queue worker remains the SMTP sender.  No COMMIT is
    issued here, so notification enqueue participates in the caller transaction.
  * FINAL_REPORT_ISSUED queues the HTML message only.  The existing application
    remains responsible for attaching the generated PDF; no attachment workflow is
    changed by this script.
*/

SET DEFINE OFF;

--------------------------------------------------------------------------------
-- 1. Notification master table
--------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE IAS_NOTIFICATION_MASTER
    (
      NOTIFICATION_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      NOTIFICATION_CODE     VARCHAR2(100 CHAR) NOT NULL,
      NOTIFICATION_NAME     VARCHAR2(200 CHAR) NOT NULL,
      MODULE_NAME           VARCHAR2(100 CHAR) NOT NULL,
      CALLING_PROCESS       VARCHAR2(300 CHAR) NOT NULL,
      RELATED_PROCEDURE     VARCHAR2(300 CHAR),
      DATA_SOURCE_NAME      VARCHAR2(300 CHAR),
      SUBJECT_TEMPLATE      VARCHAR2(1000 CHAR) NOT NULL,
      TITLE_TEMPLATE        VARCHAR2(500 CHAR) NOT NULL,
      SUMMARY_TEMPLATE      CLOB NOT NULL,
      NOTIFICATION_TYPE     VARCHAR2(30 CHAR) DEFAULT 'TRANSACTIONAL' NOT NULL,
      DELIVERY_MECHANISM    VARCHAR2(100 CHAR) DEFAULT 'PKG_INQ.P_ENQUEUE_EMAIL' NOT NULL,
      CONTENT_TYPE          VARCHAR2(100 CHAR) DEFAULT 'text/html; charset=utf-8' NOT NULL,
      PRIORITY_CODE         VARCHAR2(10 CHAR) DEFAULT 'NORMAL' NOT NULL,
      IS_ACTIVE             CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
      REQUIRES_ATTACHMENT   CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
      DESCRIPTION           VARCHAR2(1000 CHAR),
      CREATED_BY            VARCHAR2(100 CHAR) DEFAULT USER NOT NULL,
      CREATED_ON            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_BY            VARCHAR2(100 CHAR),
      UPDATED_ON            TIMESTAMP,
      CONSTRAINT PK_IAS_NOTIFICATION_MASTER PRIMARY KEY (NOTIFICATION_ID),
      CONSTRAINT UQ_IAS_NOTIFICATION_CODE UNIQUE (NOTIFICATION_CODE),
      CONSTRAINT CK_IAS_NOTIFICATION_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
      CONSTRAINT CK_IAS_NOTIFICATION_ATTACH CHECK (REQUIRES_ATTACHMENT IN ('Y','N')),
      CONSTRAINT CK_IAS_NOTIFICATION_TYPE CHECK
        (NOTIFICATION_TYPE IN ('TRANSACTIONAL','SECURITY','TECHNICAL','WORKFLOW')),
      CONSTRAINT CK_IAS_NOTIFICATION_PRIORITY CHECK
        (PRIORITY_CODE IN ('LOW','NORMAL','HIGH'))
    )~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE IAS_NOTIFICATION_MASTER IS
  'Central runtime registry for every IAS email notification and its authoritative source/process.';

CREATE OR REPLACE VIEW V_IAS_NOTIFICATION_MASTER AS
SELECT NOTIFICATION_ID, NOTIFICATION_CODE, NOTIFICATION_NAME, MODULE_NAME,
       CALLING_PROCESS, RELATED_PROCEDURE, DATA_SOURCE_NAME, SUBJECT_TEMPLATE,
       TITLE_TEMPLATE, SUMMARY_TEMPLATE, NOTIFICATION_TYPE, DELIVERY_MECHANISM,
       CONTENT_TYPE, PRIORITY_CODE, IS_ACTIVE, REQUIRES_ATTACHMENT, DESCRIPTION
  FROM IAS_NOTIFICATION_MASTER;

/*
  The reviewed V_GET_AIS_POST_COMPLIANCE exposes the compliance/entity business
  data but, in the checked-in package source, does not expose TO_EMAIL/CC_EMAIL.
  This adapter is therefore the single centralized source for that notification.
  If the deployed V_GET_AIS_POST_COMPLIANCE already exposes these addresses,
  replace the three entity joins below with those view columns before deployment.
*/
CREATE OR REPLACE VIEW V_IAS_POST_COMPLIANCE_NOTIFY AS
SELECT C.COM_ID,
       C.PARA_NO,
       C.GIST_OF_PARAS,
       C.AUDIT_PERIOD,
       C.RSK AS RISK,
       C.AUDITBY_ID,
       C.ENTITY_ID,
       ET.EMAIL_ADDRESS AS TO_EMAIL,
       RTRIM(AD.EMAIL_ADDRESS||';'||MT.EMAIL_ADDRESS,';') AS CC_EMAIL
  FROM V_GET_AIS_POST_COMPLIANCE C
  JOIN T_AUDITEE_ENTITIES_MAPING M ON M.ENTITY_ID=C.ENTITY_ID
  JOIN T_AUDITEE_ENTITIES ET ON ET.ENTITY_ID=M.ENTITY_ID
  JOIN T_AUDITEE_ENTITIES MT ON MT.ENTITY_ID=M.PARENT_ID
  JOIN T_AUDITEE_ENTITIES AD ON AD.ENTITY_ID=ET.AUDITBY_ID;

--------------------------------------------------------------------------------
-- 2. Initial notification records (repeatable seed; preserves administrator status)
--------------------------------------------------------------------------------
MERGE INTO IAS_NOTIFICATION_MASTER D
USING (
  SELECT 'AUDIT_TEAM_ASSIGNED' CODE, 'Audit Task Assigned' NAME, 'Planning' MODL,
    'ApiCallsController.AddEngagementPlan' CALLER, 'PKG_PG.P_ADDAUDITENGPLAN' PROC,
    'Existing AddAuditEngagementPlan result + audit-team data source' SRC,
    'IAS Notification: Audit Task Assigned - {REFERENCE}' SUBJ, 'Audit Task Assigned' TITLE,
    'An audit task has been allocated to the assigned team. Please review the engagement details and proceed in line with the approved plan.' SUMMARY,
    'WORKFLOW' NT, 'N' ATT, 'Active application notification.' DESCR FROM DUAL UNION ALL
  SELECT 'AUDIT_TEAM_JOINED','Audit Team Joined','Audit','DBConnection.AddJoiningReport',
    'PKG_AR.P_ADDJOININGREPORT','PKG_AR.P_ADDJOININGREPORT output cursor',
    'IAS Notification: Audit Team has Joined for {REFERENCE}','Audit Team has Joined',
    'The audit team has officially joined. Please coordinate with the team and provide requested information.',
    'WORKFLOW','N','Use the procedure cursor; do not repeat its recipient/team lookups.' FROM DUAL UNION ALL
  SELECT 'OBS_SUBMITTED_AUDITEE','Observation Submitted to Auditee','Audit Execution',
    'ApiCallsController.submit_observation_to_auditee','PKG_AR observation submission process',
    'Existing managed-observation data source','IAS Notification: Observation Submitted to Auditee - {REFERENCE}',
    'Observation Submitted to Auditee','An audit observation has been submitted to the auditee for review and response.',
    'WORKFLOW','N','Active application notification.' FROM DUAL UNION ALL
  SELECT 'PARA_STATUS_UPDATED','Audit Para Status Updated','Compliance',
    'DBConnection.SubmitPostAuditComplianceReview','PKG_AE.P_SUBMITPOSTAUDITCOMPLIANCE_REVIEW',
    'V_GET_AIS_POST_COMPLIANCE','IAS Notification: Para No. {REFERENCE} is marked {STATUS}',
    'Audit Para Status Updated','Para No. {REFERENCE} has been marked as {STATUS}.',
    'WORKFLOW','N','V_GET_AIS_POST_COMPLIANCE is authoritative; recipient resolution is centralized below.' FROM DUAL UNION ALL
  SELECT 'MGMT_AUDIT_PARA_STATUS','Management Audit Para Status','Compliance',
    'PKG_AE.P_SUBMITPOSTAUDITCOMPLIANCE_REVIEW','PKG_IAS_NOTIFICATION.SEND_MGMT_AUDIT_PARA_STATUS',
    'V_IAS_POST_COMPLIANCE_NOTIFY + AIS_T_AU_POST_COMPLIANCE_HISTORY',
    'IAS Notification: Audit Para No. {REFERENCE} {STATUS}',
    'Audit Para No. {REFERENCE} {STATUS}',' ',
    'WORKFLOW','N','Management Audit only (AUDITED_BY 112242/112248); queued after the decision commit.' FROM DUAL UNION ALL
  SELECT 'MGMT_AUDIT_WEEKLY_PARA_STATUS','Weekly Management Audit Para Decisions','Compliance',
    'JOB_MGMT_AUDIT_WEEKLY_NOTIFY','PKG_IAS_NOTIFICATION.SEND_MGMT_AUDIT_WEEKLY',
    'Decision history + explicit DIV_OFFICE/B_GROUP entity mappings',
    'IAS Notification: Weekly Management Audit Para Decisions ({REFERENCE})',
    'Weekly Management Audit Para Decisions','Reporting period: {REFERENCE}',
    'WORKFLOW','N','Previous Monday-Sunday digest for concerned Group and Divisional Heads.' FROM DUAL UNION ALL
  SELECT 'FINAL_REPORT_ISSUED','Final Audit Report Issued','Reporting',
    'FieldAuditReportController finalization','PKG_FRPT final-report process',
    'Existing field-audit report overview data source','IAS Notification: Final Audit Report Issued - {REFERENCE}',
    'Final Audit Report Issued','The final audit report has been issued. The generated PDF is attached by the existing application process.',
    'WORKFLOW','Y','Application retains PDF attachment responsibility.' FROM DUAL UNION ALL
  SELECT 'INQUIRY_ASSIGNED_UNIT','Inquiry Assigned to I&I Unit','IID',
    'ApiCallsController.AddHeadReview','PKG_INQ.ADD_HEAD_REVIEW',
    'Existing complaint/head-review/unit data sources','IAS Notification: Inquiry Assigned to I&I Unit - {REFERENCE}',
    'Inquiry Assigned to I&I Unit','A complaint inquiry has been approved and allocated to the relevant I&I Unit.',
    'WORKFLOW','N','Active application notification.' FROM DUAL UNION ALL
  SELECT 'PASSWORD_RESET_SUCCESS','Password Reset Successful','Authentication',
    'DBConnection.ResetUserPassword','PKG_AD.RESET_USER_PASSWORD','V_SERVICE_EMPLOYEEINFO + RESET_USER_PASSWORD output cursor',
    'IAS~ Password Reset Successful','Password Reset Successful',
    'Your password has been successfully reset. Change the temporary password immediately after logging in.',
    'SECURITY','N','Temporary password must only be supplied by the reset process; it is never queried from storage.' FROM DUAL UNION ALL
  SELECT 'AUDIT_SAMPLE_ISSUE','Audit Sample Creation Issue','Sampling',
    'DBConnection.CreateSampleDataAfterEngagementApproval','PKG_SM.P_ADD_SAMPLE_DATA','PKG_SM.P_ADD_SAMPLE_DATA output cursor',
    'IAS~Notification: Issue in Audit Sample for Engagement ID: {REFERENCE}','Issue in Audit Sample Creation',
    'An issue was identified while creating the audit sample. Please review and resolve it.',
    'TECHNICAL','N','Use the existing procedure cursor recipients.' FROM DUAL UNION ALL
  SELECT 'AUDIT_EXCEPTION_ISSUE','Audit Exception Creation Issue','Exception Monitoring',
    'DBConnection.CreateExceptionDataAfterEngagementApproval','PKG_SM.P_ADD_EXCEPTION_DATA','PKG_SM.P_ADD_EXCEPTION_DATA output cursor',
    'IAS~Notification: Issue in Audit Exception for Engagement ID: {REFERENCE}','Issue in Audit Exception Creation',
    'An issue was identified while creating the audit exception report. Please review and resolve it.',
    'TECHNICAL','N','Use the existing procedure cursor recipients.' FROM DUAL UNION ALL
  SELECT 'AUDIT_CRITERIA_SUBMITTED','Audit Criteria Submitted','Planning',
    'DBConnection.SubmitAuditCriteriaForApproval','PKG_PG.P_SUBMITAUDITCRITERIAFORAPPROVAL','Existing planning procedure/data source',
    'IAS~ Notification regarding submission of Audit Criteria','Audit Criteria Submitted',
    'Audit criteria have been submitted for review.','WORKFLOW','N','Dormant notification retained as inactive in seed.' FROM DUAL UNION ALL
  SELECT 'AJAX_APPLICATION_ERROR','AJAX Application Error','Application',
    'AjaxErrorNotificationMiddleware','Application middleware','Application error context + configured recipient',
    'IAS AJAX Error {STATUS} ({REFERENCE})','AJAX Application Error',
    'An AJAX application error was detected.','TECHNICAL','N','Application diagnostic notification.' FROM DUAL
) S
ON (D.NOTIFICATION_CODE = S.CODE)
WHEN MATCHED THEN UPDATE SET
  D.NOTIFICATION_NAME=S.NAME, D.MODULE_NAME=S.MODL, D.CALLING_PROCESS=S.CALLER,
  D.RELATED_PROCEDURE=S.PROC, D.DATA_SOURCE_NAME=S.SRC,
  D.SUBJECT_TEMPLATE=S.SUBJ, D.TITLE_TEMPLATE=S.TITLE,
  D.SUMMARY_TEMPLATE=TO_CLOB(S.SUMMARY), D.NOTIFICATION_TYPE=S.NT,
  D.REQUIRES_ATTACHMENT=S.ATT, D.DESCRIPTION=S.DESCR,
  D.UPDATED_BY=USER, D.UPDATED_ON=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT
  (NOTIFICATION_CODE,NOTIFICATION_NAME,MODULE_NAME,CALLING_PROCESS,RELATED_PROCEDURE,
   DATA_SOURCE_NAME,SUBJECT_TEMPLATE,TITLE_TEMPLATE,SUMMARY_TEMPLATE,
   NOTIFICATION_TYPE,REQUIRES_ATTACHMENT,IS_ACTIVE,DESCRIPTION)
VALUES
  (S.CODE,S.NAME,S.MODL,S.CALLER,S.PROC,S.SRC,S.SUBJ,S.TITLE,TO_CLOB(S.SUMMARY),
   S.NT,S.ATT,CASE WHEN S.CODE='AUDIT_CRITERIA_SUBMITTED' THEN 'N' ELSE 'Y' END,S.DESCR);

--------------------------------------------------------------------------------
-- 3. Central notification package. Every public SEND_* procedure is one
--    notification entry point and calls the existing IAS email queue mechanism.
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_IAS_NOTIFICATION AS
  PROCEDURE SEND_AUDIT_TEAM_ASSIGNED(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_REFERENCE VARCHAR2,P_ENTITY VARCHAR2,P_PERIOD VARCHAR2,P_TEAM VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_AUDIT_TEAM_JOINED(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_ENTITY VARCHAR2,P_TEAM_LEAD VARCHAR2,P_TEAM_MEMBERS VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_OBS_SUBMITTED_AUDITEE(P_ENG_ID NUMBER,P_OBS_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_REFERENCE VARCHAR2,P_ENTITY VARCHAR2,P_PERIOD VARCHAR2,P_HEADING VARCHAR2,P_SUMMARY CLOB,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_PARA_STATUS_UPDATED(P_COM_ID NUMBER,P_STATUS VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_MGMT_AUDIT_PARA_STATUS(P_COM_ID NUMBER,P_DECISION_HIST_ID NUMBER,
    P_STATUS VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_MGMT_AUDIT_WEEKLY(P_FROM_DATE DATE DEFAULT NULL,P_TO_DATE DATE DEFAULT NULL);
  PROCEDURE SEND_FINAL_REPORT_ISSUED(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_REFERENCE VARCHAR2,P_ENTITY VARCHAR2,P_PERIOD VARCHAR2,P_VERSION VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_INQUIRY_ASSIGNED_UNIT(P_COMPLAINT_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_REFERENCE VARCHAR2,P_NATURE VARCHAR2,P_UNIT VARCHAR2,P_DUE_DATE VARCHAR2,P_DIRECTIONS CLOB,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_PASSWORD_RESET_SUCCESS(P_PPNO NUMBER,P_TEMP_PASSWORD VARCHAR2,P_MAIL_CC VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_AUDIT_SAMPLE_ISSUE(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_AUDIT_EXCEPTION_ISSUE(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_AUDIT_CRITERIA_SUBMITTED(P_ENTITY_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_MESSAGE CLOB,O_EMAIL_ID OUT NUMBER);
  PROCEDURE SEND_AJAX_APPLICATION_ERROR(P_REFERENCE VARCHAR2,P_STATUS NUMBER,P_ENDPOINT VARCHAR2,
    P_ACTION VARCHAR2,P_USER_LABEL VARCHAR2,P_DETAILS CLOB,P_MAIL_TO VARCHAR2,O_EMAIL_ID OUT NUMBER);
END PKG_IAS_NOTIFICATION;
/

CREATE OR REPLACE PACKAGE BODY PKG_IAS_NOTIFICATION AS
  C_HEADER CONSTANT VARCHAR2(100) := 'Internal Audit System (IAS)';
  C_FOOTER CONSTANT VARCHAR2(500) := 'This is a system-generated notification from Internal Audit System (IAS). Please do not reply unless required under official process.';

  FUNCTION ESC(P_VALUE VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NVL(P_VALUE,''),'&','&amp;'),'<','&lt;'),'>','&gt;'),'"','&quot;'),'''','&#39;');
  END;

  FUNCTION ROW_HTML(P_LABEL VARCHAR2,P_VALUE VARCHAR2) RETURN CLOB IS
  BEGIN
    IF TRIM(P_VALUE) IS NULL THEN RETURN EMPTY_CLOB(); END IF;
    RETURN TO_CLOB('<tr><td style="padding:12px 14px;border-bottom:1px solid #d9e2ec;font-size:13px;font-weight:bold;color:#102a43;vertical-align:top">')||
      ESC(P_LABEL)||'</td><td style="padding:12px 14px;border-bottom:1px solid #d9e2ec;font-size:13px;color:#334e68;vertical-align:top">'||
      REPLACE(ESC(P_VALUE),CHR(10),'<br />')||'</td></tr>';
  END;

  FUNCTION STANDARD_HTML(P_TITLE VARCHAR2,P_SUMMARY CLOB,P_ROWS CLOB) RETURN CLOB IS
  BEGIN
    RETURN TO_CLOB('<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#1f2933">')||
      '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f6f8;padding:24px 0"><tr><td align="center"><table role="presentation" width="680" cellspacing="0" cellpadding="0" style="width:680px;max-width:680px;background:#fff;border-collapse:collapse;border:1px solid #d9e2ec">'||
      '<tr><td style="padding:18px 28px;background:#173f5f;color:#fff;font-size:20px;font-weight:bold">'||ESC(C_HEADER)||'</td></tr>'||
      '<tr><td style="padding:28px 28px 16px;font-size:24px;font-weight:bold;color:#102a43">'||ESC(P_TITLE)||'</td></tr>'||
      CASE WHEN TRIM(DBMS_LOB.SUBSTR(P_SUMMARY,32767,1)) IS NOT NULL THEN
        '<tr><td style="padding:0 28px 20px;font-size:15px;line-height:1.7;color:#334e68">'||ESC(DBMS_LOB.SUBSTR(P_SUMMARY,32767,1))||'</td></tr>' END||
      CASE WHEN DBMS_LOB.GETLENGTH(NVL(P_ROWS,EMPTY_CLOB()))>0 THEN '<tr><td style="padding:0 28px 28px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;border:1px solid #d9e2ec">'||P_ROWS||'</table></td></tr>' END||
      '<tr><td style="padding:18px 28px;background:#f8fafc;border-top:1px solid #d9e2ec;font-size:12px;line-height:1.6;color:#52606d">'||ESC(C_FOOTER)||'</td></tr></table></td></tr></table></body></html>';
  END;

  PROCEDURE ENQUEUE(P_CODE VARCHAR2,P_REF1 NUMBER,P_REF2 NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_REFERENCE VARCHAR2,P_STATUS VARCHAR2,P_ROWS CLOB,O_EMAIL_ID OUT NUMBER) IS
    V_M IAS_NOTIFICATION_MASTER%ROWTYPE; V_SUBJECT VARCHAR2(1000); V_TITLE VARCHAR2(500); V_SUMMARY CLOB; V_BODY CLOB;
  BEGIN
    SELECT * INTO V_M FROM IAS_NOTIFICATION_MASTER WHERE NOTIFICATION_CODE=UPPER(TRIM(P_CODE));
    IF V_M.IS_ACTIVE='N' THEN O_EMAIL_ID:=NULL; RETURN; END IF;
    V_SUBJECT:=REPLACE(REPLACE(V_M.SUBJECT_TEMPLATE,'{REFERENCE}',NVL(P_REFERENCE,'')),'{STATUS}',NVL(P_STATUS,''));
    V_TITLE:=REPLACE(REPLACE(V_M.TITLE_TEMPLATE,'{REFERENCE}',NVL(P_REFERENCE,'')),'{STATUS}',NVL(P_STATUS,''));
    V_SUMMARY:=REPLACE(REPLACE(V_M.SUMMARY_TEMPLATE,'{REFERENCE}',NVL(P_REFERENCE,'')),'{STATUS}',NVL(P_STATUS,''));
    V_BODY:=STANDARD_HTML(V_TITLE,V_SUMMARY,P_ROWS);
    IF TRIM(P_MAIL_TO) IS NULL THEN RAISE_APPLICATION_ERROR(-20101,'No TO recipient for '||P_CODE); END IF;
    PKG_INQ.P_ENQUEUE_EMAIL(P_CODE,P_REF1,P_REF2,P_MAIL_TO,P_MAIL_CC,V_SUBJECT,V_BODY,O_EMAIL_ID);
  END;

  PROCEDURE ENQUEUE_HTML(P_CODE VARCHAR2,P_REF1 NUMBER,P_REF2 NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,
    P_REFERENCE VARCHAR2,P_BODY CLOB,O_EMAIL_ID OUT NUMBER) IS
    V_M IAS_NOTIFICATION_MASTER%ROWTYPE; V_SUBJECT VARCHAR2(1000);
  BEGIN
    SELECT * INTO V_M FROM IAS_NOTIFICATION_MASTER WHERE NOTIFICATION_CODE=UPPER(TRIM(P_CODE));
    IF V_M.IS_ACTIVE='N' THEN O_EMAIL_ID:=NULL; RETURN; END IF;
    V_SUBJECT:=REPLACE(V_M.SUBJECT_TEMPLATE,'{REFERENCE}',NVL(P_REFERENCE,''));
    IF TRIM(P_MAIL_TO) IS NULL THEN RAISE_APPLICATION_ERROR(-20101,'No TO recipient for '||P_CODE); END IF;
    PKG_INQ.P_ENQUEUE_EMAIL(P_CODE,P_REF1,P_REF2,P_MAIL_TO,P_MAIL_CC,V_SUBJECT,P_BODY,O_EMAIL_ID);
  END;

  PROCEDURE SEND_AUDIT_TEAM_ASSIGNED(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_REFERENCE VARCHAR2,P_ENTITY VARCHAR2,P_PERIOD VARCHAR2,P_TEAM VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Engagement',P_REFERENCE)||ROW_HTML('Entity',P_ENTITY)||ROW_HTML('Audit Period',P_PERIOD)||ROW_HTML('Team',P_TEAM);
    ENQUEUE('AUDIT_TEAM_ASSIGNED',P_ENG_ID,NULL,P_MAIL_TO,P_MAIL_CC,P_REFERENCE,NULL,V,O_EMAIL_ID); END;

  -- Called by PKG_AR.P_ADDJOININGREPORT with its existing output cursor values.
  PROCEDURE SEND_AUDIT_TEAM_JOINED(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_ENTITY VARCHAR2,P_TEAM_LEAD VARCHAR2,P_TEAM_MEMBERS VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Entity',P_ENTITY)||ROW_HTML('Team Lead',P_TEAM_LEAD)||ROW_HTML('Team Members',P_TEAM_MEMBERS);
    ENQUEUE('AUDIT_TEAM_JOINED',P_ENG_ID,NULL,P_MAIL_TO,P_MAIL_CC,P_ENTITY,NULL,V,O_EMAIL_ID); END;

  PROCEDURE SEND_OBS_SUBMITTED_AUDITEE(P_ENG_ID NUMBER,P_OBS_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_REFERENCE VARCHAR2,P_ENTITY VARCHAR2,P_PERIOD VARCHAR2,P_HEADING VARCHAR2,P_SUMMARY CLOB,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Reference',P_REFERENCE)||ROW_HTML('Entity',P_ENTITY)||ROW_HTML('Audit Period',P_PERIOD)||ROW_HTML('Observation Heading',P_HEADING)||ROW_HTML('Status','Submitted to Auditee')||ROW_HTML('Observation Summary',DBMS_LOB.SUBSTR(P_SUMMARY,500,1));
    ENQUEUE('OBS_SUBMITTED_AUDITEE',P_ENG_ID,P_OBS_ID,P_MAIL_TO,P_MAIL_CC,P_REFERENCE,NULL,V,O_EMAIL_ID); END;

  -- Call from PKG_AE.P_SUBMITPOSTAUDITCOMPLIANCE_REVIEW after successful status update.
  -- V_GET_AIS_POST_COMPLIANCE supplies para/entity data; entity email resolution is
  -- performed once here, not repeated in the workflow procedure.
  PROCEDURE SEND_PARA_STATUS_UPDATED(P_COM_ID NUMBER,P_STATUS VARCHAR2,O_EMAIL_ID OUT NUMBER) IS
    V_REF VARCHAR2(200); V_GIST VARCHAR2(4000); V_TO VARCHAR2(2000); V_CC VARCHAR2(2000); V_ROWS CLOB;
  BEGIN
    SELECT TO_CHAR(C.PARA_NO),C.GIST_OF_PARAS,C.TO_EMAIL,C.CC_EMAIL
      INTO V_REF,V_GIST,V_TO,V_CC
      FROM V_IAS_POST_COMPLIANCE_NOTIFY C
     WHERE C.COM_ID=P_COM_ID;
    V_ROWS:=ROW_HTML('Para No.',V_REF)||ROW_HTML('Status',P_STATUS)||ROW_HTML('Gist of Para',V_GIST);
    ENQUEUE('PARA_STATUS_UPDATED',P_COM_ID,NULL,V_TO,V_CC,V_REF,P_STATUS,V_ROWS,O_EMAIL_ID);
  END;

  PROCEDURE SEND_MGMT_AUDIT_PARA_STATUS(P_COM_ID NUMBER,P_DECISION_HIST_ID NUMBER,
    P_STATUS VARCHAR2,O_EMAIL_ID OUT NUMBER) IS
    V_REF VARCHAR2(200); V_GIST VARCHAR2(4000); V_YEAR VARCHAR2(1000);
    V_RISK VARCHAR2(200); V_AUDITBY NUMBER; V_TO VARCHAR2(2000); V_CC VARCHAR2(2000);
    V_REASON VARCHAR2(1000); V_STATUS VARCHAR2(20); V_ROWS CLOB;
  BEGIN
    V_STATUS:=CASE WHEN UPPER(TRIM(P_STATUS))='SETTLED' THEN 'Settled'
                   WHEN UPPER(TRIM(P_STATUS))='REJECTED' THEN 'Rejected' END;
    IF V_STATUS IS NULL THEN RAISE_APPLICATION_ERROR(-20102,'Invalid Management Audit para status.'); END IF;
    SELECT TO_CHAR(C.PARA_NO),C.GIST_OF_PARAS,C.AUDIT_PERIOD,C.RISK,C.AUDITBY_ID,
           C.TO_EMAIL,C.CC_EMAIL
      INTO V_REF,V_GIST,V_YEAR,V_RISK,V_AUDITBY,V_TO,V_CC
      FROM V_IAS_POST_COMPLIANCE_NOTIFY C
     WHERE C.COM_ID=P_COM_ID;
    IF V_AUDITBY NOT IN (112242,112248) THEN
      RAISE_APPLICATION_ERROR(-20103,'Management Audit notification requested for another audit area.');
    END IF;
    SELECT CASE WHEN V_STATUS='Rejected' THEN H.COMMENTS END
      INTO V_REASON
      FROM AIS_T_AU_POST_COMPLIANCE_HISTORY H
     WHERE H.HIST_ID=P_DECISION_HIST_ID AND H.COM_ID=P_COM_ID;
    V_ROWS:=ROW_HTML('Para No.',V_REF)||ROW_HTML('Audit Year',V_YEAR)||
      ROW_HTML('Risk',V_RISK)||ROW_HTML('Status',V_STATUS)||ROW_HTML('Gist of Para',V_GIST)||
      CASE WHEN V_STATUS='Rejected' THEN ROW_HTML('Reason for Rejection',NVL(V_REASON,'Not recorded')) ELSE EMPTY_CLOB() END;
    ENQUEUE('MGMT_AUDIT_PARA_STATUS',P_COM_ID,P_DECISION_HIST_ID,V_TO,V_CC,V_REF,V_STATUS,V_ROWS,O_EMAIL_ID);
  END;

  PROCEDURE SEND_MGMT_AUDIT_WEEKLY(P_FROM_DATE DATE,P_TO_DATE DATE) IS
    C_CODE CONSTANT VARCHAR2(50):='MGMT_AUDIT_WEEKLY_PARA_STATUS';
    V_FROM DATE; V_TO_DATE DATE; V_SETTLED CLOB; V_REJECTED CLOB; V_BODY CLOB;
    V_SN NUMBER; V_RN NUMBER; V_EMAIL_ID NUMBER; V_REF1 NUMBER; V_EXISTING NUMBER;
    FUNCTION CELL(P_VALUE VARCHAR2,P_HEAD BOOLEAN DEFAULT FALSE) RETURN CLOB IS
      V_TAG VARCHAR2(2):=CASE WHEN P_HEAD THEN 'th' ELSE 'td' END;
      V_BG VARCHAR2(60):=CASE WHEN P_HEAD THEN 'background:#eef2f6;font-weight:bold;' ELSE '' END;
    BEGIN RETURN TO_CLOB('<'||V_TAG||' style="padding:8px 10px;border-bottom:1px solid #d9e2ec;font-size:12px;color:#334e68;'||V_BG||'">')||ESC(P_VALUE)||'</'||V_TAG||'>'; END;
    FUNCTION FMT(P_DATE DATE) RETURN VARCHAR2 IS BEGIN RETURN TO_CHAR(P_DATE,'DD-MON-YYYY'); END;
  BEGIN
    IF (P_FROM_DATE IS NULL AND P_TO_DATE IS NOT NULL) OR (P_FROM_DATE IS NOT NULL AND P_TO_DATE IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20104,'Supply both weekly reporting dates or neither.');
    END IF;
    V_FROM:=TRUNC(NVL(P_FROM_DATE,TRUNC(SYSDATE,'IW')-7));
    V_TO_DATE:=TRUNC(NVL(P_TO_DATE,TRUNC(SYSDATE,'IW')-1));
    IF V_TO_DATE<V_FROM THEN RAISE_APPLICATION_ERROR(-20105,'Invalid weekly reporting period.'); END IF;
    V_REF1:=TO_NUMBER(TO_CHAR(V_FROM,'YYYYMMDD'));

    FOR RCP IN (
      SELECT X.GROUP_ID,G.NAME GROUP_NAME,G.EMAIL_ADDRESS MAIL_TO,
             LISTAGG(DISTINCT D.EMAIL_ADDRESS,';') WITHIN GROUP (ORDER BY D.EMAIL_ADDRESS) MAIL_CC
        FROM (SELECT DISTINCT M.B_GROUP GROUP_ID,M.DIV_OFFICE DIV_ID
                FROM AIS_T_AU_POST_COMPLIANCE PC
                JOIN AIS_T_AU_POST_COMPLIANCE_HISTORY H ON H.COM_ID=PC.COM_ID
                JOIN T_AUDITEE_ENTITIES_MAPING M ON M.ENTITY_ID=PC.ENTITY_ID
               WHERE PC.AUDITED_BY IN (112242,112248)
                 AND H.COM_STATUS IN (16,12,15,18)
                 AND H.COMMENT_ON>=V_FROM AND H.COMMENT_ON<V_TO_DATE+1
                 AND M.B_GROUP IS NOT NULL AND M.DIV_OFFICE IS NOT NULL) X
        JOIN T_AUDITEE_ENTITIES G ON G.ENTITY_ID=X.GROUP_ID
        JOIN T_AUDITEE_ENTITIES D ON D.ENTITY_ID=X.DIV_ID
       WHERE TRIM(G.EMAIL_ADDRESS) IS NOT NULL AND TRIM(D.EMAIL_ADDRESS) IS NOT NULL
       GROUP BY X.GROUP_ID,G.NAME,G.EMAIL_ADDRESS
    ) LOOP
      SELECT COUNT(*) INTO V_EXISTING FROM T_AU_IID_EMAIL_QUEUE Q
       WHERE Q.EVENT_CODE=C_CODE AND Q.REF_ID1=V_REF1 AND Q.REF_ID2=RCP.GROUP_ID;
      IF V_EXISTING>0 THEN
        CONTINUE;
      END IF;
      V_SETTLED:=CELL('Sr.',TRUE)||CELL('Entity',TRUE)||CELL('Audit Year',TRUE)||CELL('Para No.',TRUE)||
        CELL('Title',TRUE)||CELL('Compliance Submitted On',TRUE)||CELL('Decision On',TRUE);
      V_REJECTED:=V_SETTLED||CELL('Reason',TRUE); V_SN:=0; V_RN:=0;
      FOR DCS IN (
        SELECT E.NAME ENTITY_NAME,PC.AUDIT_PERIOD,PC.PARA_NO,PC.GIST_OF_PARAS TITLE,
               (SELECT MAX(S.COMMENT_ON) FROM AIS_T_AU_POST_COMPLIANCE_HISTORY S
                 WHERE S.COM_ID=H.COM_ID AND S.COM_CYCLE=H.COM_CYCLE AND S.COM_STATUS=10
                   AND S.COMMENT_ON<=H.COMMENT_ON) SUBMITTED_ON,
               H.COMMENT_ON DECISION_ON,H.COMMENTS REASON,H.COM_STATUS
          FROM AIS_T_AU_POST_COMPLIANCE PC
          JOIN AIS_T_AU_POST_COMPLIANCE_HISTORY H ON H.COM_ID=PC.COM_ID
          JOIN T_AUDITEE_ENTITIES E ON E.ENTITY_ID=PC.ENTITY_ID
          JOIN (SELECT DISTINCT ENTITY_ID,B_GROUP FROM T_AUDITEE_ENTITIES_MAPING) M ON M.ENTITY_ID=PC.ENTITY_ID
         WHERE PC.AUDITED_BY IN (112242,112248) AND M.B_GROUP=RCP.GROUP_ID
           AND H.COM_STATUS IN (16,12,15,18)
           AND H.COMMENT_ON>=V_FROM AND H.COMMENT_ON<V_TO_DATE+1
         ORDER BY H.COMMENT_ON,H.HIST_ID
      ) LOOP
        IF DCS.COM_STATUS=16 THEN
          V_SN:=V_SN+1; V_SETTLED:=V_SETTLED||'<tr>'||CELL(TO_CHAR(V_SN))||CELL(DCS.ENTITY_NAME)||
            CELL(DCS.AUDIT_PERIOD)||CELL(DCS.PARA_NO)||CELL(DCS.TITLE)||CELL(FMT(DCS.SUBMITTED_ON))||CELL(FMT(DCS.DECISION_ON))||'</tr>';
        ELSE
          V_RN:=V_RN+1; V_REJECTED:=V_REJECTED||'<tr>'||CELL(TO_CHAR(V_RN))||CELL(DCS.ENTITY_NAME)||
            CELL(DCS.AUDIT_PERIOD)||CELL(DCS.PARA_NO)||CELL(DCS.TITLE)||CELL(FMT(DCS.SUBMITTED_ON))||CELL(FMT(DCS.DECISION_ON))||CELL(DCS.REASON)||'</tr>';
        END IF;
      END LOOP;
      IF V_SN=0 AND V_RN=0 THEN CONTINUE; END IF;
      IF V_SN=0 THEN V_SETTLED:=V_SETTLED||'<tr><td colspan="7" style="padding:10px">No settled paras.</td></tr>'; END IF;
      IF V_RN=0 THEN V_REJECTED:=V_REJECTED||'<tr><td colspan="8" style="padding:10px">No rejected paras.</td></tr>'; END IF;
      V_BODY:=TO_CLOB('<!DOCTYPE html><html><body style="margin:0;background:#f4f6f8;font-family:Arial;color:#1f2933"><table width="100%"><tr><td align="center"><table width="900" style="background:#fff;border-collapse:collapse"><tr><td style="padding:18px 28px;background:#173f5f;color:#fff;font-size:20px;font-weight:bold">Internal Audit System (IAS)</td></tr><tr><td style="padding:28px;font-size:22px;font-weight:bold">Weekly Management Audit Para Decisions</td></tr><tr><td style="padding:0 28px 18px">Reporting period: ')||ESC(FMT(V_FROM)||' to '||FMT(V_TO_DATE))||'<br>Group Head: '||ESC(RCP.GROUP_NAME)||'</td></tr><tr><td style="padding:8px 28px;font-weight:bold">SETTLED PARAS</td></tr><tr><td style="padding:0 28px 18px"><table width="100%" style="border-collapse:collapse">'||V_SETTLED||'</table></td></tr><tr><td style="padding:8px 28px;font-weight:bold">REJECTED PARAS</td></tr><tr><td style="padding:0 28px 18px"><table width="100%" style="border-collapse:collapse">'||V_REJECTED||'</table></td></tr><tr><td style="padding:18px 28px;background:#f8fafc;font-size:12px">'||ESC(C_FOOTER)||'</td></tr></table></td></tr></table></body></html>';
      ENQUEUE_HTML(C_CODE,V_REF1,RCP.GROUP_ID,RCP.MAIL_TO,RCP.MAIL_CC,
        FMT(V_FROM)||' to '||FMT(V_TO_DATE),V_BODY,V_EMAIL_ID);
    END LOOP;
  END;

  PROCEDURE SEND_FINAL_REPORT_ISSUED(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_REFERENCE VARCHAR2,P_ENTITY VARCHAR2,P_PERIOD VARCHAR2,P_VERSION VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Engagement',P_REFERENCE)||ROW_HTML('Entity',P_ENTITY)||ROW_HTML('Audit Period',P_PERIOD)||ROW_HTML('Report Version',P_VERSION);
    ENQUEUE('FINAL_REPORT_ISSUED',P_ENG_ID,NULL,P_MAIL_TO,P_MAIL_CC,P_REFERENCE,NULL,V,O_EMAIL_ID); END;

  PROCEDURE SEND_INQUIRY_ASSIGNED_UNIT(P_COMPLAINT_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_REFERENCE VARCHAR2,P_NATURE VARCHAR2,P_UNIT VARCHAR2,P_DUE_DATE VARCHAR2,P_DIRECTIONS CLOB,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Inquiry Reference',P_REFERENCE)||ROW_HTML('Inquiry Nature',P_NATURE)||ROW_HTML('Assigned Unit',P_UNIT)||ROW_HTML('Due Date',P_DUE_DATE)||ROW_HTML('Directions',DBMS_LOB.SUBSTR(P_DIRECTIONS,500,1));
    ENQUEUE('INQUIRY_ASSIGNED_UNIT',P_COMPLAINT_ID,NULL,P_MAIL_TO,P_MAIL_CC,P_REFERENCE,NULL,V,O_EMAIL_ID); END;

  PROCEDURE SEND_PASSWORD_RESET_SUCCESS(P_PPNO NUMBER,P_TEMP_PASSWORD VARCHAR2,P_MAIL_CC VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V_TO VARCHAR2(320); V_NAME VARCHAR2(300); V CLOB;
  BEGIN
    SELECT EMAIL,TRIM(EMPLOYEEFIRSTNAME||' '||EMPLOYEELASTNAME) INTO V_TO,V_NAME FROM V_SERVICE_EMPLOYEEINFO WHERE PPNO=P_PPNO;
    V:=ROW_HTML('User',V_NAME)||ROW_HTML('Username',TO_CHAR(P_PPNO))||ROW_HTML('Temporary Password',P_TEMP_PASSWORD);
    ENQUEUE('PASSWORD_RESET_SUCCESS',P_PPNO,NULL,V_TO,P_MAIL_CC,TO_CHAR(P_PPNO),NULL,V,O_EMAIL_ID);
  END;

  -- PKG_SM procedures already return EMAIL/EMAIL_CC; pass those values directly.
  PROCEDURE SEND_AUDIT_SAMPLE_ISSUE(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Engagement ID',TO_CHAR(P_ENG_ID)); ENQUEUE('AUDIT_SAMPLE_ISSUE',P_ENG_ID,NULL,P_MAIL_TO,P_MAIL_CC,TO_CHAR(P_ENG_ID),NULL,V,O_EMAIL_ID); END;
  PROCEDURE SEND_AUDIT_EXCEPTION_ISSUE(P_ENG_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Engagement ID',TO_CHAR(P_ENG_ID)); ENQUEUE('AUDIT_EXCEPTION_ISSUE',P_ENG_ID,NULL,P_MAIL_TO,P_MAIL_CC,TO_CHAR(P_ENG_ID),NULL,V,O_EMAIL_ID); END;

  PROCEDURE SEND_AUDIT_CRITERIA_SUBMITTED(P_ENTITY_ID NUMBER,P_MAIL_TO VARCHAR2,P_MAIL_CC VARCHAR2,P_MESSAGE CLOB,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Entity ID',TO_CHAR(P_ENTITY_ID))||ROW_HTML('Message',DBMS_LOB.SUBSTR(P_MESSAGE,2000,1)); ENQUEUE('AUDIT_CRITERIA_SUBMITTED',P_ENTITY_ID,NULL,P_MAIL_TO,P_MAIL_CC,TO_CHAR(P_ENTITY_ID),NULL,V,O_EMAIL_ID); END;

  PROCEDURE SEND_AJAX_APPLICATION_ERROR(P_REFERENCE VARCHAR2,P_STATUS NUMBER,P_ENDPOINT VARCHAR2,P_ACTION VARCHAR2,P_USER_LABEL VARCHAR2,P_DETAILS CLOB,P_MAIL_TO VARCHAR2,O_EMAIL_ID OUT NUMBER) IS V CLOB;
  BEGIN V:=ROW_HTML('Reference',P_REFERENCE)||ROW_HTML('Status',TO_CHAR(P_STATUS))||ROW_HTML('Endpoint',P_ENDPOINT)||ROW_HTML('Action',P_ACTION)||ROW_HTML('User',P_USER_LABEL)||ROW_HTML('Details',DBMS_LOB.SUBSTR(P_DETAILS,2000,1)); ENQUEUE('AJAX_APPLICATION_ERROR',NULL,NULL,P_MAIL_TO,NULL,P_REFERENCE,TO_CHAR(P_STATUS),V,O_EMAIL_ID); END;
END PKG_IAS_NOTIFICATION;
/

--------------------------------------------------------------------------------
-- 4. Integration notes: add only these calls to existing successful branches.
--    Do not change status updates, validation, cursor messages or commits.
--------------------------------------------------------------------------------
/*
  PKG_AE.P_SUBMITPOSTAUDITCOMPLIANCE_REVIEW
    After the existing successful update/history insert:
      PKG_IAS_NOTIFICATION.SEND_PARA_STATUS_UPDATED(vr1.comid,'Settled',v_email_id);
    Remove TO_EMAIL/CC_EMAIL/CC2_EMAIL and ET/AD/MT joins from its cursor because
    the notification procedure owns that lookup from V_GET_AIS_POST_COMPLIANCE.

  PKG_AR.P_ADDJOININGREPORT
    In the team-lead success branch, call SEND_AUDIT_TEAM_JOINED using the values
    already calculated by that process; do not re-query them.

  PKG_SM.P_ADD_SAMPLE_DATA / P_ADD_EXCEPTION_DATA
    In the existing failure branch, call the corresponding SEND_* procedure with
    EMAIL and EMAIL_CC already returned/calculated by the process.

  Application-owned workflows (team assignment, observation submission, final
  report, inquiry assignment, password reset, AJAX diagnostics) may migrate to
  these procedures one at a time. Until then their existing C# send calls remain
  valid; this deployment alone does not change business/workflow behavior.
*/

-- Deployment verification
SELECT NOTIFICATION_ID,NOTIFICATION_CODE,NOTIFICATION_NAME,RELATED_PROCEDURE,
       DATA_SOURCE_NAME,NOTIFICATION_TYPE,IS_ACTIVE
  FROM V_IAS_NOTIFICATION_MASTER
 ORDER BY NOTIFICATION_ID;

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('IAS_NOTIFICATION_MASTER','V_IAS_NOTIFICATION_MASTER',
                       'V_IAS_POST_COMPLIANCE_NOTIFY','PKG_IAS_NOTIFICATION')
 ORDER BY OBJECT_TYPE,OBJECT_NAME;

SELECT NAME,TYPE,LINE,POSITION,TEXT
  FROM USER_ERRORS
 WHERE NAME='PKG_IAS_NOTIFICATION'
 ORDER BY SEQUENCE;
