CREATE OR REPLACE PROCEDURE PKG_INQ.GET_IID_TASK_LIST(
    P_UNIT_ID   IN NUMBER,
    IO_CURSOR   OUT PKG_INQ.T_CURSOR
) IS
BEGIN
  OPEN IO_CURSOR FOR
    SELECT h.COMPLAINT_ID,
           h.COMPLAINT_NO,
           d.COMPLAINANT_NAME,
           NVL(h.UPDATED_ON, h.SUBMITTED_ON) AS ASSIGNED_ON,
           h.STATUS,
           h.ASSIGNED_UNIT_ID,
           (SELECT MAX(p.PLAN_ID)
              FROM T_AU_IID_INV_PLAN p
             WHERE p.COMPLAINT_ID = h.COMPLAINT_ID) AS PLAN_ID
      FROM T_AU_IID_COMPLAINT_HDR h
      LEFT JOIN T_AU_IID_COMPLAINT_IAID d
        ON d.COMPLAINT_ID = h.COMPLAINT_ID
     WHERE h.ACTIVE_FLAG = 'Y'
       AND NVL(h.ASSIGNED_UNIT_ID, -1) = P_UNIT_ID
     ORDER BY NVL(h.UPDATED_ON, h.SUBMITTED_ON) DESC, h.COMPLAINT_ID DESC;
END;
/

PROCEDURE P_ENQUEUE_EMAIL(
    P_EVENT_CODE IN VARCHAR2,
    P_REF_ID1    IN NUMBER,
    P_REF_ID2    IN NUMBER,
    P_MAIL_TO    IN VARCHAR2,
    P_MAIL_CC    IN VARCHAR2,
    P_SUBJECT    IN VARCHAR2,
    P_BODY       IN CLOB,
    O_EMAIL_ID   OUT NUMBER
);

CREATE OR REPLACE PROCEDURE PKG_INQ.P_ENQUEUE_EMAIL(
    P_EVENT_CODE IN VARCHAR2,
    P_REF_ID1    IN NUMBER,
    P_REF_ID2    IN NUMBER,
    P_MAIL_TO    IN VARCHAR2,
    P_MAIL_CC    IN VARCHAR2,
    P_SUBJECT    IN VARCHAR2,
    P_BODY       IN CLOB,
    O_EMAIL_ID   OUT NUMBER
) IS
BEGIN
  INSERT INTO T_AU_EMAIL_QUEUE(
      EVENT_CODE, REF_ID1, REF_ID2, MAIL_TO, MAIL_CC,
      SUBJECT, BODY, STATUS, CREATED_ON
  ) VALUES (
      UPPER(TRIM(P_EVENT_CODE)),
      P_REF_ID1,
      P_REF_ID2,
      P_MAIL_TO,
      P_MAIL_CC,
      P_SUBJECT,
      P_BODY,
      'PENDING',
      SYSDATE
  )
  RETURNING EMAIL_ID INTO O_EMAIL_ID;
END;
/

PROCEDURE P_GET_EMAIL_QUEUE(
    P_STATUS    IN VARCHAR2,
    P_FROM_DATE IN DATE,
    P_TO_DATE   IN DATE,
    IO_CURSOR   OUT PKG_INQ.T_CURSOR
);

CREATE OR REPLACE PROCEDURE PKG_INQ.P_GET_EMAIL_QUEUE(
    P_STATUS    IN VARCHAR2,
    P_FROM_DATE IN DATE,
    P_TO_DATE   IN DATE,
    IO_CURSOR   OUT PKG_INQ.T_CURSOR
) IS
BEGIN
  OPEN IO_CURSOR FOR
    SELECT EMAIL_ID,
           EVENT_CODE,
           REF_ID1,
           REF_ID2,
           MAIL_TO,
           MAIL_CC,
           SUBJECT,
           BODY,
           STATUS,
           CREATED_ON,
           SENT_ON,
           ERROR_TEXT
      FROM T_AU_EMAIL_QUEUE
     WHERE (P_STATUS IS NULL OR TRIM(P_STATUS) = '' OR STATUS = UPPER(TRIM(P_STATUS)))
       AND (P_FROM_DATE IS NULL OR CREATED_ON >= P_FROM_DATE)
       AND (P_TO_DATE   IS NULL OR CREATED_ON < (P_TO_DATE + 1))
     ORDER BY EMAIL_ID DESC;
END;
/

PROCEDURE P_MARK_EMAIL_SENT(
    P_EMAIL_ID IN NUMBER
);

CREATE OR REPLACE PROCEDURE PKG_INQ.P_MARK_EMAIL_SENT(
    P_EMAIL_ID IN NUMBER
) IS
BEGIN
  UPDATE T_AU_EMAIL_QUEUE
     SET STATUS   = 'SENT',
         SENT_ON  = SYSDATE,
         ERROR_TEXT = NULL
   WHERE EMAIL_ID = P_EMAIL_ID;
END;
/

PROCEDURE P_MARK_EMAIL_FAILED(
    P_EMAIL_ID   IN NUMBER,
    P_ERROR_TEXT IN VARCHAR2
);

CREATE OR REPLACE PROCEDURE PKG_INQ.P_MARK_EMAIL_FAILED(
    P_EMAIL_ID   IN NUMBER,
    P_ERROR_TEXT IN VARCHAR2
) IS
BEGIN
  UPDATE T_AU_EMAIL_QUEUE
     SET STATUS     = 'FAILED',
         ERROR_TEXT = SUBSTR(P_ERROR_TEXT, 1, 2000)
   WHERE EMAIL_ID = P_EMAIL_ID;
END;
/
