/*
  IID Exceptions Module
  Production-style executable script aligned with DBConnection.IID.ExceptionReports.cs

  Design notes:
  - Keeps ONE package only: PKG_ISM.
  - Exposes exactly the procedure names used by DBConnection.IID.ExceptionReports.cs.
  - Avoids hard compile-time dependency on unknown legacy objects by using metadata-driven dynamic SQL.
  - Supports reruns through safe drop blocks.
  - Includes header/format/entity/role/source metadata, history, and execution log.
  - Returns column names expected by the existing C# models.
*/

-------------------------------------------------------------------------------
-- Safe drop for reruns
-------------------------------------------------------------------------------
BEGIN
    FOR X IN (
        SELECT 'PACKAGE PKG_ISM' AS DDL_TEXT FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_RUN_LOG CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_SOURCE_HIST CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_ROLE_HIST CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_ENTITY_HIST CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_FORMAT_HIST CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_REPORT_HIST CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXC_SOURCE_CFG CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXCEPTION_REPORT_ROLE CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXCEPTION_REPORT_ENTITY CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXCEPTION_REPORT_FORMAT CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'TABLE T_AU_IID_EXCEPTION_REPORT_HDR CASCADE CONSTRAINTS PURGE' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_RUN_LOG' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_SOURCE_HIST' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_ROLE_HIST' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_ENTITY_HIST' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_FORMAT_HIST' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_REPORT_HIST' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_SOURCE_CFG' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_RPT_ROLE' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_RPT_ENTITY' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_RPT_FORMAT' FROM DUAL
        UNION ALL SELECT 'SEQUENCE SEQ_T_AU_IID_EXC_RPT_HDR' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP ' || X.DDL_TEXT;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE NOT IN (-4043, -942, -2289) THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;
/

-------------------------------------------------------------------------------
-- Master tables
-------------------------------------------------------------------------------
CREATE TABLE T_AU_IID_EXCEPTION_REPORT_HDR (
    IID_REPORT_ID           NUMBER          PRIMARY KEY,
    REPORT_CODE             VARCHAR2(50)    NOT NULL,
    REPORT_TITLE            VARCHAR2(300)   NOT NULL,
    DISCRIPTION             VARCHAR2(1000),
    IND                     VARCHAR2(50),
    LOAN_STATUS             VARCHAR2(50),
    REPORTING_PERIOD        VARCHAR2(50),
    SORT_ORDER              NUMBER,
    IS_ACTIVE               CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    CONSTRAINT UK_T_AU_IID_EXC_RPT_HDR_01 UNIQUE (REPORT_CODE),
    CONSTRAINT CK_T_AU_IID_EXC_RPT_HDR_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXCEPTION_REPORT_FORMAT (
    FORMAT_ID               NUMBER          PRIMARY KEY,
    R_ID                    NUMBER          NOT NULL,
    COLUMN_NAME             VARCHAR2(128)   NOT NULL,
    COLUMN_HEADER           VARCHAR2(200)   NOT NULL,
    COLUMN_ORDER            NUMBER          NOT NULL,
    DATA_TYPE               VARCHAR2(30),
    IS_ACTIVE               CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    CONSTRAINT FK_T_AU_IID_EXC_FMT_01 FOREIGN KEY (R_ID)
        REFERENCES T_AU_IID_EXCEPTION_REPORT_HDR (IID_REPORT_ID),
    CONSTRAINT UK_T_AU_IID_EXC_FMT_01 UNIQUE (R_ID, COLUMN_NAME),
    CONSTRAINT UK_T_AU_IID_EXC_FMT_02 UNIQUE (R_ID, COLUMN_ORDER),
    CONSTRAINT CK_T_AU_IID_EXC_FMT_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXCEPTION_REPORT_ENTITY (
    MAP_ID                  NUMBER          PRIMARY KEY,
    R_ID                    NUMBER          NOT NULL,
    ENTITY_ID               NUMBER          NOT NULL,
    IS_ACTIVE               CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    CONSTRAINT FK_T_AU_IID_EXC_ENT_01 FOREIGN KEY (R_ID)
        REFERENCES T_AU_IID_EXCEPTION_REPORT_HDR (IID_REPORT_ID),
    CONSTRAINT UK_T_AU_IID_EXC_ENT_01 UNIQUE (R_ID, ENTITY_ID),
    CONSTRAINT CK_T_AU_IID_EXC_ENT_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXCEPTION_REPORT_ROLE (
    MAP_ID                  NUMBER          PRIMARY KEY,
    R_ID                    NUMBER          NOT NULL,
    ROLE_ID                 NUMBER          NOT NULL,
    IS_ACTIVE               CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    CONSTRAINT FK_T_AU_IID_EXC_ROLE_01 FOREIGN KEY (R_ID)
        REFERENCES T_AU_IID_EXCEPTION_REPORT_HDR (IID_REPORT_ID),
    CONSTRAINT UK_T_AU_IID_EXC_ROLE_01 UNIQUE (R_ID, ROLE_ID),
    CONSTRAINT CK_T_AU_IID_EXC_ROLE_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

/*
  SOURCE_CODE values supported by package body:
    REPORT_DATA_<R_ID>      -> report data query/object
    ACCOUNT_TXN             -> account transaction source
    ACCOUNT_DOC             -> account document source
    LOAN_EXCEPTIONS         -> loan exception source
    LOAN_DOC                -> loan document source
    LOAN_DOC_IMAGE          -> loan document image source
    LOAN_TXN                -> loan transaction source

  SOURCE_TYPE:
    VIEW      -> SOURCE_NAME contains a view name
    TABLE     -> SOURCE_NAME contains a table name
    SQL       -> SOURCE_SQL contains a complete SELECT with bind placeholders
*/
CREATE TABLE T_AU_IID_EXC_SOURCE_CFG (
    SOURCE_CFG_ID           NUMBER          PRIMARY KEY,
    SOURCE_CODE             VARCHAR2(100)   NOT NULL,
    SOURCE_TYPE             VARCHAR2(20)    NOT NULL,
    SOURCE_NAME             VARCHAR2(200),
    SOURCE_SQL              CLOB,
    KEY_COLUMN_1            VARCHAR2(100),
    KEY_COLUMN_2            VARCHAR2(100),
    IS_ACTIVE               CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    CONSTRAINT UK_T_AU_IID_EXC_SRC_01 UNIQUE (SOURCE_CODE),
    CONSTRAINT CK_T_AU_IID_EXC_SRC_TYP CHECK (SOURCE_TYPE IN ('VIEW','TABLE','SQL')),
    CONSTRAINT CK_T_AU_IID_EXC_SRC_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

-------------------------------------------------------------------------------
-- History tables
-------------------------------------------------------------------------------
CREATE TABLE T_AU_IID_EXC_REPORT_HIST (
    HIST_ID                 NUMBER PRIMARY KEY,
    IID_REPORT_ID           NUMBER          NOT NULL,
    REPORT_CODE             VARCHAR2(50)    NOT NULL,
    REPORT_TITLE            VARCHAR2(300)   NOT NULL,
    DISCRIPTION             VARCHAR2(1000),
    IND                     VARCHAR2(50),
    LOAN_STATUS             VARCHAR2(50),
    REPORTING_PERIOD        VARCHAR2(50),
    SORT_ORDER              NUMBER,
    IS_ACTIVE               CHAR(1)         NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE            NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    SNAPSHOT_ACTION         VARCHAR2(30)    NOT NULL,
    SNAPSHOT_BY             NUMBER          NOT NULL,
    SNAPSHOT_ON             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_T_AU_IID_EXC_RH_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXC_FORMAT_HIST (
    HIST_ID                 NUMBER PRIMARY KEY,
    FORMAT_ID               NUMBER          NOT NULL,
    R_ID                    NUMBER          NOT NULL,
    COLUMN_NAME             VARCHAR2(128)   NOT NULL,
    COLUMN_HEADER           VARCHAR2(200)   NOT NULL,
    COLUMN_ORDER            NUMBER          NOT NULL,
    DATA_TYPE               VARCHAR2(30),
    IS_ACTIVE               CHAR(1)         NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE            NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    SNAPSHOT_ACTION         VARCHAR2(30)    NOT NULL,
    SNAPSHOT_BY             NUMBER          NOT NULL,
    SNAPSHOT_ON             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_T_AU_IID_EXC_FH_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXC_ENTITY_HIST (
    HIST_ID                 NUMBER PRIMARY KEY,
    MAP_ID                  NUMBER          NOT NULL,
    R_ID                    NUMBER          NOT NULL,
    ENTITY_ID               NUMBER          NOT NULL,
    IS_ACTIVE               CHAR(1)         NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE            NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    SNAPSHOT_ACTION         VARCHAR2(30)    NOT NULL,
    SNAPSHOT_BY             NUMBER          NOT NULL,
    SNAPSHOT_ON             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_T_AU_IID_EXC_EH_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXC_ROLE_HIST (
    HIST_ID                 NUMBER PRIMARY KEY,
    MAP_ID                  NUMBER          NOT NULL,
    R_ID                    NUMBER          NOT NULL,
    ROLE_ID                 NUMBER          NOT NULL,
    IS_ACTIVE               CHAR(1)         NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE            NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    SNAPSHOT_ACTION         VARCHAR2(30)    NOT NULL,
    SNAPSHOT_BY             NUMBER          NOT NULL,
    SNAPSHOT_ON             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_T_AU_IID_EXC_RLH_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXC_SOURCE_HIST (
    HIST_ID                 NUMBER PRIMARY KEY,
    SOURCE_CFG_ID           NUMBER          NOT NULL,
    SOURCE_CODE             VARCHAR2(100)   NOT NULL,
    SOURCE_TYPE             VARCHAR2(20)    NOT NULL,
    SOURCE_NAME             VARCHAR2(200),
    SOURCE_SQL              CLOB,
    KEY_COLUMN_1            VARCHAR2(100),
    KEY_COLUMN_2            VARCHAR2(100),
    IS_ACTIVE               CHAR(1)         NOT NULL,
    CREATED_BY              NUMBER          NOT NULL,
    CREATED_ON              DATE            NOT NULL,
    UPDATED_BY              NUMBER,
    UPDATED_ON              DATE,
    SNAPSHOT_ACTION         VARCHAR2(30)    NOT NULL,
    SNAPSHOT_BY             NUMBER          NOT NULL,
    SNAPSHOT_ON             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_T_AU_IID_EXC_SH_TYP CHECK (SOURCE_TYPE IN ('VIEW','TABLE','SQL')),
    CONSTRAINT CK_T_AU_IID_EXC_SH_ACT CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE T_AU_IID_EXC_RUN_LOG (
    RUN_ID                  NUMBER PRIMARY KEY,
    PROC_NAME               VARCHAR2(100)   NOT NULL,
    REPORT_ID               NUMBER,
    ENG_ID                  NUMBER,
    ACCOUNT_NO              VARCHAR2(100),
    LOAN_DISB_ID            VARCHAR2(100),
    IMAGE_ID                NUMBER,
    P_NO                    NUMBER,
    ENT_ID                  NUMBER,
    R_ID                    NUMBER,
    STATUS                  VARCHAR2(20)    NOT NULL,
    ROWS_RETURNED           NUMBER,
    ERROR_TEXT              VARCHAR2(2000),
    EXECUTED_ON             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_T_AU_IID_EXC_RUN_ST CHECK (STATUS IN ('SUCCESS','FAILED'))
);
/

-------------------------------------------------------------------------------
-- Sequences
-------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_T_AU_IID_EXC_RPT_HDR START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_RPT_FORMAT START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_RPT_ENTITY START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_RPT_ROLE START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_SOURCE_CFG START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_REPORT_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_FORMAT_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_ENTITY_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_ROLE_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_SOURCE_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_T_AU_IID_EXC_RUN_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
/

-------------------------------------------------------------------------------
-- Helpful indexes
-------------------------------------------------------------------------------
CREATE INDEX IX_T_AU_IID_EXC_FMT_RID ON T_AU_IID_EXCEPTION_REPORT_FORMAT(R_ID, IS_ACTIVE, COLUMN_ORDER);
/
CREATE INDEX IX_T_AU_IID_EXC_ENT_RID ON T_AU_IID_EXCEPTION_REPORT_ENTITY(R_ID, ENTITY_ID, IS_ACTIVE);
/
CREATE INDEX IX_T_AU_IID_EXC_ROLE_RID ON T_AU_IID_EXCEPTION_REPORT_ROLE(R_ID, ROLE_ID, IS_ACTIVE);
/
CREATE INDEX IX_T_AU_IID_EXC_SRC_CODE ON T_AU_IID_EXC_SOURCE_CFG(SOURCE_CODE, IS_ACTIVE);
/
CREATE INDEX IX_T_AU_IID_EXC_RUN_PROC ON T_AU_IID_EXC_RUN_LOG(PROC_NAME, EXECUTED_ON);
/

-------------------------------------------------------------------------------
-- Seed source registry (placeholder object names / SQL to be adjusted as needed)
-------------------------------------------------------------------------------
INSERT INTO T_AU_IID_EXC_SOURCE_CFG
    (SOURCE_CFG_ID, SOURCE_CODE, SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL, KEY_COLUMN_1, KEY_COLUMN_2, IS_ACTIVE, CREATED_BY)
VALUES
    (SEQ_T_AU_IID_EXC_SOURCE_CFG.NEXTVAL, 'ACCOUNT_TXN', 'SQL', NULL,
     'SELECT TRANSACTIONMASTERCODE, DESCRIPTION, REMARKS, TRANSACTIONDATE, TRANSACTIONDATE_DISP, AUTHORIZATIONDATE, AUTHORIZATIONDATE_DISP, DRAMOUNT, CRAMOUNT, TOACCOUNTID, TOACCOUNTTITLE, TOACCOUNTNO, TO_ACC_BRANCHID, INSTRUMENTNO FROM V_IID_ACCOUNT_TRANSACTIONS WHERE ENG_ID = :1 AND ACCOUNTNO = :2',
     'ENG_ID', 'ACCOUNTNO', 'Y', 0);
/
INSERT INTO T_AU_IID_EXC_SOURCE_CFG
    (SOURCE_CFG_ID, SOURCE_CODE, SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL, KEY_COLUMN_1, KEY_COLUMN_2, IS_ACTIVE, CREATED_BY)
VALUES
    (SEQ_T_AU_IID_EXC_SOURCE_CFG.NEXTVAL, 'ACCOUNT_DOC', 'SQL', NULL,
     'SELECT OLDACCOUNTNO, PAGENO, NAME, DOC_IMAGE, DOC_REMARKS FROM V_IID_ACCOUNT_DOCUMENTS WHERE OLDACCOUNTNO = :1',
     'OLDACCOUNTNO', NULL, 'Y', 0);
/
INSERT INTO T_AU_IID_EXC_SOURCE_CFG
    (SOURCE_CFG_ID, SOURCE_CODE, SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL, KEY_COLUMN_1, KEY_COLUMN_2, IS_ACTIVE, CREATED_BY)
VALUES
    (SEQ_T_AU_IID_EXC_SOURCE_CFG.NEXTVAL, 'LOAN_EXCEPTIONS', 'SQL', NULL,
     'SELECT LOAN_DISB_ID, TYPE, SCHEME, L_PURPOSE, LC_NO, CNIC, CUSTOMERNAME, APP_DATE_DISP, DISB_DATE_DISP, DEV_AMOUNT, OUTSTANDING FROM V_IID_LOAN_EXCEPTIONS WHERE ENG_ID = :1 AND NVL(TO_NUMBER(LOAN_STATUS_ID),-1) = :2',
     'ENG_ID', 'LOAN_STATUS_ID', 'Y', 0);
/
INSERT INTO T_AU_IID_EXC_SOURCE_CFG
    (SOURCE_CFG_ID, SOURCE_CODE, SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL, KEY_COLUMN_1, KEY_COLUMN_2, IS_ACTIVE, CREATED_BY)
VALUES
    (SEQ_T_AU_IID_EXC_SOURCE_CFG.NEXTVAL, 'LOAN_DOC', 'SQL', NULL,
     'SELECT IMAGEID, BRANCHCODE, LOAN_APP_ID, CNIC, CUSTOMERNAME, LOAN_CASE_NO, LOAN_DISB_ID, DOCNAME FROM V_IID_LOAN_DOCUMENTS WHERE ENG_ID = :1 AND LOAN_DISB_ID = :2',
     'ENG_ID', 'LOAN_DISB_ID', 'Y', 0);
/
INSERT INTO T_AU_IID_EXC_SOURCE_CFG
    (SOURCE_CFG_ID, SOURCE_CODE, SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL, KEY_COLUMN_1, KEY_COLUMN_2, IS_ACTIVE, CREATED_BY)
VALUES
    (SEQ_T_AU_IID_EXC_SOURCE_CFG.NEXTVAL, 'LOAN_DOC_IMAGE', 'SQL', NULL,
     'SELECT IMAGEDATA FROM V_IID_LOAN_DOCUMENT_IMAGES WHERE IMAGEID = :1',
     'IMAGEID', NULL, 'Y', 0);
/
INSERT INTO T_AU_IID_EXC_SOURCE_CFG
    (SOURCE_CFG_ID, SOURCE_CODE, SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL, KEY_COLUMN_1, KEY_COLUMN_2, IS_ACTIVE, CREATED_BY)
VALUES
    (SEQ_T_AU_IID_EXC_SOURCE_CFG.NEXTVAL, 'LOAN_TXN', 'SQL', NULL,
     'SELECT DESCRIPTION, MANUALVOUCHERNO, TRANSACTIONDATE, TRANSACTIONDATE_DISP, DRAMOUNT, CRAMOUNT, LN_ACCOUNTID, CREATEDON, CREATEDON_DISP, REMARKS, REJECTIONDATE, REJECTIONDATE_DISP, REVERSALDATE, REVERSALDATE_DISP, WORKINGDATE, WORKINGDATE_DISP, AUTHORIZATIONDATE, AUTHORIZATIONDATE_DISP, MCO_RECEIPT_NO, MCO_BOOK_NO FROM V_IID_LOAN_TRANSACTIONS WHERE ENG_ID = :1 AND LOAN_DISB_ID = :2',
     'ENG_ID', 'LOAN_DISB_ID', 'Y', 0);
/

COMMIT;
/

-------------------------------------------------------------------------------
-- Package spec
-------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_ISM AS
    TYPE T_CURSOR IS REF CURSOR;

    PROCEDURE T_AU_EXCEPTION_REPORT(
        E_ID      IN NUMBER,
        P_NO      IN NUMBER,
        ENT_ID    IN NUMBER,
        R_ID      IN NUMBER,
        T_CURSOR  OUT T_CURSOR);

    PROCEDURE P_ADD_NEW_EXP_REPORT(
        P_IND           IN VARCHAR2,
        P_REPORT_ID     IN NUMBER,
        P_REPORT_TITLE  IN VARCHAR2,
        P_DESCRIPTION   IN VARCHAR2,
        P_R_TYPE        IN VARCHAR2,
        P_L_STATUS      IN NUMBER,
        P_P_NO          IN NUMBER,
        P_R_ID          IN NUMBER,
        P_ENT_ID        IN NUMBER,
        IO_CURSOR       OUT T_CURSOR);

    PROCEDURE P_GET_EXCEPTION_REPORT_FORMAT(
        P_R_ID      IN NUMBER,
        IO_CURSOR   OUT T_CURSOR);

    PROCEDURE P_INSERT_EXCEPTION_REPORT_FORMAT(
        P_R_ID           IN NUMBER,
        P_COLUMN_NAME    IN VARCHAR2,
        P_COLUMN_HEADER  IN VARCHAR2,
        P_COLUMN_ORDER   IN NUMBER,
        P_DATA_TYPE      IN VARCHAR2,
        P_IS_ACTIVE      IN VARCHAR2,
        P_P_NO           IN NUMBER,
        O_FORMAT_ID      OUT NUMBER);

    PROCEDURE P_UPDATE_EXCEPTION_REPORT_FORMAT(
        P_FORMAT_ID      IN NUMBER,
        P_COLUMN_HEADER  IN VARCHAR2,
        P_COLUMN_ORDER   IN NUMBER,
        P_DATA_TYPE      IN VARCHAR2,
        P_IS_ACTIVE      IN VARCHAR2,
        P_P_NO           IN NUMBER);

    PROCEDURE P_GET_EXCEPTION_REPORT_DATA(
        P_R_ID      IN NUMBER,
        P_ENG_ID    IN NUMBER,
        IO_CURSOR1  OUT T_CURSOR,
        IO_CURSOR2  OUT T_CURSOR);

    PROCEDURE P_GET_ACCOUNT_TRANSCATIONS(
        E_ID       IN NUMBER,
        AC_NUMBER  IN VARCHAR2,
        P_NO       IN NUMBER,
        R_ID       IN NUMBER,
        ENT_ID     IN NUMBER,
        T_CURSOR   OUT T_CURSOR);

    PROCEDURE P_GET_ACCOUNT_DOC(
        AC_NUMBER  IN VARCHAR2,
        P_NO       IN NUMBER,
        R_ID       IN NUMBER,
        ENT_ID     IN NUMBER,
        T_CURSOR   OUT T_CURSOR);

    PROCEDURE P_GET_LOANS_EXCEPTIONS(
        LSTATUS   IN NUMBER,
        E_ID      IN NUMBER,
        P_NO      IN NUMBER,
        R_ID      IN NUMBER,
        ENT_ID    IN NUMBER,
        T_CURSOR  OUT T_CURSOR);

    PROCEDURE P_GET_LOAN_DOCUMENTS(
        E_ID       IN VARCHAR2,
        L_DISB_ID  IN VARCHAR2,
        P_NO       IN NUMBER,
        ENT_ID     IN NUMBER,
        R_ID       IN NUMBER,
        T_CURSOR   OUT T_CURSOR);

    PROCEDURE P_GET_LOAN_DOCUMENTS_IMAGE(
        IMAGE_ID  IN VARCHAR2,
        T_CURSOR  OUT T_CURSOR);

    PROCEDURE P_GET_LOAN_TRANSACTIONS(
        E_ID       IN VARCHAR2,
        L_DISB_ID  IN VARCHAR2,
        P_NO       IN NUMBER,
        ENT_ID     IN NUMBER,
        R_ID       IN NUMBER,
        T_CURSOR   OUT T_CURSOR);
END PKG_ISM;
/

-------------------------------------------------------------------------------
-- Package body
-------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY PKG_ISM AS

    FUNCTION GET_SOURCE_SQL(P_SOURCE_CODE IN VARCHAR2, P_SOURCE_TYPE OUT VARCHAR2, P_SOURCE_NAME OUT VARCHAR2)
        RETURN CLOB
    IS
        V_SQL CLOB;
    BEGIN
        SELECT SOURCE_TYPE, SOURCE_NAME, SOURCE_SQL
          INTO P_SOURCE_TYPE, P_SOURCE_NAME, V_SQL
          FROM T_AU_IID_EXC_SOURCE_CFG
         WHERE SOURCE_CODE = P_SOURCE_CODE
           AND IS_ACTIVE = 'Y';

        IF P_SOURCE_TYPE IN ('VIEW', 'TABLE') THEN
            RETURN 'SELECT * FROM ' || P_SOURCE_NAME;
        END IF;

        RETURN V_SQL;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_SOURCE_TYPE := NULL;
            P_SOURCE_NAME := NULL;
            RETURN NULL;
    END GET_SOURCE_SQL;

    PROCEDURE LOG_RUN(
        P_PROC_NAME      IN VARCHAR2,
        P_REPORT_ID      IN NUMBER   DEFAULT NULL,
        P_ENG_ID         IN NUMBER   DEFAULT NULL,
        P_ACCOUNT_NO     IN VARCHAR2 DEFAULT NULL,
        P_LOAN_DISB_ID   IN VARCHAR2 DEFAULT NULL,
        P_IMAGE_ID       IN NUMBER   DEFAULT NULL,
        P_P_NO           IN NUMBER   DEFAULT NULL,
        P_ENT_ID         IN NUMBER   DEFAULT NULL,
        P_R_ID           IN NUMBER   DEFAULT NULL,
        P_STATUS         IN VARCHAR2,
        P_ROWS_RETURNED  IN NUMBER   DEFAULT NULL,
        P_ERROR_TEXT     IN VARCHAR2 DEFAULT NULL)
    IS
    BEGIN
        INSERT INTO T_AU_IID_EXC_RUN_LOG
            (RUN_ID, PROC_NAME, REPORT_ID, ENG_ID, ACCOUNT_NO, LOAN_DISB_ID, IMAGE_ID, P_NO, ENT_ID, R_ID, STATUS, ROWS_RETURNED, ERROR_TEXT)
        VALUES
            (SEQ_T_AU_IID_EXC_RUN_LOG.NEXTVAL, P_PROC_NAME, P_REPORT_ID, P_ENG_ID, P_ACCOUNT_NO, P_LOAN_DISB_ID, P_IMAGE_ID, P_P_NO, P_ENT_ID, P_R_ID, P_STATUS, P_ROWS_RETURNED, SUBSTR(P_ERROR_TEXT,1,2000));
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END LOG_RUN;

    PROCEDURE T_AU_EXCEPTION_REPORT(
        E_ID      IN NUMBER,
        P_NO      IN NUMBER,
        ENT_ID    IN NUMBER,
        R_ID      IN NUMBER,
        T_CURSOR  OUT T_CURSOR)
    IS
    BEGIN
        OPEN T_CURSOR FOR
            SELECT H.IID_REPORT_ID AS R_ID,
                   H.REPORT_TITLE,
                   H.DISCRIPTION,
                   H.LOAN_STATUS,
                   H.IND,
                   H.REPORTING_PERIOD,
                   CAST(NULL AS NUMBER) AS EXCEPTION_COUNT
              FROM T_AU_IID_EXCEPTION_REPORT_HDR H
             WHERE H.IS_ACTIVE = 'Y'
               AND EXISTS (
                    SELECT 1
                      FROM T_AU_IID_EXCEPTION_REPORT_ENTITY E
                     WHERE E.R_ID = H.IID_REPORT_ID
                       AND E.ENTITY_ID = ENT_ID
                       AND E.IS_ACTIVE = 'Y')
               AND EXISTS (
                    SELECT 1
                      FROM T_AU_IID_EXCEPTION_REPORT_ROLE RR
                     WHERE RR.R_ID = H.IID_REPORT_ID
                       AND RR.ROLE_ID = R_ID
                       AND RR.IS_ACTIVE = 'Y')
             ORDER BY NVL(H.SORT_ORDER,999999), H.REPORT_TITLE;

        LOG_RUN('T_AU_EXCEPTION_REPORT', NULL, E_ID, NULL, NULL, NULL, P_NO, ENT_ID, R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('T_AU_EXCEPTION_REPORT', NULL, E_ID, NULL, NULL, NULL, P_NO, ENT_ID, R_ID, 'FAILED', NULL, SQLERRM);
            RAISE;
    END T_AU_EXCEPTION_REPORT;

    PROCEDURE ENSURE_REPORT_ACCESS(
        P_REPORT_ID  IN NUMBER,
        P_ENT_ID     IN NUMBER,
        P_ROLE_ID    IN NUMBER,
        P_P_NO       IN NUMBER)
    IS
    BEGIN
        IF P_ENT_ID IS NOT NULL THEN
            MERGE INTO T_AU_IID_EXCEPTION_REPORT_ENTITY T
            USING (SELECT P_REPORT_ID AS R_ID, P_ENT_ID AS ENTITY_ID FROM DUAL) S
               ON (T.R_ID = S.R_ID AND T.ENTITY_ID = S.ENTITY_ID)
            WHEN MATCHED THEN
                UPDATE SET T.IS_ACTIVE = 'Y',
                           T.UPDATED_BY = NVL(P_P_NO, 0),
                           T.UPDATED_ON = SYSDATE
            WHEN NOT MATCHED THEN
                INSERT (MAP_ID, R_ID, ENTITY_ID, IS_ACTIVE, CREATED_BY, CREATED_ON)
                VALUES (SEQ_T_AU_IID_EXC_RPT_ENTITY.NEXTVAL, S.R_ID, S.ENTITY_ID, 'Y', NVL(P_P_NO, 0), SYSDATE);
        END IF;

        IF P_ROLE_ID IS NOT NULL THEN
            MERGE INTO T_AU_IID_EXCEPTION_REPORT_ROLE T
            USING (SELECT P_REPORT_ID AS R_ID, P_ROLE_ID AS ROLE_ID FROM DUAL) S
               ON (T.R_ID = S.R_ID AND T.ROLE_ID = S.ROLE_ID)
            WHEN MATCHED THEN
                UPDATE SET T.IS_ACTIVE = 'Y',
                           T.UPDATED_BY = NVL(P_P_NO, 0),
                           T.UPDATED_ON = SYSDATE
            WHEN NOT MATCHED THEN
                INSERT (MAP_ID, R_ID, ROLE_ID, IS_ACTIVE, CREATED_BY, CREATED_ON)
                VALUES (SEQ_T_AU_IID_EXC_RPT_ROLE.NEXTVAL, S.R_ID, S.ROLE_ID, 'Y', NVL(P_P_NO, 0), SYSDATE);
        END IF;
    END ENSURE_REPORT_ACCESS;

    PROCEDURE P_ADD_NEW_EXP_REPORT(
        P_IND           IN VARCHAR2,
        P_REPORT_ID     IN NUMBER,
        P_REPORT_TITLE  IN VARCHAR2,
        P_DESCRIPTION   IN VARCHAR2,
        P_R_TYPE        IN VARCHAR2,
        P_L_STATUS      IN NUMBER,
        P_P_NO          IN NUMBER,
        P_R_ID          IN NUMBER,
        P_ENT_ID        IN NUMBER,
        IO_CURSOR       OUT T_CURSOR)
    IS
        V_REPORT_ID   NUMBER := NVL(P_REPORT_ID, 0);
        V_SORT_ORDER  NUMBER := 0;
        V_EXISTS      NUMBER := 0;
        V_REMARKS     VARCHAR2(200);
    BEGIN
        IF TRIM(P_REPORT_TITLE) IS NULL THEN
            OPEN IO_CURSOR FOR SELECT 'Report title is required.' AS REMARKS FROM DUAL;
            RETURN;
        END IF;

        IF UPPER(NVL(TRIM(P_IND), 'A')) = 'A' OR V_REPORT_ID <= 0 THEN
            SELECT NVL(MAX(SORT_ORDER), 0) + 1
              INTO V_SORT_ORDER
              FROM T_AU_IID_EXCEPTION_REPORT_HDR;

            V_REPORT_ID := SEQ_T_AU_IID_EXC_RPT_HDR.NEXTVAL;

            INSERT INTO T_AU_IID_EXCEPTION_REPORT_HDR
                (IID_REPORT_ID, REPORT_CODE, REPORT_TITLE, DISCRIPTION, IND, LOAN_STATUS, REPORTING_PERIOD, SORT_ORDER, IS_ACTIVE, CREATED_BY, CREATED_ON)
            VALUES
                (V_REPORT_ID,
                 'IID_EXC_' || TO_CHAR(V_REPORT_ID),
                 TRIM(P_REPORT_TITLE),
                 P_DESCRIPTION,
                 UPPER(NVL(TRIM(P_R_TYPE), 'L')),
                 TO_CHAR(NVL(P_L_STATUS, 0)),
                 NULL,
                 V_SORT_ORDER,
                 'Y',
                 NVL(P_P_NO, 0),
                 SYSDATE);

            ENSURE_REPORT_ACCESS(V_REPORT_ID, P_ENT_ID, P_R_ID, P_P_NO);
            V_REMARKS := 'Report Added';
        ELSE
            SELECT COUNT(*)
              INTO V_EXISTS
              FROM T_AU_IID_EXCEPTION_REPORT_HDR
             WHERE IID_REPORT_ID = V_REPORT_ID;

            IF V_EXISTS = 0 THEN
                OPEN IO_CURSOR FOR SELECT 'Report not found.' AS REMARKS FROM DUAL;
                RETURN;
            END IF;

            UPDATE T_AU_IID_EXCEPTION_REPORT_HDR
               SET REPORT_TITLE = TRIM(P_REPORT_TITLE),
                   DISCRIPTION = P_DESCRIPTION,
                   IND = UPPER(NVL(TRIM(P_R_TYPE), 'L')),
                   LOAN_STATUS = TO_CHAR(NVL(P_L_STATUS, 0)),
                   IS_ACTIVE = 'Y',
                   UPDATED_BY = NVL(P_P_NO, 0),
                   UPDATED_ON = SYSDATE
             WHERE IID_REPORT_ID = V_REPORT_ID;

            ENSURE_REPORT_ACCESS(V_REPORT_ID, P_ENT_ID, P_R_ID, P_P_NO);
            V_REMARKS := 'Report Updated';
        END IF;

        OPEN IO_CURSOR FOR SELECT V_REMARKS AS REMARKS FROM DUAL;
        LOG_RUN('P_ADD_NEW_EXP_REPORT', V_REPORT_ID, NULL, NULL, NULL, NULL, P_P_NO, P_ENT_ID, P_R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_ADD_NEW_EXP_REPORT', V_REPORT_ID, NULL, NULL, NULL, NULL, P_P_NO, P_ENT_ID, P_R_ID, 'FAILED', NULL, SQLERRM);
            OPEN IO_CURSOR FOR SELECT SUBSTR(SQLERRM, 1, 2000) AS REMARKS FROM DUAL;
    END P_ADD_NEW_EXP_REPORT;

    PROCEDURE P_GET_EXCEPTION_REPORT_FORMAT(
        P_R_ID      IN NUMBER,
        IO_CURSOR   OUT T_CURSOR)
    IS
    BEGIN
        OPEN IO_CURSOR FOR
            SELECT FORMAT_ID,
                   R_ID,
                   COLUMN_NAME,
                   COLUMN_HEADER,
                   COLUMN_ORDER,
                   DATA_TYPE,
                   IS_ACTIVE
              FROM T_AU_IID_EXCEPTION_REPORT_FORMAT
             WHERE R_ID = P_R_ID
               AND IS_ACTIVE = 'Y'
             ORDER BY COLUMN_ORDER;

        LOG_RUN('P_GET_EXCEPTION_REPORT_FORMAT', P_R_ID, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_EXCEPTION_REPORT_FORMAT', P_R_ID, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_EXCEPTION_REPORT_FORMAT;

    PROCEDURE P_INSERT_EXCEPTION_REPORT_FORMAT(
        P_R_ID           IN NUMBER,
        P_COLUMN_NAME    IN VARCHAR2,
        P_COLUMN_HEADER  IN VARCHAR2,
        P_COLUMN_ORDER   IN NUMBER,
        P_DATA_TYPE      IN VARCHAR2,
        P_IS_ACTIVE      IN VARCHAR2,
        P_P_NO           IN NUMBER,
        O_FORMAT_ID      OUT NUMBER)
    IS
        V_STATUS CHAR(1) := CASE WHEN UPPER(NVL(TRIM(P_IS_ACTIVE), 'Y')) = 'N' THEN 'N' ELSE 'Y' END;
    BEGIN
        INSERT INTO T_AU_IID_EXCEPTION_REPORT_FORMAT
            (FORMAT_ID, R_ID, COLUMN_NAME, COLUMN_HEADER, COLUMN_ORDER, DATA_TYPE, IS_ACTIVE, CREATED_BY, CREATED_ON)
        VALUES
            (SEQ_T_AU_IID_EXC_RPT_FORMAT.NEXTVAL,
             P_R_ID,
             UPPER(TRIM(P_COLUMN_NAME)),
             TRIM(P_COLUMN_HEADER),
             P_COLUMN_ORDER,
             UPPER(NVL(TRIM(P_DATA_TYPE), 'TEXT')),
             V_STATUS,
             NVL(P_P_NO, 0),
             SYSDATE)
        RETURNING FORMAT_ID INTO O_FORMAT_ID;

        LOG_RUN('P_INSERT_EXCEPTION_REPORT_FORMAT', P_R_ID, NULL, NULL, NULL, NULL, P_P_NO, NULL, NULL, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_INSERT_EXCEPTION_REPORT_FORMAT', P_R_ID, NULL, NULL, NULL, NULL, P_P_NO, NULL, NULL, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_INSERT_EXCEPTION_REPORT_FORMAT;

    PROCEDURE P_UPDATE_EXCEPTION_REPORT_FORMAT(
        P_FORMAT_ID      IN NUMBER,
        P_COLUMN_HEADER  IN VARCHAR2,
        P_COLUMN_ORDER   IN NUMBER,
        P_DATA_TYPE      IN VARCHAR2,
        P_IS_ACTIVE      IN VARCHAR2,
        P_P_NO           IN NUMBER)
    IS
        V_STATUS CHAR(1) := CASE WHEN UPPER(NVL(TRIM(P_IS_ACTIVE), 'Y')) = 'N' THEN 'N' ELSE 'Y' END;
    BEGIN
        IF V_STATUS = 'N' THEN
            DELETE FROM T_AU_IID_EXCEPTION_REPORT_FORMAT
             WHERE FORMAT_ID = P_FORMAT_ID;
        ELSE
            UPDATE T_AU_IID_EXCEPTION_REPORT_FORMAT
               SET COLUMN_HEADER = TRIM(P_COLUMN_HEADER),
                   COLUMN_ORDER = P_COLUMN_ORDER,
                   DATA_TYPE = UPPER(NVL(TRIM(P_DATA_TYPE), 'TEXT')),
                   IS_ACTIVE = V_STATUS,
                   UPDATED_BY = NVL(P_P_NO, 0),
                   UPDATED_ON = SYSDATE
             WHERE FORMAT_ID = P_FORMAT_ID;
        END IF;

        LOG_RUN('P_UPDATE_EXCEPTION_REPORT_FORMAT', NULL, NULL, NULL, NULL, NULL, P_P_NO, NULL, NULL, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_UPDATE_EXCEPTION_REPORT_FORMAT', NULL, NULL, NULL, NULL, NULL, P_P_NO, NULL, NULL, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_UPDATE_EXCEPTION_REPORT_FORMAT;

    PROCEDURE P_GET_EXCEPTION_REPORT_DATA(
        P_R_ID      IN NUMBER,
        P_ENG_ID    IN NUMBER,
        IO_CURSOR1  OUT T_CURSOR,
        IO_CURSOR2  OUT T_CURSOR)
    IS
        V_SOURCE_TYPE  VARCHAR2(20);
        V_SOURCE_NAME  VARCHAR2(200);
        V_SQL          CLOB;
        V_SOURCE_CODE  VARCHAR2(100);
    BEGIN
        OPEN IO_CURSOR1 FOR
            SELECT FORMAT_ID,
                   R_ID,
                   COLUMN_NAME,
                   COLUMN_HEADER,
                   COLUMN_ORDER,
                   DATA_TYPE,
                   IS_ACTIVE
              FROM T_AU_IID_EXCEPTION_REPORT_FORMAT
             WHERE R_ID = P_R_ID
               AND IS_ACTIVE = 'Y'
             ORDER BY COLUMN_ORDER;

        V_SOURCE_CODE := 'REPORT_DATA_' || TO_CHAR(P_R_ID);
        V_SQL := GET_SOURCE_SQL(V_SOURCE_CODE, V_SOURCE_TYPE, V_SOURCE_NAME);

        IF V_SQL IS NULL THEN
            OPEN IO_CURSOR2 FOR
                SELECT NULL AS NO_DATA
                  FROM DUAL
                 WHERE 1 = 0;
        ELSIF V_SOURCE_TYPE IN ('VIEW', 'TABLE') THEN
            OPEN IO_CURSOR2 FOR V_SQL || ' WHERE ENG_ID = :1' USING P_ENG_ID;
        ELSE
            OPEN IO_CURSOR2 FOR V_SQL USING P_ENG_ID;
        END IF;

        LOG_RUN('P_GET_EXCEPTION_REPORT_DATA', P_R_ID, P_ENG_ID, NULL, NULL, NULL, NULL, NULL, NULL, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_EXCEPTION_REPORT_DATA', P_R_ID, P_ENG_ID, NULL, NULL, NULL, NULL, NULL, NULL, 'FAILED', NULL, SQLERRM);
            OPEN IO_CURSOR1 FOR
                SELECT NULL AS FORMAT_ID,
                       NULL AS R_ID,
                       NULL AS COLUMN_NAME,
                       NULL AS COLUMN_HEADER,
                       NULL AS COLUMN_ORDER,
                       NULL AS DATA_TYPE,
                       NULL AS IS_ACTIVE
                  FROM DUAL
                 WHERE 1 = 0;
            OPEN IO_CURSOR2 FOR
                SELECT NULL AS NO_DATA
                  FROM DUAL
                 WHERE 1 = 0;
        END P_GET_EXCEPTION_REPORT_DATA;

    PROCEDURE P_GET_ACCOUNT_TRANSCATIONS(
        E_ID       IN NUMBER,
        AC_NUMBER  IN VARCHAR2,
        P_NO       IN NUMBER,
        R_ID       IN NUMBER,
        ENT_ID     IN NUMBER,
        T_CURSOR   OUT T_CURSOR)
    IS
        V_SOURCE_TYPE VARCHAR2(20);
        V_SOURCE_NAME VARCHAR2(200);
        V_SQL         CLOB;
    BEGIN
        V_SQL := GET_SOURCE_SQL('ACCOUNT_TXN', V_SOURCE_TYPE, V_SOURCE_NAME);
        IF V_SQL IS NULL THEN
            OPEN T_CURSOR FOR SELECT NULL AS TRANSACTIONMASTERCODE FROM DUAL WHERE 1=0;
        ELSIF V_SOURCE_TYPE IN ('VIEW','TABLE') THEN
            OPEN T_CURSOR FOR V_SQL || ' WHERE ENG_ID = :1 AND ACCOUNTNO = :2' USING E_ID, AC_NUMBER;
        ELSE
            OPEN T_CURSOR FOR V_SQL USING E_ID, AC_NUMBER;
        END IF;
        LOG_RUN('P_GET_ACCOUNT_TRANSCATIONS', NULL, E_ID, AC_NUMBER, NULL, NULL, P_NO, ENT_ID, R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_ACCOUNT_TRANSCATIONS', NULL, E_ID, AC_NUMBER, NULL, NULL, P_NO, ENT_ID, R_ID, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_ACCOUNT_TRANSCATIONS;

    PROCEDURE P_GET_ACCOUNT_DOC(
        AC_NUMBER  IN VARCHAR2,
        P_NO       IN NUMBER,
        R_ID       IN NUMBER,
        ENT_ID     IN NUMBER,
        T_CURSOR   OUT T_CURSOR)
    IS
        V_SOURCE_TYPE VARCHAR2(20);
        V_SOURCE_NAME VARCHAR2(200);
        V_SQL         CLOB;
    BEGIN
        V_SQL := GET_SOURCE_SQL('ACCOUNT_DOC', V_SOURCE_TYPE, V_SOURCE_NAME);
        IF V_SQL IS NULL THEN
            OPEN T_CURSOR FOR SELECT NULL AS OLDACCOUNTNO FROM DUAL WHERE 1=0;
        ELSIF V_SOURCE_TYPE IN ('VIEW','TABLE') THEN
            OPEN T_CURSOR FOR V_SQL || ' WHERE OLDACCOUNTNO = :1' USING AC_NUMBER;
        ELSE
            OPEN T_CURSOR FOR V_SQL USING AC_NUMBER;
        END IF;
        LOG_RUN('P_GET_ACCOUNT_DOC', NULL, NULL, AC_NUMBER, NULL, NULL, P_NO, ENT_ID, R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_ACCOUNT_DOC', NULL, NULL, AC_NUMBER, NULL, NULL, P_NO, ENT_ID, R_ID, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_ACCOUNT_DOC;

    PROCEDURE P_GET_LOANS_EXCEPTIONS(
        LSTATUS   IN NUMBER,
        E_ID      IN NUMBER,
        P_NO      IN NUMBER,
        R_ID      IN NUMBER,
        ENT_ID    IN NUMBER,
        T_CURSOR  OUT T_CURSOR)
    IS
        V_SOURCE_TYPE VARCHAR2(20);
        V_SOURCE_NAME VARCHAR2(200);
        V_SQL         CLOB;
    BEGIN
        V_SQL := GET_SOURCE_SQL('LOAN_EXCEPTIONS', V_SOURCE_TYPE, V_SOURCE_NAME);
        IF V_SQL IS NULL THEN
            OPEN T_CURSOR FOR SELECT NULL AS LOAN_DISB_ID FROM DUAL WHERE 1=0;
        ELSIF V_SOURCE_TYPE IN ('VIEW','TABLE') THEN
            OPEN T_CURSOR FOR V_SQL || ' WHERE ENG_ID = :1 AND NVL(TO_NUMBER(LOAN_STATUS_ID),-1) = :2' USING E_ID, LSTATUS;
        ELSE
            OPEN T_CURSOR FOR V_SQL USING E_ID, LSTATUS;
        END IF;
        LOG_RUN('P_GET_LOANS_EXCEPTIONS', NULL, E_ID, NULL, NULL, NULL, P_NO, ENT_ID, R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_LOANS_EXCEPTIONS', NULL, E_ID, NULL, NULL, NULL, P_NO, ENT_ID, R_ID, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_LOANS_EXCEPTIONS;

    PROCEDURE P_GET_LOAN_DOCUMENTS(
        E_ID       IN VARCHAR2,
        L_DISB_ID  IN VARCHAR2,
        P_NO       IN NUMBER,
        ENT_ID     IN NUMBER,
        R_ID       IN NUMBER,
        T_CURSOR   OUT T_CURSOR)
    IS
        V_SOURCE_TYPE VARCHAR2(20);
        V_SOURCE_NAME VARCHAR2(200);
        V_SQL         CLOB;
    BEGIN
        V_SQL := GET_SOURCE_SQL('LOAN_DOC', V_SOURCE_TYPE, V_SOURCE_NAME);
        IF V_SQL IS NULL THEN
            OPEN T_CURSOR FOR SELECT NULL AS IMAGEID FROM DUAL WHERE 1=0;
        ELSIF V_SOURCE_TYPE IN ('VIEW','TABLE') THEN
            OPEN T_CURSOR FOR V_SQL || ' WHERE ENG_ID = :1 AND LOAN_DISB_ID = :2' USING E_ID, L_DISB_ID;
        ELSE
            OPEN T_CURSOR FOR V_SQL USING E_ID, L_DISB_ID;
        END IF;
        LOG_RUN('P_GET_LOAN_DOCUMENTS', NULL, TO_NUMBER(E_ID), NULL, L_DISB_ID, NULL, P_NO, ENT_ID, R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_LOAN_DOCUMENTS', NULL, NULL, NULL, L_DISB_ID, NULL, P_NO, ENT_ID, R_ID, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_LOAN_DOCUMENTS;

    PROCEDURE P_GET_LOAN_DOCUMENTS_IMAGE(
        IMAGE_ID  IN VARCHAR2,
        T_CURSOR  OUT T_CURSOR)
    IS
        V_SOURCE_TYPE VARCHAR2(20);
        V_SOURCE_NAME VARCHAR2(200);
        V_SQL         CLOB;
    BEGIN
        V_SQL := GET_SOURCE_SQL('LOAN_DOC_IMAGE', V_SOURCE_TYPE, V_SOURCE_NAME);
        IF V_SQL IS NULL THEN
            OPEN T_CURSOR FOR SELECT NULL AS IMAGEDATA FROM DUAL WHERE 1=0;
        ELSIF V_SOURCE_TYPE IN ('VIEW','TABLE') THEN
            OPEN T_CURSOR FOR V_SQL || ' WHERE IMAGEID = :1' USING IMAGE_ID;
        ELSE
            OPEN T_CURSOR FOR V_SQL USING IMAGE_ID;
        END IF;
        LOG_RUN('P_GET_LOAN_DOCUMENTS_IMAGE', NULL, NULL, NULL, NULL, TO_NUMBER(IMAGE_ID), NULL, NULL, NULL, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_LOAN_DOCUMENTS_IMAGE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_LOAN_DOCUMENTS_IMAGE;

    PROCEDURE P_GET_LOAN_TRANSACTIONS(
        E_ID       IN VARCHAR2,
        L_DISB_ID  IN VARCHAR2,
        P_NO       IN NUMBER,
        ENT_ID     IN NUMBER,
        R_ID       IN NUMBER,
        T_CURSOR   OUT T_CURSOR)
    IS
        V_SOURCE_TYPE VARCHAR2(20);
        V_SOURCE_NAME VARCHAR2(200);
        V_SQL         CLOB;
    BEGIN
        V_SQL := GET_SOURCE_SQL('LOAN_TXN', V_SOURCE_TYPE, V_SOURCE_NAME);
        IF V_SQL IS NULL THEN
            OPEN T_CURSOR FOR SELECT NULL AS DESCRIPTION FROM DUAL WHERE 1=0;
        ELSIF V_SOURCE_TYPE IN ('VIEW','TABLE') THEN
            OPEN T_CURSOR FOR V_SQL || ' WHERE ENG_ID = :1 AND LOAN_DISB_ID = :2' USING E_ID, L_DISB_ID;
        ELSE
            OPEN T_CURSOR FOR V_SQL USING E_ID, L_DISB_ID;
        END IF;
        LOG_RUN('P_GET_LOAN_TRANSACTIONS', NULL, TO_NUMBER(E_ID), NULL, L_DISB_ID, NULL, P_NO, ENT_ID, R_ID, 'SUCCESS', NULL, NULL);
    EXCEPTION
        WHEN OTHERS THEN
            LOG_RUN('P_GET_LOAN_TRANSACTIONS', NULL, NULL, NULL, L_DISB_ID, NULL, P_NO, ENT_ID, R_ID, 'FAILED', NULL, SQLERRM);
            RAISE;
    END P_GET_LOAN_TRANSACTIONS;

END PKG_ISM;
/
