/* Deployment configuration. Change these values without modifying package code. */
DEFINE MGMT_WEEKLY_SCHEDULE = 'FREQ=WEEKLY;BYDAY=MON;BYHOUR=07;BYMINUTE=00;BYSECOND=00'
DEFINE MGMT_MAPPING_EXCEPTION_SCHEDULE = 'FREQ=WEEKLY;BYDAY=FRI;BYHOUR=07;BYMINUTE=00;BYSECOND=00'
DEFINE IAS_NOTIFICATION_HEALTH_SCHEDULE = 'FREQ=DAILY;BYHOUR=08;BYMINUTE=00;BYSECOND=00'
