/*
  Management Audit para notifications
  Date: 2026-09-25

  Scope:
  - Management Audit only: AIS_T_AU_POST_COMPLIANCE.AUDITED_BY IN (112242, 112248)
  - Weekly consolidated settled/rejected para notification
  - Uses existing IAS queue: PKG_INQ.P_ENQUEUE_EMAIL / T_AU_IID_EMAIL_QUEUE
  - No employee email addresses are hard-coded
*/

SET DEFINE OFF;

--------------------------------------------------------------------------------
-- Duplicate-run prevention for weekly consolidated notifications.
--------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE T_AU_MGMT_AUDIT_WEEKLY_NOTIFY_LOG
    (
      LOG_ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      PERIOD_START_DATE       DATE NOT NULL,
      PERIOD_END_DATE         DATE NOT NULL,
      GROUP_HEAD_ENTITY_ID    NUMBER,
      DIV_HEAD_ENTITY_ID      NUMBER,
      EMAIL_ID                NUMBER,
      CREATED_ON              DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_MGMT_AUDIT_WEEKLY_NOTIFY_LOG PRIMARY KEY (LOG_ID),
      CONSTRAINT UQ_MGMT_AUDIT_WEEKLY_NOTIFY UNIQUE
        (PERIOD_START_DATE, PERIOD_END_DATE, GROUP_HEAD_ENTITY_ID, DIV_HEAD_ENTITY_ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

--------------------------------------------------------------------------------
-- Weekly consolidated Management Audit notification.
--
-- Usage examples:
--   BEGIN P_SEND_MGMT_AUDIT_WEEKLY_NOTIFY(TRUNC(SYSDATE)-7, TRUNC(SYSDATE)); END;
--   BEGIN P_SEND_MGMT_AUDIT_WEEKLY_NOTIFY; END;
--
-- P_FROM_DATE is inclusive; P_TO_DATE is inclusive.
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE P_SEND_MGMT_AUDIT_WEEKLY_NOTIFY
(
  P_FROM_DATE IN DATE DEFAULT TRUNC(SYSDATE) - 7,
  P_TO_DATE   IN DATE DEFAULT TRUNC(SYSDATE) - 1
) IS
  C_EVENT_CODE CONSTANT VARCHAR2(50) := 'MGMT_AUDIT_WEEKLY_PARA_STATUS';
  C_HEADER     CONSTANT VARCHAR2(100) := 'Internal Audit System (IAS)';
  C_FOOTER     CONSTANT VARCHAR2(500) := 'This is a system-generated notification from Internal Audit System (IAS). Please do not reply unless required under official process.';

  V_START_DATE DATE := TRUNC(NVL(P_FROM_DATE, TRUNC(SYSDATE) - 7));
  V_END_DATE   DATE := TRUNC(NVL(P_TO_DATE, TRUNC(SYSDATE) - 1));
  V_BODY       CLOB;
  V_SETTLED    CLOB;
  V_REJECTED   CLOB;
  V_EMAIL_ID   NUMBER;
  V_SETTLED_N  NUMBER;
  V_REJECTED_N NUMBER;

  FUNCTION ESC(P_VALUE VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NVL(P_VALUE, ''), '&', '&amp;'), '<', '&lt;'), '>', '&gt;'), '"', '&quot;'), '''', '&#39;');
  END;

  FUNCTION TD(P_VALUE VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN TO_CLOB('<td style="padding:8px 10px;border-bottom:1px solid #d9e2ec;font-size:12px;color:#334e68;vertical-align:top;">') ||
           ESC(P_VALUE) || '</td>';
  END;

  FUNCTION TH(P_VALUE VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN TO_CLOB('<th align="left" style="padding:9px 10px;background-color:#eef2f6;border-bottom:1px solid #d9e2ec;font-size:12px;color:#243b53;">') ||
           ESC(P_VALUE) || '</th>';
  END;

  FUNCTION SECTION_TITLE(P_VALUE VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN TO_CLOB('<tr><td style="padding:20px 28px 8px 28px;font-size:16px;font-weight:bold;color:#102a43;">') ||
           ESC(P_VALUE) || '</td></tr>';
  END;

  FUNCTION TABLE_WRAP(P_ROWS CLOB) RETURN CLOB IS
  BEGIN
    RETURN TO_CLOB('<tr><td style="padding:0 28px 18px 28px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:100%;border:1px solid #d9e2ec;">') ||
           P_ROWS || '</table></td></tr>';
  END;

  FUNCTION FORMAT_DATE(P_VALUE DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN P_VALUE IS NULL THEN '' ELSE TO_CHAR(P_VALUE, 'DD-MON-YYYY') END;
  END;

BEGIN
  IF V_END_DATE < V_START_DATE THEN
    RAISE_APPLICATION_ERROR(-20601, 'P_TO_DATE cannot be earlier than P_FROM_DATE.');
  END IF;

  FOR RCP IN (
    SELECT DISTINCT
           NVL(G.ENTITY_ID, D.ENTITY_ID) AS GROUP_HEAD_ENTITY_ID,
           D.ENTITY_ID AS DIV_HEAD_ENTITY_ID,
           NVL(G.EMAIL_ADDRESS, D.EMAIL_ADDRESS) AS MAIL_TO,
           CASE WHEN G.ENTITY_ID IS NULL THEN NULL ELSE D.EMAIL_ADDRESS END AS MAIL_CC,
           NVL(G.NAME, D.NAME) AS GROUP_HEAD_NAME,
           D.NAME AS DIV_HEAD_NAME
      FROM AIS_T_AU_POST_COMPLIANCE PC
      JOIN AIS_T_AU_POST_COMPLIANCE_HISTORY H
        ON H.COM_ID = PC.COM_ID
      JOIN T_AUDITEE_ENTITIES_MAPING M
        ON M.ENTITY_ID = PC.ENTITY_ID
      JOIN T_AUDITEE_ENTITIES D
        ON D.ENTITY_ID = M.PARENT_ID
      LEFT JOIN T_AUDITEE_ENTITIES_MAPING GM
        ON GM.ENTITY_ID = D.ENTITY_ID
      LEFT JOIN T_AUDITEE_ENTITIES G
        ON G.ENTITY_ID = GM.PARENT_ID
     WHERE PC.AUDITED_BY IN (112242, 112248)
       AND H.COM_STATUS IN (16, 12, 15, 18)
       AND H.COMMENT_ON >= V_START_DATE
       AND H.COMMENT_ON < V_END_DATE + 1
       AND NOT EXISTS (
             SELECT 1
               FROM T_AU_MGMT_AUDIT_WEEKLY_NOTIFY_LOG L
              WHERE L.PERIOD_START_DATE = V_START_DATE
                AND L.PERIOD_END_DATE = V_END_DATE
                AND NVL(L.GROUP_HEAD_ENTITY_ID, -1) = NVL(NVL(G.ENTITY_ID, D.ENTITY_ID), -1)
                AND NVL(L.DIV_HEAD_ENTITY_ID, -1) = NVL(D.ENTITY_ID, -1))
       AND TRIM(NVL(G.EMAIL_ADDRESS, D.EMAIL_ADDRESS)) IS NOT NULL
  ) LOOP
    V_SETTLED := TH('Sr.') || TH('Entity') || TH('Audit Year') || TH('Para No.') ||
                 TH('Title') || TH('Compliance Submitted On') || TH('Decision On');
    V_REJECTED := V_SETTLED || TH('Reason');
    V_SETTLED_N := 0;
    V_REJECTED_N := 0;

    FOR DCS IN (
      SELECT E.NAME AS ENTITY_NAME,
             PC.AUDIT_PERIOD,
             PC.PARA_NO,
             PC.GIST_OF_PARAS AS TITLE,
             (SELECT MAX(S.COMMENT_ON)
                FROM AIS_T_AU_POST_COMPLIANCE_HISTORY S
               WHERE S.COM_ID = H.COM_ID
                 AND S.COM_CYCLE = H.COM_CYCLE
                 AND S.COM_STATUS = 10
                 AND S.COMMENT_ON <= H.COMMENT_ON) AS COMPLIANCE_SUBMITTED_ON,
             H.COMMENT_ON AS DECISION_ON,
             H.COMMENTS AS REASON,
             H.COM_STATUS
        FROM AIS_T_AU_POST_COMPLIANCE PC
        JOIN AIS_T_AU_POST_COMPLIANCE_HISTORY H
          ON H.COM_ID = PC.COM_ID
        JOIN T_AUDITEE_ENTITIES E
          ON E.ENTITY_ID = PC.ENTITY_ID
        JOIN T_AUDITEE_ENTITIES_MAPING M
          ON M.ENTITY_ID = PC.ENTITY_ID
        JOIN T_AUDITEE_ENTITIES D
          ON D.ENTITY_ID = M.PARENT_ID
        LEFT JOIN T_AUDITEE_ENTITIES_MAPING GM
          ON GM.ENTITY_ID = D.ENTITY_ID
        LEFT JOIN T_AUDITEE_ENTITIES G
          ON G.ENTITY_ID = GM.PARENT_ID
       WHERE PC.AUDITED_BY IN (112242, 112248)
         AND H.COM_STATUS IN (16, 12, 15, 18)
         AND H.COMMENT_ON >= V_START_DATE
         AND H.COMMENT_ON < V_END_DATE + 1
         AND NVL(NVL(G.ENTITY_ID, D.ENTITY_ID), -1) = NVL(RCP.GROUP_HEAD_ENTITY_ID, -1)
         AND NVL(D.ENTITY_ID, -1) = NVL(RCP.DIV_HEAD_ENTITY_ID, -1)
       ORDER BY H.COMMENT_ON, E.NAME, PC.PARA_NO, H.HIST_ID
    ) LOOP
      IF DCS.COM_STATUS = 16 THEN
        V_SETTLED_N := V_SETTLED_N + 1;
        V_SETTLED := V_SETTLED || TO_CLOB('<tr>') ||
          TD(TO_CHAR(V_SETTLED_N)) || TD(DCS.ENTITY_NAME) || TD(DCS.AUDIT_PERIOD) ||
          TD(DCS.PARA_NO) || TD(DCS.TITLE) || TD(FORMAT_DATE(DCS.COMPLIANCE_SUBMITTED_ON)) ||
          TD(FORMAT_DATE(DCS.DECISION_ON)) || '</tr>';
      ELSE
        V_REJECTED_N := V_REJECTED_N + 1;
        V_REJECTED := V_REJECTED || TO_CLOB('<tr>') ||
          TD(TO_CHAR(V_REJECTED_N)) || TD(DCS.ENTITY_NAME) || TD(DCS.AUDIT_PERIOD) ||
          TD(DCS.PARA_NO) || TD(DCS.TITLE) || TD(FORMAT_DATE(DCS.COMPLIANCE_SUBMITTED_ON)) ||
          TD(FORMAT_DATE(DCS.DECISION_ON)) || TD(DCS.REASON) || '</tr>';
      END IF;
    END LOOP;

    IF V_SETTLED_N = 0 AND V_REJECTED_N = 0 THEN
      CONTINUE;
    END IF;

    IF V_SETTLED_N = 0 THEN
      V_SETTLED := V_SETTLED || TO_CLOB('<tr>') || TD('-') || TD('No settled paras for this reporting period.') ||
                   TD('') || TD('') || TD('') || TD('') || TD('') || '</tr>';
    END IF;

    IF V_REJECTED_N = 0 THEN
      V_REJECTED := V_REJECTED || TO_CLOB('<tr>') || TD('-') || TD('No rejected paras for this reporting period.') ||
                    TD('') || TD('') || TD('') || TD('') || TD('') || TD('') || '</tr>';
    END IF;

    V_BODY := TO_CLOB('<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body style="margin:0;padding:0;background-color:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#1f2933;">') ||
      '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#f4f6f8;padding:24px 0;"><tr><td align="center">' ||
      '<table role="presentation" width="760" cellspacing="0" cellpadding="0" style="width:760px;max-width:760px;background-color:#ffffff;border-collapse:collapse;border:1px solid #d9e2ec;">' ||
      '<tr><td style="padding:18px 28px;background-color:#173f5f;color:#ffffff;font-size:20px;font-weight:bold;">' || ESC(C_HEADER) || '</td></tr>' ||
      '<tr><td style="padding:28px 28px 10px 28px;font-size:22px;font-weight:bold;color:#102a43;">Weekly Management Audit Para Decisions</td></tr>' ||
      '<tr><td style="padding:0 28px 12px 28px;font-size:14px;line-height:1.7;color:#334e68;">Reporting period: ' ||
      ESC(FORMAT_DATE(V_START_DATE)) || ' to ' || ESC(FORMAT_DATE(V_END_DATE)) ||
      '<br />Group Head: ' || ESC(RCP.GROUP_HEAD_NAME) || '<br />Divisional Head: ' || ESC(RCP.DIV_HEAD_NAME) || '</td></tr>' ||
      SECTION_TITLE('SETTLED PARAS') || TABLE_WRAP(V_SETTLED) ||
      SECTION_TITLE('REJECTED PARAS') || TABLE_WRAP(V_REJECTED) ||
      '<tr><td style="padding:18px 28px;background-color:#f8fafc;border-top:1px solid #d9e2ec;font-size:12px;line-height:1.6;color:#52606d;">' || ESC(C_FOOTER) || '</td></tr>' ||
      '</table></td></tr></table></body></html>';

    PKG_INQ.P_ENQUEUE_EMAIL(
      C_EVENT_CODE,
      RCP.GROUP_HEAD_ENTITY_ID,
      RCP.DIV_HEAD_ENTITY_ID,
      RCP.MAIL_TO,
      RCP.MAIL_CC,
      'IAS Notification: Weekly Management Audit Para Decisions (' || FORMAT_DATE(V_START_DATE) || ' to ' || FORMAT_DATE(V_END_DATE) || ')',
      V_BODY,
      V_EMAIL_ID);

    INSERT INTO T_AU_MGMT_AUDIT_WEEKLY_NOTIFY_LOG
      (PERIOD_START_DATE, PERIOD_END_DATE, GROUP_HEAD_ENTITY_ID, DIV_HEAD_ENTITY_ID, EMAIL_ID)
    VALUES
      (V_START_DATE, V_END_DATE, RCP.GROUP_HEAD_ENTITY_ID, RCP.DIV_HEAD_ENTITY_ID, V_EMAIL_ID);

    COMMIT;
  END LOOP;
END P_SEND_MGMT_AUDIT_WEEKLY_NOTIFY;
/

