/* Management Audit para notifications - production deployment.
   Run with SQL*Plus from AIS/Docs/sql so @@ includes resolve correctly. */
SET SERVEROUTPUT ON;
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT === Preflight: central architecture and recipient evidence ===
DECLARE
  V_OBJECTS NUMBER; V_ACTIVE NUMBER; V_MAPPED NUMBER; V_CONFLICTS NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_OBJECTS FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('IAS_NOTIFICATION_MASTER','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY') AND STATUS='VALID';
  SELECT COUNT(*) INTO V_ACTIVE FROM IAS_NOTIFICATION_MASTER
   WHERE NOTIFICATION_CODE='PARA_STATUS_UPDATED' AND IS_ACTIVE='Y';
  IF V_OBJECTS<>4 OR V_ACTIVE<>1 THEN
    RAISE_APPLICATION_ERROR(-20801,'Central IAS notification architecture is not active; deployment stopped.');
  END IF;
  SELECT COUNT(*) INTO V_MAPPED FROM (
    SELECT DISTINCT E.ENTITY_ID FROM T_AUDITEE_ENTITIES E
    JOIN T_AUDITEE_ENTITIES_MAPING M ON M.ENTITY_ID=E.ENTITY_ID
    JOIN T_AUDITEE_ENTITIES D ON D.ENTITY_ID=M.DIV_OFFICE
    JOIN T_AUDITEE_ENTITIES G ON G.ENTITY_ID=M.B_GROUP
    WHERE E.AUDITBY_ID IN (112242,112248)
      AND TRIM(D.EMAIL_ADDRESS) IS NOT NULL AND TRIM(G.EMAIL_ADDRESS) IS NOT NULL);
  IF V_MAPPED<3 THEN RAISE_APPLICATION_ERROR(-20802,'Fewer than three Management Audit entities have explicit Division/Group recipient mappings.'); END IF;
  SELECT COUNT(*) INTO V_CONFLICTS FROM (
    SELECT M.ENTITY_ID FROM T_AUDITEE_ENTITIES_MAPING M
    JOIN T_AUDITEE_ENTITIES E ON E.ENTITY_ID=M.ENTITY_ID
    WHERE E.AUDITBY_ID IN (112242,112248)
    GROUP BY M.ENTITY_ID
    HAVING COUNT(DISTINCT TO_CHAR(M.DIV_OFFICE)||':'||TO_CHAR(M.B_GROUP))>1);
  IF V_CONFLICTS>0 THEN RAISE_APPLICATION_ERROR(-20803,'Conflicting DIV_OFFICE/B_GROUP mappings exist; deployment stopped.'); END IF;
  DBMS_OUTPUT.PUT_LINE('Verified deployed central architecture and explicit recipient mappings.');
  FOR R IN (
    SELECT * FROM (
      SELECT DISTINCT E.ENTITY_ID,E.NAME ENTITY_NAME,D.ENTITY_ID DIVISION_ID,D.NAME DIVISION_NAME,
             D.EMAIL_ADDRESS DIVISION_EMAIL,G.ENTITY_ID GROUP_ID,G.NAME GROUP_NAME,G.EMAIL_ADDRESS GROUP_EMAIL
      FROM T_AUDITEE_ENTITIES E
      JOIN T_AUDITEE_ENTITIES_MAPING M ON M.ENTITY_ID=E.ENTITY_ID
      JOIN T_AUDITEE_ENTITIES D ON D.ENTITY_ID=M.DIV_OFFICE
      JOIN T_AUDITEE_ENTITIES G ON G.ENTITY_ID=M.B_GROUP
      WHERE E.AUDITBY_ID IN (112242,112248)
        AND TRIM(D.EMAIL_ADDRESS) IS NOT NULL AND TRIM(G.EMAIL_ADDRESS) IS NOT NULL
      ORDER BY E.ENTITY_ID) WHERE ROWNUM<=3
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Entity ['||R.ENTITY_ID||'] '||R.ENTITY_NAME||' -> Division ['||R.DIVISION_ID||'] '||
      R.DIVISION_NAME||' <'||R.DIVISION_EMAIL||'> -> Group ['||R.GROUP_ID||'] '||R.GROUP_NAME||' <'||R.GROUP_EMAIL||'>');
  END LOOP;
END;
/

PROMPT === Compile central notification package and PKG_AE integration ===
@@ias_notification_centralization.sql
@@PKG_AE.sql

DECLARE
  V_INVALID NUMBER; V_ERRORS NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_INVALID FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY') AND STATUS<>'VALID';
  SELECT COUNT(*) INTO V_ERRORS FROM USER_ERRORS WHERE NAME IN ('PKG_AE','PKG_IAS_NOTIFICATION');
  IF V_INVALID>0 OR V_ERRORS>0 THEN
    RAISE_APPLICATION_ERROR(-20804,'Notification object compilation failed; inspect USER_ERRORS.');
  END IF;
END;
/

PROMPT === Queue-level weekly idempotency ===
BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UQ_IID_EMAIL_MGMT_WEEKLY ON T_AU_IID_EMAIL_QUEUE
    (CASE WHEN EVENT_CODE='MGMT_AUDIT_WEEKLY_PARA_STATUS' THEN EVENT_CODE END,
     CASE WHEN EVENT_CODE='MGMT_AUDIT_WEEKLY_PARA_STATUS' THEN REF_ID1 END,
     CASE WHEN EVENT_CODE='MGMT_AUDIT_WEEKLY_PARA_STATUS' THEN REF_ID2 END)~';
EXCEPTION WHEN OTHERS THEN IF SQLCODE<>-955 THEN RAISE; END IF;
END;
/

PROMPT === Scheduler: Mondays 07:00 database-server time ===
DECLARE
  V_COUNT NUMBER;
  V_START TIMESTAMP WITH TIME ZONE := TRUNC(SYSTIMESTAMP,'IW') + INTERVAL '7' DAY + INTERVAL '7' HOUR;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_SCHEDULER_JOBS WHERE JOB_NAME='JOB_MGMT_AUDIT_WEEKLY_NOTIFY';
  IF V_COUNT=0 THEN
    DBMS_SCHEDULER.CREATE_JOB(JOB_NAME=>'JOB_MGMT_AUDIT_WEEKLY_NOTIFY',JOB_TYPE=>'PLSQL_BLOCK',
      JOB_ACTION=>'BEGIN PKG_IAS_NOTIFICATION.SEND_MGMT_AUDIT_WEEKLY; END;',START_DATE=>V_START,
      REPEAT_INTERVAL=>'FREQ=WEEKLY;BYDAY=MON;BYHOUR=07;BYMINUTE=00;BYSECOND=00',ENABLED=>TRUE,AUTO_DROP=>FALSE,
      COMMENTS=>'Queues the previous Monday-Sunday Management Audit settled/rejected digest.');
  ELSE
    DBMS_SCHEDULER.DISABLE('JOB_MGMT_AUDIT_WEEKLY_NOTIFY',FORCE=>TRUE);
    DBMS_SCHEDULER.SET_ATTRIBUTE('JOB_MGMT_AUDIT_WEEKLY_NOTIFY','job_action','BEGIN PKG_IAS_NOTIFICATION.SEND_MGMT_AUDIT_WEEKLY; END;');
    DBMS_SCHEDULER.SET_ATTRIBUTE('JOB_MGMT_AUDIT_WEEKLY_NOTIFY','repeat_interval','FREQ=WEEKLY;BYDAY=MON;BYHOUR=07;BYMINUTE=00;BYSECOND=00');
    DBMS_SCHEDULER.ENABLE('JOB_MGMT_AUDIT_WEEKLY_NOTIFY');
  END IF;
END;
/

PROMPT === Remove obsolete standalone tracking table after successful deployment ===
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE T_AU_MGMT_AUDIT_WEEKLY_NOTIFY_LOG';
EXCEPTION WHEN OTHERS THEN IF SQLCODE<>-942 THEN RAISE; END IF;
END;
/

PROMPT === Compilation and scheduler verification ===
SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY') ORDER BY OBJECT_NAME,OBJECT_TYPE;
SELECT NAME,TYPE,LINE,POSITION,TEXT FROM USER_ERRORS
 WHERE NAME IN ('PKG_AE','PKG_IAS_NOTIFICATION') ORDER BY NAME,SEQUENCE;
SELECT JOB_NAME,ENABLED,STATE,REPEAT_INTERVAL,NEXT_RUN_DATE FROM USER_SCHEDULER_JOBS
 WHERE JOB_NAME='JOB_MGMT_AUDIT_WEEKLY_NOTIFY';
