/* Management Audit para notifications - production deployment.
   Run with SQL*Plus from AIS/Docs/sql so @@ includes resolve correctly. */
SET SERVEROUTPUT ON;
SET DEFINE ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

@@management_audit_notification_schedule_config.sql

PROMPT === Preflight: production central architecture and recipient evidence ===
DECLARE
  V_MASTER NUMBER; V_PACKAGE NUMBER; V_QUEUE_API NUMBER; V_MAPPED NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_MASTER FROM USER_OBJECTS
   WHERE OBJECT_NAME='IAS_NOTIFICATION_MASTER' AND OBJECT_TYPE='TABLE' AND STATUS='VALID';
  SELECT COUNT(*) INTO V_PACKAGE FROM USER_OBJECTS
   WHERE OBJECT_NAME='PKG_IAS_NOTIFICATION' AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY') AND STATUS='VALID';
  SELECT COUNT(*) INTO V_QUEUE_API FROM USER_PROCEDURES
   WHERE OBJECT_NAME='PKG_INQ' AND PROCEDURE_NAME='P_ENQUEUE_EMAIL';
  IF V_MASTER<>1 OR V_PACKAGE<>2 OR V_QUEUE_API<>1 THEN
    RAISE_APPLICATION_ERROR(-20801,'IAS_NOTIFICATION_MASTER / PKG_IAS_NOTIFICATION / PKG_INQ queue architecture is not active.');
  END IF;

  SELECT COUNT(*) INTO V_MAPPED FROM (
    SELECT DISTINCT E.ENTITY_ID
      FROM T_AUDITEE_ENTITIES E
      JOIN T_AUDITEE_ENTITIES_MAPING M ON M.ENTITY_ID=E.ENTITY_ID
      JOIN T_AUDITEE_ENTITIES D ON D.ENTITY_ID=M.DIV_OFFICE
      JOIN T_AUDITEE_ENTITIES R ON R.ENTITY_ID=NVL(M.REPORTING,M.B_GROUP)
     WHERE E.AUDITBY_ID IN (112242,112248)
       AND TRIM(D.EMAIL_ADDRESS) IS NOT NULL AND TRIM(R.EMAIL_ADDRESS) IS NOT NULL);
  IF V_MAPPED<3 THEN
    RAISE_APPLICATION_ERROR(-20802,'Fewer than three Management Audit entities have demonstrable Division/Reporting recipient mappings.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('Confirmed central master/package/queue architecture.');
  FOR R IN (
    SELECT * FROM (
      SELECT DISTINCT E.ENTITY_ID,E.NAME ENTITY_NAME,D.ENTITY_ID DIVISION_ID,D.NAME DIVISION_NAME,
             D.EMAIL_ADDRESS DIVISION_EMAIL,RPT.ENTITY_ID REPORTING_ID,RPT.NAME REPORTING_NAME,
             RPT.EMAIL_ADDRESS REPORTING_EMAIL
        FROM T_AUDITEE_ENTITIES E
        JOIN T_AUDITEE_ENTITIES_MAPING M ON M.ENTITY_ID=E.ENTITY_ID
        JOIN T_AUDITEE_ENTITIES D ON D.ENTITY_ID=M.DIV_OFFICE
        JOIN T_AUDITEE_ENTITIES RPT ON RPT.ENTITY_ID=NVL(M.REPORTING,M.B_GROUP)
       WHERE E.AUDITBY_ID IN (112242,112248)
         AND TRIM(D.EMAIL_ADDRESS) IS NOT NULL AND TRIM(RPT.EMAIL_ADDRESS) IS NOT NULL
       ORDER BY E.ENTITY_ID) WHERE ROWNUM<=3
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Entity ['||R.ENTITY_ID||'] '||R.ENTITY_NAME||' -> Division ['||R.DIVISION_ID||'] '||
      R.DIVISION_NAME||' <'||R.DIVISION_EMAIL||'> -> Reporting/Group ['||R.REPORTING_ID||'] '||
      R.REPORTING_NAME||' <'||R.REPORTING_EMAIL||'>');
  END LOOP;
END;
/

PROMPT === Compile queue contract, central package and transaction integration ===
@@PKG_INQ.sql
@@ias_notification_centralization.sql
@@PKG_AE.sql

DECLARE
  V_INVALID NUMBER; V_ERRORS NUMBER; V_STATUS_TYPE VARCHAR2(30);
BEGIN
  SELECT COUNT(*) INTO V_INVALID FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('PKG_INQ','PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP')
     AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY','VIEW') AND STATUS<>'VALID';
  SELECT COUNT(*) INTO V_ERRORS FROM USER_ERRORS
   WHERE NAME IN ('PKG_INQ','PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP');
  SELECT DATA_TYPE INTO V_STATUS_TYPE FROM USER_ARGUMENTS
   WHERE PACKAGE_NAME='PKG_INQ' AND OBJECT_NAME='P_GET_EMAIL_QUEUE'
     AND ARGUMENT_NAME='P_STATUS' AND DATA_LEVEL=0;
  IF V_INVALID>0 OR V_ERRORS>0 OR V_STATUS_TYPE<>'VARCHAR2' THEN
    RAISE_APPLICATION_ERROR(-20804,'Notification compilation or P_GET_EMAIL_QUEUE VARCHAR2 contract validation failed.');
  END IF;
END;
/

PROMPT === Queue-level idempotency; failed rows remain the retryable source of truth ===
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UQ_IID_EMAIL_MGMT_WEEKLY';
EXCEPTION WHEN OTHERS THEN IF SQLCODE<>-1418 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UQ_IID_EMAIL_SCHED_NOTIFY';
EXCEPTION WHEN OTHERS THEN IF SQLCODE<>-1418 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UQ_IID_EMAIL_SCHED_NOTIFY ON T_AU_IID_EMAIL_QUEUE
    (CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH') THEN EVENT_CODE END,
     CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH') THEN REF_ID1 END,
     CASE WHEN EVENT_CODE IN ('MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION','IAS_NOTIFICATION_HEALTH') THEN NVL(REF_ID2,-1) END)~';
END;
/

PROMPT === Configured scheduler jobs ===
SET DEFINE ON;
DECLARE
  PROCEDURE UPSERT_JOB(P_NAME VARCHAR2,P_ACTION VARCHAR2,P_SCHEDULE VARCHAR2,P_COMMENTS VARCHAR2) IS
    V_COUNT NUMBER; V_START TIMESTAMP WITH TIME ZONE;
  BEGIN
    DBMS_SCHEDULER.EVALUATE_CALENDAR_STRING(P_SCHEDULE,SYSTIMESTAMP,SYSTIMESTAMP,V_START);
    SELECT COUNT(*) INTO V_COUNT FROM USER_SCHEDULER_JOBS WHERE JOB_NAME=UPPER(P_NAME);
    IF V_COUNT=0 THEN
      DBMS_SCHEDULER.CREATE_JOB(JOB_NAME=>P_NAME,JOB_TYPE=>'PLSQL_BLOCK',JOB_ACTION=>P_ACTION,
        START_DATE=>V_START,REPEAT_INTERVAL=>P_SCHEDULE,ENABLED=>TRUE,AUTO_DROP=>FALSE,COMMENTS=>P_COMMENTS);
    ELSE
      DBMS_SCHEDULER.DISABLE(P_NAME,FORCE=>TRUE);
      DBMS_SCHEDULER.SET_ATTRIBUTE(P_NAME,'job_action',P_ACTION);
      DBMS_SCHEDULER.SET_ATTRIBUTE(P_NAME,'repeat_interval',P_SCHEDULE);
      DBMS_SCHEDULER.SET_ATTRIBUTE(P_NAME,'comments',P_COMMENTS);
      DBMS_SCHEDULER.ENABLE(P_NAME);
    END IF;
  END;
BEGIN
  FOR R IN (
    SELECT JOB_NAME FROM USER_SCHEDULER_JOBS
     WHERE JOB_NAME='JOB_MGMT_AUDIT_WEEKLY_NOTIFY'
        OR UPPER(JOB_ACTION) LIKE '%SEND_MGMT_AUDIT_WEEKLY%'
  ) LOOP
    DBMS_SCHEDULER.DROP_JOB(R.JOB_NAME,FORCE=>TRUE);
  END LOOP;
  UPSERT_JOB('JOB_MGMT_AUDIT_MAPPING_EXCEPT','BEGIN PKG_IAS_NOTIFICATION.SEND_MGMT_AUDIT_MAPPING_EXCEPTIONS; END;',
    '&MGMT_MAPPING_EXCEPTION_SCHEDULE','Queues Friday mapping exceptions separately for heads 112242 and 112248.');
  UPSERT_JOB('JOB_IAS_NOTIFICATION_HEALTH','BEGIN PKG_IAS_NOTIFICATION.SEND_NOTIFICATION_HEALTH; END;',
    '&IAS_NOTIFICATION_HEALTH_SCHEDULE','Queues the IAS notification operational health report for Super Admin.');
END;
/

PROMPT === Remove obsolete standalone tracking table ===
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE T_AU_MGMT_AUDIT_WEEKLY_NOTIFY_LOG';
EXCEPTION WHEN OTHERS THEN IF SQLCODE<>-942 THEN RAISE; END IF;
END;
/

PROMPT === Queue API lifecycle validation (not an SMTP-delivery claim) ===
DECLARE
  V_EMAIL_ID NUMBER; V_TO VARCHAR2(320); V_STATUS VARCHAR2(20); V_RETRY NUMBER;
BEGIN
  SELECT MIN(E.EMAIL) INTO V_TO
    FROM T_USER_MAPING M JOIN T_USER U ON U.USERID=M.USERID
    JOIN V_SERVICE_EMPLOYEEINFO E ON E.PPNO=U.PPNO
   WHERE M.ROLE_ID=1 AND NVL(U.ISACTIVE,'Y')='Y' AND TRIM(E.EMAIL) IS NOT NULL;
  IF V_TO IS NULL THEN RAISE_APPLICATION_ERROR(-20805,'Cannot validate queue lifecycle: no Super Admin email.'); END IF;
  SAVEPOINT QUEUE_API_TEST;
  PKG_INQ.P_ENQUEUE_EMAIL('DEPLOYMENT_QUEUE_VALIDATION',NULL,NULL,V_TO,NULL,
    'IAS deployment queue validation','Rolled back after API state-transition validation.',V_EMAIL_ID);
  SELECT STATUS INTO V_STATUS FROM T_AU_IID_EMAIL_QUEUE WHERE EMAIL_ID=V_EMAIL_ID;
  IF V_STATUS<>'PENDING' THEN RAISE_APPLICATION_ERROR(-20806,'PENDING transition failed.'); END IF;
  PKG_INQ.P_MARK_EMAIL_FAILED(V_EMAIL_ID,'Deployment retry validation');
  SELECT STATUS,RETRY_COUNT INTO V_STATUS,V_RETRY FROM T_AU_IID_EMAIL_QUEUE WHERE EMAIL_ID=V_EMAIL_ID;
  IF V_STATUS<>'FAILED' OR V_RETRY<1 THEN RAISE_APPLICATION_ERROR(-20807,'FAILED/retry transition failed.'); END IF;
  PKG_INQ.P_MARK_EMAIL_SENT(V_EMAIL_ID);
  SELECT STATUS INTO V_STATUS FROM T_AU_IID_EMAIL_QUEUE WHERE EMAIL_ID=V_EMAIL_ID;
  IF V_STATUS<>'SENT' THEN RAISE_APPLICATION_ERROR(-20808,'SENT transition failed.'); END IF;
  ROLLBACK TO QUEUE_API_TEST;
  DBMS_OUTPUT.PUT_LINE('Validated PENDING -> FAILED (retry increment) -> SENT; test row rolled back.');
END;
/

COMMIT;
PROMPT === Deployment validation ===
SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('PKG_INQ','PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP')
 ORDER BY OBJECT_NAME,OBJECT_TYPE;
SELECT NAME,TYPE,LINE,POSITION,TEXT FROM USER_ERRORS
 WHERE NAME IN ('PKG_INQ','PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP')
 ORDER BY NAME,SEQUENCE;
SELECT JOB_NAME,ENABLED,STATE,REPEAT_INTERVAL,NEXT_RUN_DATE FROM USER_SCHEDULER_JOBS
 WHERE JOB_NAME IN ('JOB_MGMT_AUDIT_MAPPING_EXCEPT','JOB_IAS_NOTIFICATION_HEALTH')
 ORDER BY JOB_NAME;
SELECT EXECUTION_KEY,STATUS,RETRY_COUNT,CREATED_ON,UPDATED_ON
  FROM T_IAS_NOTIFY_EXECUTION WHERE EXECUTION_KEY LIKE 'WEEKLY:%'
 ORDER BY CREATED_ON DESC;
SELECT INDEX_NAME,STATUS FROM USER_INDEXES WHERE INDEX_NAME='UQ_IID_EMAIL_SCHED_NOTIFY';
SELECT PACKAGE_NAME,OBJECT_NAME,ARGUMENT_NAME,DATA_TYPE FROM USER_ARGUMENTS
 WHERE PACKAGE_NAME='PKG_INQ' AND OBJECT_NAME='P_GET_EMAIL_QUEUE' AND ARGUMENT_NAME='P_STATUS';

SET DEFINE OFF;
