-- Incremental upgrade for commit "Complete IAS system error monitoring".
-- Run after the earlier centralized system error monitoring script has been applied.
-- This script preserves existing monitoring data and creates/changes only missing objects.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_STATUS_HISTORY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE T_AU_SYSTEM_ERROR_STATUS_HISTORY
      (
          STATUS_HISTORY_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ERROR_ID           NUMBER NOT NULL,
          OLD_STATUS         VARCHAR2(30),
          NEW_STATUS         VARCHAR2(30) NOT NULL,
          CHANGED_BY_PPNO    VARCHAR2(50),
          CHANGED_ON_UTC     TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
          REMARKS            VARCHAR2(1000),
          CONSTRAINT FK_AU_SYS_ERR_STATUS_MASTER
              FOREIGN KEY (ERROR_ID) REFERENCES T_AU_SYSTEM_ERROR_MASTER(ERROR_ID)
      )';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_IND_COLUMNS
   WHERE INDEX_NAME = 'IX_AU_SYS_ERR_STATUS_ERROR_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_AU_SYS_ERR_STATUS_ERROR_ID ON T_AU_SYSTEM_ERROR_STATUS_HISTORY (ERROR_ID, CHANGED_ON_UTC)';
  END IF;
END;
/

DECLARE
  v_constraint_name VARCHAR2(128);
BEGIN
  FOR c IN (
    SELECT acc.CONSTRAINT_NAME
      FROM USER_CONSTRAINTS acc
      JOIN USER_CONS_COLUMNS col
        ON col.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
     WHERE acc.TABLE_NAME = 'T_AU_SYSTEM_ERROR_MASTER'
       AND acc.CONSTRAINT_TYPE = 'C'
       AND col.COLUMN_NAME = 'EMAIL_SENT'
       AND UPPER(acc.SEARCH_CONDITION_VC) LIKE '%EMAIL_SENT%'
       AND UPPER(acc.SEARCH_CONDITION_VC) NOT LIKE '%''P''%'
  ) LOOP
    v_constraint_name := c.CONSTRAINT_NAME;
    EXECUTE IMMEDIATE 'ALTER TABLE T_AU_SYSTEM_ERROR_MASTER DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_MASTER'
     AND CONSTRAINT_NAME = 'CK_AU_SYS_ERR_EMAIL_SENT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE T_AU_SYSTEM_ERROR_MASTER ADD CONSTRAINT CK_AU_SYS_ERR_EMAIL_SENT CHECK (EMAIL_SENT IN (''Y'',''N'',''P''))';
  END IF;
END;
/

UPDATE T_AU_SYSTEM_ERROR_MASTER
   SET EMAIL_SENT = 'N'
 WHERE EMAIL_SENT IS NULL;

COMMIT;

DECLARE
  v_admin_menu_id NUMBER;
  v_page_id NUMBER;

  PROCEDURE ensure_page(p_path IN VARCHAR2, p_title IN VARCHAR2) IS
  BEGIN
    BEGIN
      SELECT PAGE_ID
        INTO v_page_id
        FROM T_MENU_PAGES
       WHERE UPPER(PAGE_URL) = UPPER('/' || p_path)
          OR (UPPER(CONTROLLER_NAME) = 'ADMINISTRATIONPANEL'
          AND UPPER(ACTION_NAME) = UPPER(SUBSTR(p_path, INSTR(p_path, '/') + 1)))
       FETCH FIRST 1 ROWS ONLY;

      UPDATE T_MENU_PAGES
         SET CONTROLLER_NAME = 'AdministrationPanel',
             ACTION_NAME = SUBSTR(p_path, INSTR(p_path, '/') + 1),
             PAGE_URL = '/' || p_path,
             PAGE_TITLE = p_title,
             HIDE_MENU = 1
       WHERE PAGE_ID = v_page_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO T_MENU_PAGES
          (MENU_ID, PAGE_TITLE, PAGE_URL, CONTROLLER_NAME, ACTION_NAME, HIDE_MENU, PAGE_KEY)
        VALUES
          (v_admin_menu_id, p_title, '/' || p_path, 'AdministrationPanel',
           SUBSTR(p_path, INSTR(p_path, '/') + 1), 1, UPPER(REPLACE(p_path, '/', '_')))
        RETURNING PAGE_ID INTO v_page_id;
    END;

    MERGE INTO T_MENU_PAGES_GROUPMAP dst
    USING (SELECT v_page_id PAGE_ID, 1 GROUP_ID FROM dual) src
       ON (dst.PAGE_ID = src.PAGE_ID AND dst.GROUP_ID = src.GROUP_ID)
     WHEN NOT MATCHED THEN
       INSERT (PAGE_ID, GROUP_ID) VALUES (src.PAGE_ID, src.GROUP_ID);
  END;
BEGIN
  BEGIN
    SELECT MENU_ID
      INTO v_admin_menu_id
      FROM T_MENUS
     WHERE UPPER(MENU_NAME) IN ('ADMIN', 'ADMINISTRATION')
     FETCH FIRST 1 ROWS ONLY;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      SELECT MIN(MENU_ID) INTO v_admin_menu_id FROM T_MENUS;
  END;

  ensure_page('AdministrationPanel/SystemErrorMonitoring', 'System Error Monitoring');
  ensure_page('AdministrationPanel/SystemErrorDetail', 'System Error Detail');
  ensure_page('AdministrationPanel/GetSystemErrors', 'System Error Data');
  ensure_page('AdministrationPanel/ResolveSystemError', 'Resolve System Error');
  ensure_page('AdministrationPanel/ExportSystemErrors', 'Export System Errors');
END;
/

COMMIT;

-- Recompile the package body/spec from the version in this release.
@@PKG_LG.sql
