SET DEFINE OFF;

PROMPT IAS ALL_PACKAGES alignment corrections for changes since 03-Sep-2026.
PROMPT Scope: add missing PKG_LG.CLAIM_SYSTEM_ERROR_EMAIL without replacing unrelated package logic.

DECLARE
  c_decl CONSTANT VARCHAR2(4000) :=
    CHR(10) || '  PROCEDURE CLAIM_SYSTEM_ERROR_EMAIL(P_ERROR_ID IN NUMBER, O_CLAIMED OUT NUMBER);' || CHR(10);

  l_source CLOB;
  l_cursor INTEGER;
BEGIN
  SELECT XMLAGG(XMLELEMENT(e, TEXT) ORDER BY LINE).EXTRACT('//text()').GETCLOBVAL()
    INTO l_source
    FROM USER_SOURCE
   WHERE NAME = 'PKG_LG'
     AND TYPE = 'PACKAGE';

  IF l_source IS NULL THEN
    RAISE_APPLICATION_ERROR(-20001, 'PKG_LG package specification was not found in USER_SOURCE.');
  END IF;

  IF INSTR(UPPER(l_source), 'CLAIM_SYSTEM_ERROR_EMAIL') = 0 THEN
    l_source := REPLACE(
      l_source,
      '  PROCEDURE MARK_SYSTEM_ERROR_EMAIL',
      c_decl || '  PROCEDURE MARK_SYSTEM_ERROR_EMAIL'
    );

    IF INSTR(UPPER(l_source), 'CLAIM_SYSTEM_ERROR_EMAIL') = 0 THEN
      RAISE_APPLICATION_ERROR(-20002, 'Unable to locate PKG_LG MARK_SYSTEM_ERROR_EMAIL declaration anchor.');
    END IF;

    l_cursor := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(l_cursor, 'CREATE OR REPLACE ' || l_source, DBMS_SQL.NATIVE);
    DBMS_SQL.CLOSE_CURSOR(l_cursor);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    IF DBMS_SQL.IS_OPEN(l_cursor) THEN
      DBMS_SQL.CLOSE_CURSOR(l_cursor);
    END IF;
    RAISE;
END;
/

DECLARE
  c_body CONSTANT CLOB := q'[

  PROCEDURE CLAIM_SYSTEM_ERROR_EMAIL(P_ERROR_ID IN NUMBER, O_CLAIMED OUT NUMBER) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    UPDATE T_AU_SYSTEM_ERROR_MASTER
       SET EMAIL_SENT = 'P'
     WHERE ERROR_ID = P_ERROR_ID
       AND NVL(EMAIL_SENT, 'N') = 'N';

    O_CLAIMED := CASE WHEN SQL%ROWCOUNT = 1 THEN 1 ELSE 0 END;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END CLAIM_SYSTEM_ERROR_EMAIL;
]';

  l_source CLOB;
  l_cursor INTEGER;
BEGIN
  SELECT XMLAGG(XMLELEMENT(e, TEXT) ORDER BY LINE).EXTRACT('//text()').GETCLOBVAL()
    INTO l_source
    FROM USER_SOURCE
   WHERE NAME = 'PKG_LG'
     AND TYPE = 'PACKAGE BODY';

  IF l_source IS NULL THEN
    RAISE_APPLICATION_ERROR(-20003, 'PKG_LG package body was not found in USER_SOURCE.');
  END IF;

  IF INSTR(UPPER(l_source), 'END CLAIM_SYSTEM_ERROR_EMAIL') = 0 THEN
    l_source := REPLACE(
      l_source,
      '  PROCEDURE MARK_SYSTEM_ERROR_EMAIL',
      c_body || CHR(10) || '  PROCEDURE MARK_SYSTEM_ERROR_EMAIL'
    );

    IF INSTR(UPPER(l_source), 'END CLAIM_SYSTEM_ERROR_EMAIL') = 0 THEN
      RAISE_APPLICATION_ERROR(-20004, 'Unable to locate PKG_LG MARK_SYSTEM_ERROR_EMAIL body anchor.');
    END IF;

    l_cursor := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(l_cursor, 'CREATE OR REPLACE ' || l_source, DBMS_SQL.NATIVE);
    DBMS_SQL.CLOSE_CURSOR(l_cursor);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    IF DBMS_SQL.IS_OPEN(l_cursor) THEN
      DBMS_SQL.CLOSE_CURSOR(l_cursor);
    END IF;
    RAISE;
END;
/

ALTER PACKAGE PKG_LG COMPILE PACKAGE;
ALTER PACKAGE PKG_LG COMPILE BODY;

PROMPT PKG_LG alignment verification:
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'PKG_LG'
 ORDER BY OBJECT_TYPE;

SELECT NAME, TYPE, LINE, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'PKG_LG'
 ORDER BY SEQUENCE;

PROMPT IAS_ALL_PACKAGES_Alignment.sql completed.
