SET DEFINE OFF;

PROMPT IAS DB migration for commits from 03-Sep-2026 through latest.
PROMPT Scope: non-destructive structural prerequisites for application audit, system error monitoring, and engagement shifting.

--------------------------------------------------------------------------------
-- 1. Application audit log required by PKG_LG.P_LOG_APPLICATION_ACTIVITY
--------------------------------------------------------------------------------

DECLARE
  v_count NUMBER;

  PROCEDURE add_col(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
    v_exists NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_table)
       AND COLUMN_NAME = UPPER(p_column);

    IF v_exists = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_definition || ')';
    END IF;
  END;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'T_AU_APPLICATION_AUDIT_LOG';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE T_AU_APPLICATION_AUDIT_LOG
      (
        ID                    NUMBER NOT NULL,
        EVENT_TIME            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        EVENT_TYPE            VARCHAR2(50),
        ACTION_NAME           VARCHAR2(250) NOT NULL,
        ACTION_CATEGORY       VARCHAR2(100),
        MODULE_NAME           VARCHAR2(100),
        PPNO                  VARCHAR2(30),
        ROLE_ID               NUMBER,
        GROUP_ID              NUMBER,
        ENTITY_ID             NUMBER,
        USER_CONTEXT_ID       NUMBER,
        SESSION_ID            VARCHAR2(100),
        PAGE_ID               NUMBER,
        CONTROLLER_NAME       VARCHAR2(150),
        CONTROLLER_ACTION     VARCHAR2(150),
        API_PATH              VARCHAR2(500),
        HTTP_METHOD           VARCHAR2(20),
        DB_PACKAGE_NAME       VARCHAR2(100),
        DB_PROCEDURE_NAME     VARCHAR2(150),
        ENGAGEMENT_ID         NUMBER,
        PARA_ID               NUMBER,
        OLD_PARA_ID           NUMBER,
        NEW_PARA_ID           NUMBER,
        COM_ID                NUMBER,
        OBJECT_TYPE           VARCHAR2(100),
        OBJECT_ID             VARCHAR2(100),
        RESULT_STATUS         VARCHAR2(30) DEFAULT 'SUCCESS',
        RESULT_CODE           VARCHAR2(100),
        RESULT_MESSAGE        VARCHAR2(1000),
        CLIENT_IP_ADDRESS     VARCHAR2(100),
        PROXY_IP_ADDRESS      VARCHAR2(100),
        USER_AGENT            VARCHAR2(1000),
        TRACE_ID              VARCHAR2(150),
        REQUEST_ID            VARCHAR2(150),
        DURATION_MS           NUMBER,
        DETAILS               CLOB,
        CREATED_ON            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  ELSE
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'ID', 'ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'EVENT_TIME', 'EVENT_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'EVENT_TYPE', 'EVENT_TYPE VARCHAR2(50)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'ACTION_NAME', 'ACTION_NAME VARCHAR2(250)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'ACTION_CATEGORY', 'ACTION_CATEGORY VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'MODULE_NAME', 'MODULE_NAME VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'PPNO', 'PPNO VARCHAR2(30)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'ROLE_ID', 'ROLE_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'GROUP_ID', 'GROUP_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'ENTITY_ID', 'ENTITY_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'USER_CONTEXT_ID', 'USER_CONTEXT_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'SESSION_ID', 'SESSION_ID VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'PAGE_ID', 'PAGE_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'CONTROLLER_NAME', 'CONTROLLER_NAME VARCHAR2(150)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'CONTROLLER_ACTION', 'CONTROLLER_ACTION VARCHAR2(150)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'API_PATH', 'API_PATH VARCHAR2(500)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'HTTP_METHOD', 'HTTP_METHOD VARCHAR2(20)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'DB_PACKAGE_NAME', 'DB_PACKAGE_NAME VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'DB_PROCEDURE_NAME', 'DB_PROCEDURE_NAME VARCHAR2(150)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'ENGAGEMENT_ID', 'ENGAGEMENT_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'PARA_ID', 'PARA_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'OLD_PARA_ID', 'OLD_PARA_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'NEW_PARA_ID', 'NEW_PARA_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'COM_ID', 'COM_ID NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'OBJECT_TYPE', 'OBJECT_TYPE VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'OBJECT_ID', 'OBJECT_ID VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'RESULT_STATUS', 'RESULT_STATUS VARCHAR2(30) DEFAULT ''SUCCESS''');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'RESULT_CODE', 'RESULT_CODE VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'RESULT_MESSAGE', 'RESULT_MESSAGE VARCHAR2(1000)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'CLIENT_IP_ADDRESS', 'CLIENT_IP_ADDRESS VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'PROXY_IP_ADDRESS', 'PROXY_IP_ADDRESS VARCHAR2(100)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'USER_AGENT', 'USER_AGENT VARCHAR2(1000)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'TRACE_ID', 'TRACE_ID VARCHAR2(150)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'REQUEST_ID', 'REQUEST_ID VARCHAR2(150)');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'DURATION_MS', 'DURATION_MS NUMBER');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'DETAILS', 'DETAILS CLOB');
    add_col('T_AU_APPLICATION_AUDIT_LOG', 'CREATED_ON', 'CREATED_ON TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_T_AU_APPLICATION_AUDIT_LOG';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_AU_APPLICATION_AUDIT_LOG START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE';
  END IF;
END;
/

DECLARE
  PROCEDURE ensure_index(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;
BEGIN
  ensure_index('IX_APP_AUDIT_EVENT_TIME', 'CREATE INDEX IX_APP_AUDIT_EVENT_TIME ON T_AU_APPLICATION_AUDIT_LOG (EVENT_TIME)');
  ensure_index('IX_APP_AUDIT_PPNO', 'CREATE INDEX IX_APP_AUDIT_PPNO ON T_AU_APPLICATION_AUDIT_LOG (PPNO, EVENT_TIME)');
  ensure_index('IX_APP_AUDIT_SESSION', 'CREATE INDEX IX_APP_AUDIT_SESSION ON T_AU_APPLICATION_AUDIT_LOG (SESSION_ID)');
  ensure_index('IX_APP_AUDIT_ENTITY', 'CREATE INDEX IX_APP_AUDIT_ENTITY ON T_AU_APPLICATION_AUDIT_LOG (ENTITY_ID, EVENT_TIME)');
  ensure_index('IX_APP_AUDIT_ENGAGEMENT', 'CREATE INDEX IX_APP_AUDIT_ENGAGEMENT ON T_AU_APPLICATION_AUDIT_LOG (ENGAGEMENT_ID)');
  ensure_index('IX_APP_AUDIT_PARA', 'CREATE INDEX IX_APP_AUDIT_PARA ON T_AU_APPLICATION_AUDIT_LOG (PARA_ID)');
  ensure_index('IX_APP_AUDIT_COM', 'CREATE INDEX IX_APP_AUDIT_COM ON T_AU_APPLICATION_AUDIT_LOG (COM_ID)');
  ensure_index('IX_APP_AUDIT_TRACE', 'CREATE INDEX IX_APP_AUDIT_TRACE ON T_AU_APPLICATION_AUDIT_LOG (TRACE_ID)');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'T_AU_APPLICATION_AUDIT_LOG'
     AND CONSTRAINT_NAME = 'PK_T_AU_APPLICATION_AUDIT_LOG';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE T_AU_APPLICATION_AUDIT_LOG ADD CONSTRAINT PK_T_AU_APPLICATION_AUDIT_LOG PRIMARY KEY (ID)';
  END IF;
END;
/

DECLARE
BEGIN
  FOR c IN (
    SELECT uc.CONSTRAINT_NAME
      FROM USER_CONSTRAINTS uc
      JOIN USER_CONS_COLUMNS cc
        ON cc.CONSTRAINT_NAME = uc.CONSTRAINT_NAME
       AND cc.TABLE_NAME = uc.TABLE_NAME
     WHERE uc.TABLE_NAME = 'T_AU_APPLICATION_AUDIT_LOG'
       AND uc.CONSTRAINT_TYPE = 'C'
       AND cc.COLUMN_NAME = 'RESULT_STATUS'
       AND UPPER(uc.SEARCH_CONDITION_VC) NOT LIKE '%FAILURE%'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE T_AU_APPLICATION_AUDIT_LOG DROP CONSTRAINT ' || c.CONSTRAINT_NAME;
  END LOOP;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'T_AU_APPLICATION_AUDIT_LOG'
     AND CONSTRAINT_NAME = 'CK_APP_AUDIT_RESULT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE T_AU_APPLICATION_AUDIT_LOG ADD CONSTRAINT CK_APP_AUDIT_RESULT
      CHECK (RESULT_STATUS IN ('SUCCESS','FAILURE','VALIDATION','REJECTED','INFORMATION'))
    ]';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- 2. Centralized system error monitoring required by DBConnection.SystemError.cs
--------------------------------------------------------------------------------

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_MASTER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE T_AU_SYSTEM_ERROR_MASTER
      (
        ERROR_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ERROR_REFERENCE       VARCHAR2(50) NOT NULL,
        FINGERPRINT           VARCHAR2(128) NOT NULL,
        ERROR_TYPE            VARCHAR2(300),
        ERROR_CODE            VARCHAR2(100),
        MODULE                VARCHAR2(100),
        CONTROLLER            VARCHAR2(100),
        ACTION                VARCHAR2(100),
        API_PATH              VARCHAR2(1000),
        STORED_PROCEDURE      VARCHAR2(200),
        PPNO                  VARCHAR2(50),
        ROLE_NAME             VARCHAR2(150),
        ENTITY_NAME           VARCHAR2(300),
        PAGE_ID               NUMBER,
        ENG_ID                NUMBER,
        PARA_ID               NUMBER,
        COM_ID                NUMBER,
        FIRST_OCCURRENCE_UTC  TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
        LAST_OCCURRENCE_UTC   TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
        OCCURRENCE_COUNT      NUMBER DEFAULT 1 NOT NULL,
        LAST_TRACE_ID         VARCHAR2(200),
        LAST_IP_ADDRESS       VARCHAR2(100),
        ERROR_MESSAGE         CLOB,
        TECHNICAL_DETAILS     CLOB,
        EMAIL_SENT            CHAR(1) DEFAULT 'N',
        EMAIL_SENT_UTC        TIMESTAMP,
        RESOLUTION_STATUS     VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
        RESOLVED_BY           VARCHAR2(100),
        RESOLVED_ON_UTC       TIMESTAMP,
        RESOLUTION_REMARKS    VARCHAR2(1000),
        CONSTRAINT UK_AU_SYS_ERR_MASTER_FP UNIQUE (FINGERPRINT),
        CONSTRAINT UK_AU_SYS_ERR_MASTER_REF UNIQUE (ERROR_REFERENCE),
        CONSTRAINT CK_AU_SYS_ERR_EMAIL_SENT CHECK (EMAIL_SENT IN ('Y','N','P'))
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_HISTORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE T_AU_SYSTEM_ERROR_HISTORY
      (
        HISTORY_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ERROR_ID           NUMBER NOT NULL,
        OCCURRED_ON_UTC    TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
        TRACE_ID           VARCHAR2(200),
        IP_ADDRESS         VARCHAR2(100),
        USER_AGENT         VARCHAR2(1000),
        PPNO               VARCHAR2(50),
        ROLE_NAME          VARCHAR2(150),
        ENTITY_NAME        VARCHAR2(300),
        PAGE_ID            NUMBER,
        ENG_ID             NUMBER,
        PARA_ID            NUMBER,
        COM_ID             NUMBER,
        API_PATH           VARCHAR2(1000),
        ERROR_MESSAGE      CLOB,
        TECHNICAL_DETAILS  CLOB,
        CONSTRAINT FK_AU_SYS_ERR_HIST_MASTER FOREIGN KEY (ERROR_ID)
          REFERENCES T_AU_SYSTEM_ERROR_MASTER (ERROR_ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_STATUS_HISTORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE T_AU_SYSTEM_ERROR_STATUS_HISTORY
      (
        STATUS_HISTORY_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ERROR_ID           NUMBER NOT NULL,
        CHANGED_ON_UTC     TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
        OLD_STATUS         VARCHAR2(30),
        NEW_STATUS         VARCHAR2(30) NOT NULL,
        CHANGED_BY_PPNO    VARCHAR2(50),
        REMARKS            VARCHAR2(1000),
        CONSTRAINT FK_AU_SYS_ERR_STATUS_MASTER FOREIGN KEY (ERROR_ID)
          REFERENCES T_AU_SYSTEM_ERROR_MASTER (ERROR_ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_RECIPIENTS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE T_AU_SYSTEM_ERROR_RECIPIENTS
      (
        RECIPIENT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        RECIPIENT_TYPE  VARCHAR2(10) NOT NULL,
        EMAIL_ADDRESS   VARCHAR2(320) NOT NULL,
        DISPLAY_NAME    VARCHAR2(200),
        IS_ACTIVE       CHAR(1) DEFAULT 'Y' NOT NULL,
        SORT_ORDER      NUMBER DEFAULT 100 NOT NULL,
        CREATED_ON_UTC  TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
        CONSTRAINT CK_AU_SYS_ERR_RECIP_TYPE CHECK (RECIPIENT_TYPE IN ('TO','CC')),
        CONSTRAINT CK_AU_SYS_ERR_RECIP_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
      )
    ]';
  END IF;
END;
/

DECLARE
  PROCEDURE ensure_index(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;
BEGIN
  ensure_index('IX_AU_SYS_ERR_HIST_ERROR_ID',
               'CREATE INDEX IX_AU_SYS_ERR_HIST_ERROR_ID ON T_AU_SYSTEM_ERROR_HISTORY (ERROR_ID, OCCURRED_ON_UTC)');
  ensure_index('IX_AU_SYS_ERR_STATUS_ERROR_ID',
               'CREATE INDEX IX_AU_SYS_ERR_STATUS_ERROR_ID ON T_AU_SYSTEM_ERROR_STATUS_HISTORY (ERROR_ID, CHANGED_ON_UTC)');
  ensure_index('UX_AU_SYS_ERR_RECIP_EMAIL',
               'CREATE UNIQUE INDEX UX_AU_SYS_ERR_RECIP_EMAIL ON T_AU_SYSTEM_ERROR_RECIPIENTS (LOWER(EMAIL_ADDRESS), RECIPIENT_TYPE)');
END;
/

DECLARE
BEGIN
  FOR c IN (
    SELECT uc.CONSTRAINT_NAME
      FROM USER_CONSTRAINTS uc
      JOIN USER_CONS_COLUMNS cc
        ON cc.CONSTRAINT_NAME = uc.CONSTRAINT_NAME
       AND cc.TABLE_NAME = uc.TABLE_NAME
     WHERE uc.TABLE_NAME = 'T_AU_SYSTEM_ERROR_MASTER'
       AND uc.CONSTRAINT_TYPE = 'C'
       AND cc.COLUMN_NAME = 'EMAIL_SENT'
       AND UPPER(uc.SEARCH_CONDITION_VC) NOT LIKE '%''P''%'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE T_AU_SYSTEM_ERROR_MASTER DROP CONSTRAINT ' || c.CONSTRAINT_NAME;
  END LOOP;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  UPDATE T_AU_SYSTEM_ERROR_MASTER SET EMAIL_SENT = 'N' WHERE EMAIL_SENT IS NULL;

  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'T_AU_SYSTEM_ERROR_MASTER'
     AND CONSTRAINT_NAME = 'CK_AU_SYS_ERR_EMAIL_SENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE T_AU_SYSTEM_ERROR_MASTER ADD CONSTRAINT CK_AU_SYS_ERR_EMAIL_SENT
      CHECK (EMAIL_SENT IN ('Y','N','P'))
    ]';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- 3. Engagement entity shift history required by PKG_AD.P_SHIFT_ENGAGEMENT_ENTITY
--------------------------------------------------------------------------------

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'T_AU_ENG_ENTITY_SHIFT_HIST';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE T_AU_ENG_ENTITY_SHIFT_HIST
      (
        ID                         NUMBER PRIMARY KEY,
        ENG_ID                     NUMBER NOT NULL,
        OLD_ENTITY_ID              NUMBER NOT NULL,
        NEW_ENTITY_ID              NUMBER NOT NULL,
        REASON                     VARCHAR2(1000) NOT NULL,
        PPNO                       NUMBER NOT NULL,
        ROLE_ID                    NUMBER NOT NULL,
        SHIFTED_ON                 DATE DEFAULT SYSDATE NOT NULL,
        PLAN_ENG_ROWS              NUMBER DEFAULT 0 NOT NULL,
        OBSERVATION_ROWS           NUMBER DEFAULT 0 NOT NULL,
        AIS_OBSERVATION_ROWS       NUMBER DEFAULT 0 NOT NULL,
        OBS_ASSIGNEDTO_ROWS        NUMBER DEFAULT 0 NOT NULL,
        TEAM_TASKLIST_ROWS         NUMBER DEFAULT 0 NOT NULL,
        DSA_ROWS                   NUMBER DEFAULT 0 NOT NULL,
        OBSERVATION_MAN_ROWS       NUMBER DEFAULT 0 NOT NULL,
        BRANCH_RISK_RATING_ROWS    NUMBER DEFAULT 0 NOT NULL,
        COSO_RATING_DEPT_ROWS      NUMBER DEFAULT 0 NOT NULL,
        RISK_BRANCH_WISE_ROWS      NUMBER DEFAULT 0 NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_AU_ENG_ENTITY_SHIFT_HIST';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_AU_ENG_ENTITY_SHIFT_HIST START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

COMMIT;

PROMPT IAS_DB_Migration_03Sep2026.sql completed. Recompile package scripts after this migration.
