/*
Step 01 - Read-only prerequisite validation.
Execute first. If it raises any error, stop the deployment.
*/
DECLARE
  V_MISSING VARCHAR2(4000);
  V_COUNT NUMBER;
  V_NEXT_RUN TIMESTAMP WITH TIME ZONE;
BEGIN
  IF DBMS_DB_VERSION.VERSION < 18 THEN
    RAISE_APPLICATION_ERROR(
      -20801,
      'Oracle 18c or later is required by this deployment. Detected major version='||
      DBMS_DB_VERSION.VERSION||'.'
    );
  END IF;

  SELECT LISTAGG(REQUIRED_NAME, ', ') WITHIN GROUP (ORDER BY REQUIRED_NAME)
    INTO V_MISSING
    FROM (
      SELECT R.REQUIRED_NAME
        FROM (
          SELECT 'T_AUDITEE_ENTITIES' REQUIRED_NAME FROM DUAL UNION ALL
          SELECT 'T_AUDITEE_ENTITIES_MAPING' FROM DUAL UNION ALL
          SELECT 'AIS_T_AU_POST_COMPLIANCE' FROM DUAL UNION ALL
          SELECT 'AIS_T_AU_POST_COMPLIANCE_HISTORY' FROM DUAL UNION ALL
          SELECT 'T_AU_IID_EMAIL_QUEUE' FROM DUAL UNION ALL
          SELECT 'SEQ_AU_IID_EMAIL_QUEUE_ID' FROM DUAL UNION ALL
          SELECT 'T_USER' FROM DUAL UNION ALL
          SELECT 'T_USER_MAPING' FROM DUAL UNION ALL
          SELECT 'T_SYS_LOG' FROM DUAL UNION ALL
          SELECT 'V_GET_AIS_POST_COMPLIANCE' FROM DUAL UNION ALL
          SELECT 'V_SERVICE_EMPLOYEEINFO' FROM DUAL UNION ALL
          SELECT 'PKG_LG' FROM DUAL
        ) R
       WHERE NOT EXISTS (SELECT 1 FROM USER_OBJECTS O WHERE O.OBJECT_NAME=R.REQUIRED_NAME)
    );
  IF V_MISSING IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(-20800,'Missing prerequisite IAS objects: '||V_MISSING);
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='T_AUDITEE_ENTITIES'
     AND COLUMN_NAME IN ('ENTITY_ID','NAME','EMAIL_ADDRESS','AUDITBY_ID','ACTIVE','AUDITABLE');
  IF V_COUNT<>6 THEN
    RAISE_APPLICATION_ERROR(-20802,'Required T_AUDITEE_ENTITIES notification columns were not found.');
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='T_AUDITEE_ENTITIES_MAPING'
     AND COLUMN_NAME IN ('ENTITY_ID','PARENT_ID','DIV_OFFICE','REPORTING','B_GROUP','STATUS');
  IF V_COUNT<>6 THEN
    RAISE_APPLICATION_ERROR(-20803,'Required Division/Reporting mapping columns were not found.');
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='T_AU_IID_EMAIL_QUEUE'
     AND COLUMN_NAME IN
       ('EMAIL_ID','EVENT_CODE','REF_ID1','REF_ID2','MAIL_TO','MAIL_CC','SUBJECT','BODY',
        'STATUS','CREATED_ON','SENT_ON','ERROR_TEXT','RETRY_COUNT','CREATED_BY');
  IF V_COUNT<>14 THEN
    RAISE_APPLICATION_ERROR(-20804,'Required T_AU_IID_EMAIL_QUEUE columns were not found.');
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM USER_OBJECTS
   WHERE OBJECT_NAME='PKG_LG'
     AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY')
     AND STATUS='VALID';
  IF V_COUNT<>2 THEN
    RAISE_APPLICATION_ERROR(-20805,'Existing IAS error logger PKG_LG specification/body is not valid.');
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM SESSION_PRIVS
   WHERE PRIVILEGE IN ('CREATE JOB','CREATE ANY JOB');
  IF V_COUNT=0 THEN
    RAISE_APPLICATION_ERROR(-20806,'CREATE JOB privilege is required to configure IAS notification scheduler jobs.');
  END IF;

  DBMS_SCHEDULER.EVALUATE_CALENDAR_STRING(
    'FREQ=DAILY;BYHOUR=08;BYMINUTE=00;BYSECOND=00',
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    V_NEXT_RUN
  );
  IF V_NEXT_RUN IS NULL THEN
    RAISE_APPLICATION_ERROR(-20806,'DBMS_SCHEDULER calendar evaluation is unavailable.');
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM T_USER_MAPING M
    JOIN T_USER U ON U.USERID=M.USERID
    JOIN V_SERVICE_EMPLOYEEINFO E ON E.PPNO=U.PPNO
   WHERE M.ROLE_ID=1
     AND NVL(U.ISACTIVE,'Y')='Y'
     AND TRIM(E.EMAIL) IS NOT NULL;
  IF V_COUNT=0 THEN
    RAISE_APPLICATION_ERROR(-20807,'No active Super User (ROLE_ID=1) email recipient is configured.');
  END IF;

  SELECT COUNT(*) INTO V_COUNT
    FROM T_AUDITEE_ENTITIES E
   WHERE E.ENTITY_ID IN (112242,112248)
     AND TRIM(E.EMAIL_ADDRESS) IS NOT NULL;
  IF V_COUNT<>2 THEN
    RAISE_APPLICATION_ERROR(-20808,'Email addresses must be configured for both Management Audit heads 112242 and 112248.');
  END IF;

  DBMS_OUTPUT.PUT_LINE(
    'Preflight passed: Oracle '||DBMS_DB_VERSION.VERSION||
    '+, queue/schema prerequisites, Super User recipient, audit-head recipients and scheduler capability confirmed.'
  );
END;
/
