/*
Step 05 - Create the notification data-source views.
*/
/* Exactly one notification source row per COM_ID, independent of mapping-row count. */
CREATE OR REPLACE VIEW V_IAS_POST_COMPLIANCE_NOTIFY AS
WITH C AS
(
  SELECT X.*,
         ROW_NUMBER() OVER (PARTITION BY X.COM_ID ORDER BY X.ENTITY_ID,X.PARA_NO) RN
    FROM V_GET_AIS_POST_COMPLIANCE X
),
PARENT_EMAIL AS
(
  SELECT M.ENTITY_ID,
         LISTAGG(DISTINCT P.EMAIL_ADDRESS,';') WITHIN GROUP (ORDER BY P.EMAIL_ADDRESS) PARENT_EMAILS
    FROM T_AUDITEE_ENTITIES_MAPING M
    JOIN T_AUDITEE_ENTITIES P ON P.ENTITY_ID=M.PARENT_ID
   WHERE NVL(M.STATUS,'Y')='Y' AND TRIM(P.EMAIL_ADDRESS) IS NOT NULL
   GROUP BY M.ENTITY_ID
)
SELECT C.COM_ID,
       C.PARA_NO,
       C.GIST_OF_PARAS,
       C.AUDIT_PERIOD,
       C.RSK AS RISK,
       C.AUDITBY_ID,
       C.ENTITY_ID,
       E.EMAIL_ADDRESS AS TO_EMAIL,
       TRIM(BOTH ';' FROM A.EMAIL_ADDRESS||';'||P.PARENT_EMAILS) AS CC_EMAIL
  FROM C
  LEFT JOIN T_AUDITEE_ENTITIES E ON E.ENTITY_ID=C.ENTITY_ID
  LEFT JOIN T_AUDITEE_ENTITIES A ON A.ENTITY_ID=C.AUDITBY_ID
  LEFT JOIN PARENT_EMAIL P ON P.ENTITY_ID=C.ENTITY_ID
 WHERE C.RN=1;

/*
  Management Audit hierarchy:
  - only ACTIVE=Y and AUDITABLE=Y entities are reportable exceptions;
  - DIV_OFFICE identifies the digest owner/TO recipient;
  - REPORTING, with B_GROUP as the established fallback, identifies CC;
  - a Division resolving to multiple Reporting Offices/Groups is an exception,
    never a multi-recipient CC list.
*/
CREATE OR REPLACE VIEW V_IAS_MGMT_AUDIT_NOTIFY_MAP AS
WITH MAP_RAW AS
(
  SELECT M.ENTITY_ID,
         COUNT(*) MAPPING_ROWS,
         COUNT(DISTINCT M.DIV_OFFICE) DIVISION_COUNT,
         MIN(M.DIV_OFFICE) DIVISION_ID,
         COUNT(DISTINCT NVL(M.REPORTING,M.B_GROUP)) ENTITY_REPORTING_COUNT,
         MIN(NVL(M.REPORTING,M.B_GROUP)) ENTITY_REPORTING_ID
    FROM T_AUDITEE_ENTITIES_MAPING M
   WHERE NVL(M.STATUS,'Y')='Y'
   GROUP BY M.ENTITY_ID
),
ENTITY_MAP AS
(
  SELECT E.ENTITY_ID,E.NAME ENTITY_NAME,E.AUDITBY_ID AUDITED_BY,
         NVL(M.MAPPING_ROWS,0) MAPPING_ROWS,
         NVL(M.DIVISION_COUNT,0) DIVISION_COUNT,
         CASE WHEN M.DIVISION_COUNT=1 THEN M.DIVISION_ID END DIVISION_ID,
         NVL(M.ENTITY_REPORTING_COUNT,0) ENTITY_REPORTING_COUNT,
         CASE WHEN M.ENTITY_REPORTING_COUNT=1 THEN M.ENTITY_REPORTING_ID END ENTITY_REPORTING_ID
    FROM T_AUDITEE_ENTITIES E
    LEFT JOIN MAP_RAW M ON M.ENTITY_ID=E.ENTITY_ID
   WHERE E.AUDITBY_ID IN (112242,112248)
     AND E.ACTIVE='Y'
     AND E.AUDITABLE='Y'
),
DIVISION_MAP AS
(
  SELECT E.DIVISION_ID,
         COUNT(DISTINCT E.ENTITY_REPORTING_ID) DIVISION_REPORTING_COUNT,
         MIN(E.ENTITY_REPORTING_ID) DIVISION_REPORTING_ID,
         SUM(CASE WHEN E.ENTITY_REPORTING_COUNT<>1 THEN 1 ELSE 0 END) INCOMPLETE_ENTITY_COUNT
    FROM ENTITY_MAP E
   WHERE E.DIVISION_ID IS NOT NULL
   GROUP BY E.DIVISION_ID
)
SELECT E.ENTITY_ID,E.ENTITY_NAME,E.AUDITED_BY,E.DIVISION_ID,
       D.NAME DIVISION_NAME,D.EMAIL_ADDRESS DIVISION_EMAIL,
       NVL(DM.DIVISION_REPORTING_COUNT,0) DIVISION_REPORTING_COUNT,
       CASE WHEN DM.DIVISION_REPORTING_COUNT=1 AND DM.INCOMPLETE_ENTITY_COUNT=0
            THEN DM.DIVISION_REPORTING_ID END REPORTING_ID,
       CASE WHEN DM.DIVISION_REPORTING_COUNT=1 AND DM.INCOMPLETE_ENTITY_COUNT=0
            THEN R.NAME END REPORTING_NAME,
       CASE WHEN DM.DIVISION_REPORTING_COUNT=1 AND DM.INCOMPLETE_ENTITY_COUNT=0
            THEN R.EMAIL_ADDRESS END REPORTING_EMAIL,
       CASE WHEN E.MAPPING_ROWS>0 AND E.DIVISION_COUNT=1
                  AND TRIM(D.EMAIL_ADDRESS) IS NOT NULL
                  AND E.ENTITY_REPORTING_COUNT=1
                  AND DM.DIVISION_REPORTING_COUNT=1
                  AND DM.INCOMPLETE_ENTITY_COUNT=0
                  AND TRIM(R.EMAIL_ADDRESS) IS NOT NULL
            THEN 'Y' ELSE 'N' END MAPPING_READY,
       RTRIM(
         CASE WHEN E.MAPPING_ROWS=0 THEN 'Create active entity notification mapping; ' END||
         CASE WHEN E.DIVISION_COUNT=0 THEN 'Assign Divisional Office; '
              WHEN E.DIVISION_COUNT>1 THEN 'Resolve conflicting Divisional Office mappings; ' END||
         CASE WHEN E.DIVISION_COUNT=1 AND TRIM(D.EMAIL_ADDRESS) IS NULL THEN 'Add Divisional Head email; ' END||
         CASE WHEN E.ENTITY_REPORTING_COUNT=0 THEN 'Assign Reporting Office / Group; '
              WHEN E.ENTITY_REPORTING_COUNT>1 THEN 'Resolve conflicting entity Reporting Office / Group mappings; ' END||
         CASE WHEN DM.DIVISION_REPORTING_COUNT>1 THEN 'Resolve Division mapped to multiple Reporting Offices / Groups; ' END||
         CASE WHEN NVL(DM.INCOMPLETE_ENTITY_COUNT,0)>0 AND E.ENTITY_REPORTING_COUNT=1
              THEN 'Complete inconsistent Reporting Office / Group mappings within Division; ' END||
         CASE WHEN DM.DIVISION_REPORTING_COUNT=1 AND DM.INCOMPLETE_ENTITY_COUNT=0
                   AND TRIM(R.EMAIL_ADDRESS) IS NULL THEN 'Add Reporting Office / Group email; ' END,
         '; ') MISSING_REQUIRED_ACTION
  FROM ENTITY_MAP E
  LEFT JOIN T_AUDITEE_ENTITIES D ON D.ENTITY_ID=E.DIVISION_ID
  LEFT JOIN DIVISION_MAP DM ON DM.DIVISION_ID=E.DIVISION_ID
  LEFT JOIN T_AUDITEE_ENTITIES R ON R.ENTITY_ID=DM.DIVISION_REPORTING_ID;

DECLARE
  V_INVALID NUMBER;
  V_DUPLICATE_COM NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_INVALID
    FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP')
     AND OBJECT_TYPE='VIEW'
     AND STATUS<>'VALID';

  SELECT COUNT(*) INTO V_DUPLICATE_COM
    FROM (
      SELECT COM_ID
        FROM V_IAS_POST_COMPLIANCE_NOTIFY
       GROUP BY COM_ID
      HAVING COUNT(*)<>1
    );

  IF V_INVALID>0 OR V_DUPLICATE_COM>0 THEN
    RAISE_APPLICATION_ERROR(
      -20822,
      'Notification-view validation failed: invalid_views='||V_INVALID||
      ', duplicate_COM_ID_groups='||V_DUPLICATE_COM
    );
  END IF;
END;
/
