/*
Step 14 - Read-only post-deployment verification.
Final SENT/delivery results depend on the existing email queue worker.
*/
/* Read-only post-deployment evidence. Run after queue workers have processed test notifications. */

SELECT PC.AUDITED_BY,
       CASE WHEN H.COM_STATUS=16 THEN 'SETTLED' ELSE 'REJECTED' END DECISION,
       COUNT(*) QUEUED, SUM(CASE WHEN Q.STATUS='SENT' THEN 1 ELSE 0 END) SENT,
       SUM(CASE WHEN Q.STATUS='PENDING' THEN 1 ELSE 0 END) PENDING,
       SUM(CASE WHEN Q.STATUS='FAILED' THEN 1 ELSE 0 END) FAILED
  FROM T_AU_IID_EMAIL_QUEUE Q
  JOIN AIS_T_AU_POST_COMPLIANCE PC ON PC.COM_ID=Q.REF_ID1
  JOIN AIS_T_AU_POST_COMPLIANCE_HISTORY H ON H.HIST_ID=Q.REF_ID2 AND H.COM_ID=PC.COM_ID
 WHERE Q.EVENT_CODE='MGMT_AUDIT_PARA_STATUS' AND PC.AUDITED_BY IN (112242,112248)
 GROUP BY PC.AUDITED_BY,CASE WHEN H.COM_STATUS=16 THEN 'SETTLED' ELSE 'REJECTED' END
 ORDER BY PC.AUDITED_BY,DECISION;

SELECT PC.AUDITED_BY,PC.COM_ID,PC.AUDIT_PERIOD AUDIT_YEAR,PC.RSK RISK,PC.PARA_NO,
       H.HIST_ID,H.COMMENT_ON DECISION_ON,H.COMMENTS REJECTION_REASON,Q.EMAIL_ID,Q.STATUS
  FROM T_AU_IID_EMAIL_QUEUE Q
  JOIN AIS_T_AU_POST_COMPLIANCE PC ON PC.COM_ID=Q.REF_ID1
  JOIN AIS_T_AU_POST_COMPLIANCE_HISTORY H ON H.HIST_ID=Q.REF_ID2 AND H.COM_ID=PC.COM_ID
 WHERE Q.EVENT_CODE='MGMT_AUDIT_PARA_STATUS'
 ORDER BY Q.CREATED_ON DESC;

SELECT Q.REF_ID1 PERIOD_START_KEY,Q.REF_ID2 DIVISION_ID,Q.MAIL_TO,Q.MAIL_CC,Q.STATUS,
       COUNT(*) OVER (PARTITION BY Q.REF_ID1,Q.REF_ID2) ITEMS_FOR_DIVISION_PERIOD
  FROM T_AU_IID_EMAIL_QUEUE Q
 WHERE Q.EVENT_CODE='MGMT_AUDIT_WEEKLY_PARA_STATUS'
 ORDER BY Q.REF_ID1 DESC,Q.REF_ID2;
SELECT * FROM (
  SELECT ENTITY_ID,ENTITY_NAME,AUDITED_BY,DIVISION_ID,DIVISION_NAME,DIVISION_EMAIL,
         REPORTING_ID,REPORTING_NAME,REPORTING_EMAIL,MAPPING_READY
    FROM V_IAS_MGMT_AUDIT_NOTIFY_MAP WHERE MAPPING_READY='Y' ORDER BY ENTITY_ID
) WHERE ROWNUM<=3;

SELECT EMAIL_ID,REF_ID1 REPORT_DATE_KEY,REF_ID2 AUDITED_BY,MAIL_TO,STATUS,RETRY_COUNT,CREATED_ON,SENT_ON
  FROM T_AU_IID_EMAIL_QUEUE WHERE EVENT_CODE='MGMT_AUDIT_MAPPING_EXCEPTION'
 ORDER BY CREATED_ON DESC;
SELECT AUDITED_BY,ENTITY_ID,ENTITY_NAME,DIVISION_NAME,DIVISION_EMAIL,REPORTING_NAME,REPORTING_EMAIL,
       MISSING_REQUIRED_ACTION
  FROM V_IAS_MGMT_AUDIT_NOTIFY_MAP WHERE MAPPING_READY='N'
 ORDER BY AUDITED_BY,ENTITY_NAME;

SELECT STATUS,COUNT(*) ROWS_IN_STATE,MIN(CREATED_ON) OLDEST,MAX(SENT_ON) LAST_SENT,
       SUM(NVL(RETRY_COUNT,0)) RETRY_COUNT
  FROM T_AU_IID_EMAIL_QUEUE GROUP BY STATUS ORDER BY STATUS;
SELECT EVENT_CODE,COUNT(*) RETRIED_THEN_SENT,MAX(SENT_ON) LAST_RETRY_SUCCESS
  FROM T_AU_IID_EMAIL_QUEUE WHERE STATUS='SENT' AND NVL(RETRY_COUNT,0)>0
 GROUP BY EVENT_CODE ORDER BY EVENT_CODE;

SELECT PACKAGE_NAME,OBJECT_NAME,ARGUMENT_NAME,IN_OUT,DATA_TYPE
  FROM USER_ARGUMENTS
 WHERE PACKAGE_NAME='PKG_INQ' AND OBJECT_NAME='P_GET_EMAIL_QUEUE' AND ARGUMENT_NAME='P_STATUS';

SELECT JOB_NAME,ENABLED,STATE,REPEAT_INTERVAL,NEXT_RUN_DATE,LAST_START_DATE,LAST_RUN_DURATION,FAILURE_COUNT
  FROM USER_SCHEDULER_JOBS
 WHERE JOB_NAME IN ('JOB_MGMT_AUDIT_WEEKLY_NOTIFY','JOB_MGMT_AUDIT_MAPPING_EXCEPT','JOB_IAS_NOTIFICATION_HEALTH')
 ORDER BY JOB_NAME;

SELECT EMAIL_ID,MAIL_TO,STATUS,RETRY_COUNT,CREATED_ON,SENT_ON,ERROR_TEXT
  FROM T_AU_IID_EMAIL_QUEUE WHERE EVENT_CODE='IAS_NOTIFICATION_HEALTH'
 ORDER BY CREATED_ON DESC;
SELECT EVENT_CODE,COUNT(*) GENERATED_COUNT,
       SUM(CASE WHEN STATUS='SENT' THEN 1 ELSE 0 END) SENT,
       SUM(CASE WHEN STATUS='PENDING' THEN 1 ELSE 0 END) PENDING,
       SUM(CASE WHEN STATUS='FAILED' THEN 1 ELSE 0 END) FAILED,
       SUM(CASE WHEN STATUS='SENT' AND NVL(RETRY_COUNT,0)>0 THEN 1 ELSE 0 END) RETRIED_SUCCESSFULLY,
       MAX(SENT_ON) LAST_SUCCESSFUL_SEND
  FROM T_AU_IID_EMAIL_QUEUE
 WHERE EVENT_CODE IN ('MGMT_AUDIT_PARA_STATUS','MGMT_AUDIT_WEEKLY_PARA_STATUS','MGMT_AUDIT_MAPPING_EXCEPTION')
 GROUP BY EVENT_CODE ORDER BY EVENT_CODE;

SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('PKG_INQ','PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP')
 ORDER BY OBJECT_NAME,OBJECT_TYPE;
SELECT INDEX_NAME,STATUS FROM USER_INDEXES WHERE INDEX_NAME='UQ_IID_EMAIL_SCHED_NOTIFY';
SELECT NAME,TYPE,LINE,POSITION,TEXT FROM USER_ERRORS
 WHERE NAME IN ('PKG_INQ','PKG_AE','PKG_IAS_NOTIFICATION','V_IAS_POST_COMPLIANCE_NOTIFY','V_IAS_MGMT_AUDIT_NOTIFY_MAP')
 ORDER BY NAME,SEQUENCE;

SELECT COM_ID,COUNT(*) ROW_COUNT
  FROM V_IAS_POST_COMPLIANCE_NOTIFY
 GROUP BY COM_ID HAVING COUNT(*)<>1;

SELECT COUNT(*) NON_OPERATIONAL_ROWS
  FROM V_IAS_MGMT_AUDIT_NOTIFY_MAP M
  JOIN T_AUDITEE_ENTITIES E ON E.ENTITY_ID=M.ENTITY_ID
 WHERE NVL(E.ACTIVE,'N')<>'Y' OR NVL(E.AUDITABLE,'N')<>'Y';

SELECT DIVISION_ID,DIVISION_NAME,MAX(DIVISION_REPORTING_COUNT) SOURCE_REPORTING_COUNT,
       COUNT(DISTINCT REPORTING_ID) RESOLVED_REPORTING_COUNT,
       SUM(CASE WHEN MAPPING_READY='N' THEN 1 ELSE 0 END) EXCEPTION_ENTITIES
  FROM V_IAS_MGMT_AUDIT_NOTIFY_MAP
 GROUP BY DIVISION_ID,DIVISION_NAME
 ORDER BY DIVISION_NAME;
