const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
let requests = [], confirmations = [], allow = true, renders = 0, cancelled = null;
const element = { ready() {}, text() { return this; }, prop() { return this; }, addClass() { return this; }, removeClass() { return this; } };
function $(selector) { return element; }
$.each = (items, callback) => { for (let i = 0; i < items.length; i++) { if (callback(i, items[i]) === false) break; } };
$.map = (items, callback) => items.map(callback).filter(item => item != null);
$.ajax = options => requests.push(options);
const context = { $, document: {}, window: { confirm(message) { confirmations.push(message); return allow; } }, g_asiBaseURL: '', console,
    showApiAlert() {}, showApiAlertFromXhr() {}, getErrorReferenceIdFromXhr() {} };
vm.createContext(context);
vm.runInContext(fs.readFileSync('AIS/wwwroot/js/csp/Views_AdministrationPanel_manage_user.js', 'utf8'), context);
context.renderUserContexts = () => renders++;
context.renderUserList = () => {};
context.applyContextToBuilder = () => {};
context.cancelEditUserDetails = id => { cancelled = id; context.g_userId = 0; context.g_userContexts = []; };
context.escapeHtml = value => value || '';
const row = (id, isDefault = 'N') => ({ assignmentId: id, roleId: 2, groupId: 2, entityId: 3, isActive: 'Y', isDefault, roleName: 'Role', entityName: 'Entity', isDeleted: false });
context.g_userId = 7;
context.g_userList = [{ id: 7 }, { id: 8 }];
context.g_userContexts = [row(11, 'Y'), row(12)];
allow = false;
context.removeUserContext(0);
assert.equal(requests.length, 0, 'cancel leaves server and grid untouched');
assert.equal(context.g_userContexts.length, 2);
allow = true;
context.removeUserContext(0);
context.removeUserContext(0);
assert.equal(requests.length, 1, 'repeated clicks send a single immediate POST');
assert.equal(requests[0].url, '/AdministrationPanel/delete_user_context_assignment');
assert.equal(requests[0].type, 'POST');
assert.equal(requests[0].data.userId, 7);
assert.equal(requests[0].data.assignmentId, 11);
assert.equal(context.g_userContexts[0].isDeleted, false, 'no pending disable/save is queued');
requests[0].success({ status: true, userRemoved: false, assignments: [row(12, 'Y')] });
requests[0].complete();
assert.equal(context.g_userContexts.length, 1);
assert.equal(context.g_userContexts[0].assignmentId, 12);
assert.equal(context.g_userContexts[0].isDefault, 'Y', 'server default flags are refreshed');
assert.equal(context.g_userList[0].assignmentCount, 1);
context.removeUserContext(0);
assert.equal(requests.length, 2, 'final assignment bypasses normal Save validation');
requests[1].success({ status: true, userRemoved: true, assignments: [] });
requests[1].complete();
assert.equal(cancelled, 7);
assert.equal(context.g_userContexts.length, 0);
assert.deepEqual(Array.from(context.g_userList, user => user.id), [8], 'removed account leaves Manage User');
context.g_userId = 8;
context.g_userContexts = [row(20, 'Y')];
context.removeUserContext(0);
requests[2].error({ status: 500 });
requests[2].complete();
assert.equal(context.g_userContexts[0].assignmentId, 20, 'failure leaves the row intact');
context.g_userContexts = [row(0, 'Y')];
context.removeUserContext(0);
assert.equal(requests.length, 3, 'unsaved rows need no database deletion');
assert.equal(context.g_userContexts.length, 0);
assert.match(context.validateAssignments({ rowCount: 0, visibleAssignments: [] }), /at least one/);
assert.match(context.validateAssignments({ rowCount: 1, visibleAssignments: [{ ROLE_ID: 2, ENTITY_ID: 3, ISACTIVE: 'N', ISDEFAULT: 'N' }] }), /At least one active/);
assert.equal(context.validateAssignments({ rowCount: 1, visibleAssignments: [{ ROLE_ID: 2, ENTITY_ID: 3, ISACTIVE: 'Y', ISDEFAULT: 'Y' }] }), null);
context.g_userContexts = [];
context.upsertContext(row(0, 'Y'));
context.upsertContext({ ...row(0, 'Y'), entityId: 4 });
assert.equal(context.g_userContexts.length, 2, 'normal Add Assignment still works');
context.collectAssignmentsFromGrid = () => ({ rowCount: 1, visibleAssignments: [{ ROLE_ID: 2, ENTITY_ID: 3, ISACTIVE: 'Y', ISDEFAULT: 'Y' }], assignments: [] });
element.val = () => '123';
element.is = () => true;
$.trim = value => value.trim();
context.saveButtonClickHandler();
assert.equal(requests[3].url, '/AdministrationPanel/save_user_contexts', 'normal Save keeps its endpoint');
context.addNewUserButtonClickHandler();
assert.equal(JSON.parse(requests[4].data).USER_ID, null, 'normal Create still requests a new account');
const partial = fs.readFileSync('AIS/Views/FieldAudit/BO_Partials/_DraftReportPartial.cshtml', 'utf8');
assert.match(partial, /<div hidden style="display:none !important" aria-hidden="true">[\s\S]*?<select id="entitySelectField"[\s\S]*?@Model.EngagementId[\s\S]*?id="engIdHidden"/);
const pkg = fs.readFileSync('AIS/Docs/sql/PKG_USER_CONTEXT.sql', 'utf8');
const deletion = pkg.slice(pkg.indexOf('    PROCEDURE P_DELETE_USER_CONTEXT_ASSIGNMENT'), pkg.indexOf('    END P_DELETE_USER_CONTEXT_ASSIGNMENT;'));
assert.ok(deletion.indexOf("P_WRITE_HISTORY(V_ASSIGNMENT_ID, 'DELETE'") < deletion.indexOf('DELETE FROM T_USER_CONTEXT_ASSIGNMENT'));
assert.match(deletion, /DELETE FROM T_USER_MAPING WHERE USERID = P_USER_ID/);
assert.match(deletion, /UPDATE T_USER SET ISACTIVE = 'N'/);
assert.match(deletion, /P_SET_DEFAULT_USER_CONTEXT/);
assert.doesNotMatch(deletion, /P_DISABLE_USER_CONTEXT_ASSIGNMENT|DELETE FROM T_USER(?:\s|;)|COMMIT;/);
console.log('PASS: confirmation, immediate POST, repeat clicks, multi/final grid refresh, failure, unsaved removal, Add/Create/Save validation, hidden BO engagement; SQL safety assertions (not live DB QA).');

const fieldValues = {};
const draftElement = { length: 1, ready() {}, find() { return { length: 1 }; }, val(value) { if (value !== undefined) fieldValues[this.id] = value; return fieldValues[this.id]; }, prop() {} };
const draft = { window: { addEventListener() {} }, document: {}, console, $: selector => ({ ...draftElement, id: selector }) };
vm.createContext(draft);
vm.runInContext(fs.readFileSync('AIS/wwwroot/js/csp/Views_Execution_draft_audit_report_branch.js', 'utf8'), draft);
let draftLoads = 0;
draft.initializeDraftReportUi = () => {};
draft.getEntityObservation = () => { draftLoads++; };
draft.fieldAuditBoLoadDraftReport(123, false);
assert.equal(fieldValues['#entitySelectField'], '123');
assert.equal(fieldValues['#engIdHidden'], '123');
assert.equal(draftLoads, 1);
console.log('PASS: BO Step 1 initializer retains selected engagement and loads observations.');
